### ISSUE TITLE
Add API to Development service to manage SDKs

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#4437] opened 2021-09-28 18:36 UTC
This is meant as a location to start discussing some of the things we need in tooling such as Builder to do SDK management since we're running inside of a user namespace.

In particular, Builder has gone through great strife to manage SDKs on behalf the user. However, it is one of our biggest strengths because new developers to GNOME can simply clone a repository, and get going against org.gnome.Sdk//master as well as SDK extensions.

In Builder 41, we have code to fallback to a private SDK installation in case we can't install to the known installation which contains the remote/ref in question.

However, we still run into issues occasionally. For example, if we try to install `org.gnome.Sdk//master` we might pull in `org.freedesktop.Platform.openh264` which has `extra_data`. This is problematic in that it will try to run flatpak-bwrap to handle that script.

In most cases this isn't an issue, we can just `flatpak_transaction_set_disable_related()` however that only works so long as runtimes themselves don't use `extra_data` which is rather brittle.

It would be nice if we could get additional API on `org.freedesktop.Flatpak` `/org/freedesktop/Flatpak/Development` which allowed for installing or updating a ref (possibly to a private installation). It has some overlap with the `org.freedesktop.Flatpak.SystemHelper` although much simplified since IDE tooling really not need be concerned with bundles/summaries/etc.

I could probably donate time to implement the feature if I can get some coordination on design and how we should go about it from others, as I know it would allow me to delete large swaths of code from Builder.

**Comment by gasinvein** [comment] 2021-10-04 18:07
This seems to overlap with #3317, doesn't it?

**Comment by chergert** [comment] 2021-10-04 18:49
I don't think so because that will inevitably be tied to the application running as noted by `#2`.

> 2. which extends either the running app, or its runtime

In this case of IDE tooling like Builder, you'll need to be able to provide the installation location (likely private to avoid polluting the `--user` or `--system` installations along with the completely unrelated ref.

The only real reason this needs to be done outside the applications container is that `FlatpakTransaction` will try to spawn `flatpak-bwrap` in the case of `extra_data`. Otherwise, we'd happily go along maintaining our private SDKs inside the application container.

**Comment by mwleeds** [comment] 2021-10-08 22:17
Is this perhaps a duplicate of #4046?

> In this case of IDE tooling like Builder, you'll need to be able to provide the installation location (likely private to avoid polluting the --user or --system installations along with the completely unrelated ref.

In most cases you'd want to re-use an existing installation so that you avoid duplicating the disk usage in case the user already has the needed runtime installed, right?

**Comment by chergert** [comment] 2021-10-08 22:32
> In most cases you'd want to re-use an existing installation so that you avoid duplicating the disk usage in case the user already has the needed runtime installed, right?

Existing installation yes, but `--system` or `--user`, maybe not. In particular with Builder we need to keep the repositories we automatically add in a private installation so that we don't pollute the user's "trusted" installations with additional remotes. This is particularly necessary with the `gnome-nightly` remote (which has a plethora of not-ready applications) along with `flathub-beta` where we might need to get beta SDKs to resolve SDK extensions (which is required when `org.gnome.SDK//master` is preparing for release).

I think it would be okay to mark as duplicate of #4046 so long as we are allowing support for choosing which installation (and optionally providing a path) to the installation necessary. Another possibility would be for it to install using any installation, but provide paths to additional installations to check.

**Closed** 2021-10-08 23:06 UTC
