### ISSUE TITLE
Epiphany needs to talk to secrets service

### ISSUE THREAD

**Issue by kov** [flatpak/flatpak#340] opened 2016-10-10 12:11 UTC
For remembering and pre-filling passwords Epiphany needs to talk to org.freedesktop.secrets (it uses libsecrets).

**Comment by alexlarsson** [comment] 2016-10-13 07:05
I don't really know much about this api, but is it enough to grant the app access to talk to it?
I.e. flatpak run --talk-name=org.freedesktop.secrets

If so we could add this to the app.

However, in general exposing access to the secret database like that to a sandboxed app isn't all that great, because I don't think there is any real security (against other apps from the same user) in org.freedesktop.secrets. 

@stefwalter has some other ideas of how to better do sandboxed secrets support.

**Comment by TingPing** [comment] 2016-10-13 13:34
> I don't really know much about this api, but is it enough to grant the app access to talk to it?
I.e. flatpak run --talk-name=org.freedesktop.secrets

Yes.

**Comment by hadess** [comment] 2016-10-23 11:30
Duplicate of #362 ?

**Comment by matthiasclasen** [comment] 2018-10-08 00:13
yes, lets treat this as a duplicate of the xdg-desktop-portal issue about keyring access

**Closed by matthiasclasen** 2018-10-08 00:13 UTC
