### ISSUE TITLE
Installations and single updates always want to update everything

### ISSUE THREAD

**Issue by fbruetting** [flatpak/flatpak#1923] opened 2018-07-25 10:00 UTC
## Linux distribution and version
Fedora 28

## Flatpak version
0.99.3

## Description of the problem
Yesterday, a new platform runtime led to heavy UI problems, so today on my other machine, I just want to update KiCAD for getting the new version 5. So I ran `flatpak update org.kicad_pcb.KiCad`, but Flatpak always asks me to confirm updating everything. Also that `--app` option doesn’t change anything.

```
> flatpak update --app org.kicad_pcb.KiCad/x86_64/stable
Looking for updates...
Updating in system:
org.gnome.Platform/x86_64/3.26                 flathub ce4fc76f0f4e
org.gtk.Gtk3theme.Adapta-Eta/x86_64/3.22       flathub 7df05ed1c545
org.gtk.Gtk3theme.Adapta-Nokto-Eta/x86_64/3.22 flathub be8e29593c5e
org.gtk.Gtk3theme.Adapta-Nokto/x86_64/3.22     flathub a2621e8769ce
org.gtk.Gtk3theme.Adapta/x86_64/3.22           flathub 200066efa6dd
org.gnome.Platform.Locale/x86_64/3.26          flathub 9d202b1b339c
org.kicad_pcb.KiCad/x86_64/stable              flathub 9771545f483f
org.kicad_pcb.KiCad.Locale/x86_64/stable       flathub 3658e6cd0fc4
Is this ok [y/n]:
```

I also tried reinstalling, but that led to the same problem:
```
> flatpak install flathub org.kicad_pcb.KiCad
Installing in system:
org.kicad_pcb.KiCad/x86_64/stable        flathub 9771545f483f
  permissions: ipc, network, x11
  file access: home
org.kicad_pcb.KiCad.Locale/x86_64/stable flathub 3658e6cd0fc4
Updating in system:
org.gnome.Platform/x86_64/3.26                 flathub ce4fc76f0f4e
org.gtk.Gtk3theme.Adapta-Eta/x86_64/3.22       flathub 7df05ed1c545
org.gtk.Gtk3theme.Adapta-Nokto-Eta/x86_64/3.22 flathub be8e29593c5e
org.gtk.Gtk3theme.Adapta-Nokto/x86_64/3.22     flathub a2621e8769ce
org.gtk.Gtk3theme.Adapta/x86_64/3.22           flathub 200066efa6dd
org.gnome.Platform.Locale/x86_64/3.26          flathub 9d202b1b339c
Is this ok [y/n]:
```

## Steps to reproduce
`flatpak update <RDNS of a single package>` (works just in case that there are more updates available)

**Comment by mwleeds** [comment] 2018-07-25 23:21
I think that behavior is intentional but perhaps there could be a `--only` option to update only the specified ref. Then if the updated ref needs an updated runtime to function, I guess you'd have to error out?

**Comment by mwleeds** [comment] 2018-07-25 23:57
> I don’t think so. When I say update X, why should this affect Y or Z?

If the app update requires a new version of the runtime, then if flatpak were to only update the app, the updated app would fail to launch which is pretty useless. In the case where the updated app works with the same runtime, I think most users would want an updated runtime (and related refs) anyway.

> Also for example the filter options --app and --runtime would have no purpose anymore.

Those options only affect how flatpak interprets the refs passed on the command line: assume they're apps or assume they're runtimes. They're not about whether to only update apps or runtimes.

**Comment by fbruetting** [comment] 2018-07-26 00:34
Ok, maybe I know there is an error in a runtime and I don't want it to upgrade, or maybe the app just requires Gnome 3.28 and doesn't care about the exact version. Can this be implemented by either asking [y/n/all] or confirm two times for first bundle itself, and then it's references? (I have to test that --no-ref(?) switch tomorrow.)


Still, the question is: Why does also my Adapta theme get updated? I can't believe that they're referencing each others exact commit hash.


Am 26.07.2018 01:57 schrieb Matthew Leeds <notifications@github.com>:

I don’t think so. When I say update X, why should this affect Y or Z?

If the app update requires a new version of the runtime, then if flatpak were to only update the app, the updated app would fail to launch which is pretty useless. In the case where the updated app works with the same runtime, I think most users would want an updated runtime (and related refs) anyway.

Also for example the filter options --app and --runtime would have no purpose anymore.

Those options only affect how flatpak interprets the refs passed on the command line: assume they're apps or assume they're runtimes. They're not about whether to only update apps or runtimes.

**Comment by alexlarsson** [comment] 2018-08-08 16:09
`flatpak update --no-deps ...` should do what you want, no?

**Comment by alexlarsson** [comment] 2018-08-08 16:11
Adapta is updated because its refered to by the runtime theme extension point. If you don't want that --no-related will skip updating it.

**Comment by aiamuzz** [comment] 2018-08-08 16:31
hmmmm ... as update command is the topic ... 

Currently flatpak allows us to run separate update commands for multiple apps simultaneously provided they are run in a separate terminal window ...

however there are a couple of inefficiencies i'd like to report ...

1.
Say i run update commands for 2 specific app(for this example) and say both these apps require a particular platform-runtime to be updated first before the app itself is updated ... as a result of these 2 simultaneous update commands running ... both will start downloading the same platform-runtime in the 2 terminal windows ...

So you see, there is a redundant download taking place, its just not efficient(wasted downloaded bandwidth) also its not elegant too ... don't you think ?

2.
Shouldn't running `flatpak update` command update all apps including the ones installed at custom locations ? ... currently i need to run 2 update commands one for the default location and the other for my custom installation location which for me is ... `flatpak --installation=myFlatpaks update`

**Comment by alexlarsson** [comment] 2018-08-14 12:46
@aiamuzz 1 is very hard to work around, because the two instances don't know about each other. It should be safe though (i.e. only inefficient, not problematic). 2 seems wrong, can you open a separate issue about that.

Otherwise i'm closing this bug as it essentially works as intended.

**Closed by alexlarsson** 2018-08-14 12:46 UTC

**Comment by fbruetting** [comment] 2018-08-23 18:19
Today I installed Thunderbird-Flatpak, somehow also my Adapta theme was updated. I don’t understand why that gets pulled in? That should be totally negligible, as the Adapta version of the day before also worked fine for everything else…

**Comment by mwleeds** [comment] 2018-08-23 18:38
@fbruetting see https://github.com/flatpak/flatpak/issues/1923#issuecomment-411462631

**Comment by mwleeds** [comment] 2018-08-23 21:16
The runtime didn't need an update but a runtime extension, Adapta, needed an update. I don't see how that behavior is bad.

**Comment by fbruetting** [comment] 2018-08-23 21:17
Because I didn’t want to update anything. Sometimes I’m on a mobile connection and want to save my data.

**Comment by mwleeds** [comment] 2018-08-23 21:32
The install command has options called `--no-deps` and `--no-related` that I think would together approximate the behavior you want. But you'd have to be careful using them because if you install an app that depends on a runtime you don't have, you'd then have to install the runtime manually.

It sounds like what you really want is `--no-update-related` and `--no-update-deps` options that would install dependencies and related refs if they're not installed, but not update them if they are. I would guess that a patch to implement those would be considered.

**Comment by fbruetting** [comment] 2018-08-23 21:44
The thing that I’m not getting is the relation between Thunderbird and Adapta. With the runtime staying exactly the same, there should be no connection/relation/dependency at all…? At least I cannot imagine any connection here. :/

Still, I assume that others would also complain about such things when Flatpak gets more adoption in the future, so maybe staying minimal would make more sense?

These are the two screenshots I took:
![img_20180823_113819](https://user-images.githubusercontent.com/10520767/44553643-5d45f480-a72e-11e8-98f4-800d955e0656.jpg)
![img_20180823_115117](https://user-images.githubusercontent.com/10520767/44553645-5dde8b00-a72e-11e8-902b-6b45ee5951bb.jpg)

**Comment by mwleeds** [comment] 2018-08-23 21:58
The connection is that Thunderbird uses the runtime `org.gnome.Platform//3.28`[[1](https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.json#L3)] and that runtime has an extension point for gtk themes[[2](https://gitlab.gnome.org/GNOME/gnome-sdk-images/blob/master/org.gnome.Sdk.json.in#L18)] and Adapta uses that extension point. The idea behind this behavior is that generally when you install something you want its dependencies and related refs to be up-to-date, even if it's not strictly necessary that they are to get the app to run.

**Comment by fbruetting** [comment] 2018-08-23 22:01
Ah ok, now I get it. Thanks for the explanation!
