### ISSUE TITLE
Error: Unable to load summary from remote flathub

### ISSUE THREAD

**Issue by drom98** [flatpak/flatpak#3038] opened 2019-07-31 17:29 UTC
## Flatpak 1.2.4
When installing any app it gives me an error saying "error: Unable to load summary from remote flathub (...) handshake TLS"
Installing Spotify for example. (flatpak install flathub com.spotify.Client)

**Comment by mwleeds** [comment] 2019-07-31 21:42
Duplicate of #2331

**Closed by mwleeds** 2019-07-31 21:42 UTC

**Comment by mismatso** [comment] 2020-03-22 18:03
I had the same problem, but it was because I had been playing with my authority certificates, to install an internal CA.

To rule out this problem, I recommend reconfiguring authority certificates to ensure that all known public CAs are being considered.

`sudo dpkg-reconfigure ca-certificates`
