### ISSUE TITLE
[Bug]: Kernel 5.14.20 breaks xdg-document-portal (choosing a file) in a flatpak, causing flatpak apps to freeze upon picking a file

### ISSUE THREAD

**Issue by pizzadude** [flatpak/flatpak#4595] opened 2021-11-21 14:17 UTC
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

Be on kernel 5.14.20 in fedora 35
Enable flathub repo
flatpak install com.belmoussaoui.Obfuscate
flatpak run com.belmoussaoui.Obfuscate
choose a file
app freezes up
notice something like this in /var/log/messages

Nov 21 07:29:29 fedora-t580 kernel: aops:fuse_file_aops [fuse] ino:5e3ad53fdf779e10 dentry name:"blah.png"
Nov 21 07:29:29 fedora-t580 kernel: flags: 0x17ffffc0000017(locked|referenced|uptodate|lru|node=0|zone=2|lastcpupid=0x1fffff)
Nov 21 07:29:29 fedora-t580 kernel: raw: 0017ffffc0000017 ffffe34ac8288748 ffffe34ac8225c48 ffff97416b6ac4b8
Nov 21 07:29:29 fedora-t580 kernel: raw: 0000000000000000 0000000000000000 00000002ffffffff ffff9741a41bd000
Nov 21 07:29:29 fedora-t580 kernel: page dumped because: VM_BUG_ON_PAGE(PageLRU(page))
Nov 21 07:29:29 fedora-t580 kernel: ------------[ cut here ]------------
Nov 21 07:29:29 fedora-t580 kernel: kernel BUG at mm/swap.c:469!
Nov 21 07:29:29 fedora-t580 kernel: invalid opcode: 0000 [#1] SMP PTI
Nov 21 07:29:29 fedora-t580 kernel: CPU: 2 PID: 4934 Comm: fuse mainloop Tainted: G           OE     5.14.20-300.fc35.x86_64 #1

### Expected Behavior

for app not to freeze when picking a file

### Actual Behavior

app freezes when picking a file when relying on documents portal, dmesg shows some kernel error about fuse.

### Additional Information

fedora kernel 5.14.18 and below doesn't have this issue. I don't know if this is a kernel issue, or a flatpak issue. started happening in kernel  5.14.20 and above. still happens in kernel 5.15.3

**Comment by pizzadude** [comment] 2021-11-21 14:20
https://bugzilla.redhat.com/show_bug.cgi?id=2025285

**Comment by pizzadude** [comment] 2021-11-22 10:02
It happens with any flatpak that doesn't have permission for "home" or "host", meaning, uses portals to access files. It happens with org.duckstation.DuckStation, and org.desmume.DeSmuME, to name some more.

**Comment by smcv** [comment] 2021-11-22 18:15
This looks like a kernel bug (FUSE regression) that should be fixed in the kernel. There's nothing to be fixed in Flatpak here.

**Closed by smcv** 2021-11-22 18:15 UTC
Labels: bug

**Comment by pizzadude** [comment] 2021-11-22 19:02
@smcv can you comment that on the redhat bugzilla?

**Comment by smcv** [comment] 2021-11-24 11:32
This was reported upstream: https://lore.kernel.org/all/CAFxkdAqahwaN0u6u34d4CrMW7rYL=6TpWk1CcOn+uGQdEgkuTQ@mail.gmail.com/

A patch has been suggested upstream, so I'm hoping this regression will be fixed in 5.15.5.

5.14.21 has been announced to be end-of-life, so there will be no more 5.14.x releases and its users should move to 5.15.x.
