### ISSUE TITLE
Flatpak updates old NVIDIA

### ISSUE THREAD

**Issue by alex285** [flatpak/flatpak#2741] opened 2019-03-05 13:47 UTC
As you can see on screenshot; Also related to https://github.com/flatpak/flatpak/issues/2718

Flatpak 1.2.3

![screenshot from 2019-03-05 15-43-38](https://user-images.githubusercontent.com/11244308/53809669-e18af700-3f5d-11e9-969d-3b6725a54956.png)

**Comment by TingPing** [comment] 2019-03-05 16:44
Updating everything installed is logical.

So just marking as a Duplicate of #2718

**Closed by TingPing** 2019-03-05 16:44 UTC
