### ISSUE TITLE
Permission denied errors when updating flatpak apps

### ISSUE THREAD

**Issue by Veske** [flatpak/flatpak#1555] opened 2018-04-05 07:31 UTC
## Linux distribution and version

```
  OPERATING SYSTEM:   Arch rolling
    Kernel:           4.15.14-1-ARCH (x86_64)
    Desktop:          GNOME Shell 3.28.0
    Compiler:         GCC 7.3.1 20180312
```

## Flatpak version
```
➜  ~ pacman -Q flatpak
flatpak 0.11.3+4+g633a9cbf-1
```
## Description of the problem

I execute the command `flatpak update` and it fails due to permission denied errors.

## Steps to reproduce

No idea, I did a regular system update wich updated dependencies like Flatpak, Linux, Systemd and so on. After that the update for flatpak apps started failing.

Here is a log of failed update:
https://gist.github.com/Veske/2ffd4833234f68c7f535add4c68ef521

Here is flatpak update with strace: 
https://gist.github.com/Veske/d87f8c555d122627dc2d8764c596ef0e

**Comment by mople71** [comment] 2018-04-07 12:30
Facing the same issue here.

**Comment by mwleeds** [comment] 2018-04-09 02:57
Duplicate of #1507

**Closed by mwleeds** 2018-04-09 02:57 UTC
