### ISSUE TITLE
PPA for Ubuntu doesn't pull ostree and apps builds fail

### ISSUE THREAD

**Issue by csoriano89** [flatpak/flatpak#694] opened 2017-04-09 08:59 UTC
ostree needs to be installed for rofiles-fuse, otherwise builds of applications fails.

This has been an issue also for Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859884 
and Arch https://bugs.archlinux.org/task/53617?project=1&cat%5B0%5D=2&string=flatpak

Would be good if for the future we make sure the cross-distro experience doesn't break this way on a release for a tool that one of the main focus is to be cross-distro :)

**Comment by matthiasclasen** [comment] 2017-04-09 14:25
to be fair, this is entirely a packaging problem, and caused by distributions thinking it is a good idea to break upstream modules into a bunch of separate packages...

**Comment by alexlarsson** [comment] 2017-04-10 06:48
I updated the PPA with this dependency

**Comment by csoriano89** [comment] 2017-04-10 07:21
Yeah I know, in this case was the PPA maintained by Alex though.
In any case my point is, maybe we should make sure well-known distros (Debian, Fedora, SUSE, Ubuntu PPA, Arch) ship Flatpak as intended when a new dependency or release is done, otherwise the "image" of cross-distro breaks.
I don't mind to put the effort in that, since I already "have" to take care of the Newcomers apps working on most systems and know a few people using on those systems, I will just need a little of coordination or heads-up with new dependencies.

**Comment by alexlarsson** [comment] 2017-04-10 07:26
0.9.2-0alexlarsson3~xenial  etc should have this.

**Comment by matthiasclasen** [comment] 2017-04-13 19:55
Carlos, I assume we can close this then ?

**Closed by matthiasclasen** 2017-04-13 19:55 UTC

**Comment by csoriano89** [comment] 2017-04-13 20:09
yes, forgot to close it
