### ISSUE TITLE
I want to be able run flatpak bundles without installing

### ISSUE THREAD

**Issue by Anti-Ultimate** [flatpak/flatpak#408] opened 2016-11-22 04:44 UTC
Seriously, if I'm releasing development builds from git every day or so, I don't expect the user to really want to install every single one of them. AppImage is the only solution to my issue right now and I'd like to have Flatpak also do enable this.

**Comment by TingPing** [comment] 2016-11-22 11:18
Create a repository and they simply have to update.

**Comment by Anti-Ultimate** [comment] 2016-11-22 13:13
No, what I want is to have a single file that runs by clicking on it. To test development releases and to have the ability to pinpoint where something broke. A repository is not what I want

**Comment by probonopd** [comment] 2016-11-22 19:08
That's _exactly_ what AppImage was designed for. Flatpak is optimized for other aspects, e.g., download size efficiency.

**Comment by Anti-Ultimate** [comment] 2016-11-23 05:38
Yes, but the thing is that AppImageKit draws in useless libraries from apt the binary doesn't even need, just because Library Y is in Package X which contains 10 other libraries the application isn't linked to. Those just take up space and are completely useless.

I could copy the libaries into the AppDir manually like I used to do, but this has shown not to work well in the past with newer distros containing newer versions of libraries needed. And the libraries to compile can only be found on a specific distro (namely the one which has the libraries specified in the script).

It's not making it any better that my bash skills are baby-grade.

AppImages compiled against the Flatpak runtime, now that's something I would like.

**Comment by probonopd** [comment] 2016-11-23 17:19
@Anti-Ultimate in order not to spam this thread, I have opened a separate [issue](https://github.com/probonopd/AppImageKit/issues/297) for what you wrote above.

**Comment by alexlarsson** [comment] 2016-11-30 16:17
I understand you want this, but this is not inside the scope of flatpak. Closing.

**Closed by alexlarsson** 2016-11-30 16:17 UTC

**Comment by damianatorrpm** [comment] 2018-10-07 17:00
+1

**Comment by hcsubser** [comment] 2020-12-22 09:09
You should really take a deeper look into this.
It takes the best things from both worlds(appimages and flatpaks)
This can really make flatpaks much more flexible and far more useful.
I would really want to see something done about this

**Comment by gasinvein** [comment] 2020-12-22 09:55
I think that #4018, despite having completely different goal, might be a step towards this. It allows to "replace" runtime (`/usr`) with a user-provided directory. Do the same for app bundle (`/app`) - and I guess you'll effectively have the ability to run things without installation.

**Comment by ryanabx** [comment] 2024-05-08 08:19
@gasinvein : 

> I think that #4018, despite having completely different goal, might help implementing this, if someone decides to. It allows to "replace" runtime (`/usr`) with a user-provided directory. Do the same for app bundle (`/app`) - and I guess you'll effectively have the ability to run things without installation.

This is what I am trying to do at https://github.com/ryanabx/portapak (minus replacing the runtime)

However, if, for example, org.inkscape.Inkscape is not installed in the system or user installations, and you run, for example:

```shell
"flatpak --env=HOME=/var/home/ryanbrue --app-path=/run/user/1000/portapak/out/inkscape/files run org.inkscape.Inkscape
```

It will fail saying:

```
error: app/org.inkscape.Inkscape/x86_64/master not installed
```

It seems like flatpak still requires the app to be installed even if you override the app path :/

**Comment by TingPing** [comment] 2024-05-08 15:43
You can use the `FLATPAK_USER_DIR` env var to use custom locations for apps/runtimes.

**Comment by ryanabx** [comment] 2024-05-08 16:32
@TingPing :
> You can use the FLATPAK_USER_DIR env var to use custom locations for apps/runtimes. The installations feature might be better but that might require privileges.

Thank you! I did look into the installations feature but since it's name-based and not path-based I figured it wouldn't work as well for temporary repos. I did make a [feature request](https://github.com/flatpak/flatpak/issues/5795) recently for the ability to specify `--installation={PATH}` though, and I think that'd be a nice thing to have.

If I set `FLATPAK_USER_DIR`, will it expect the runtime to be there as well? What I'd like to be able to do is use the system or user-level installation to find the runtime, but have the app installed in a temporary repo OR just mount the files to /app directly if that's possible.

**Comment by TingPing** [comment] 2024-05-08 16:46
> If I set FLATPAK_USER_DIR, will it expect the runtime to be there as well? What I'd like to be able to do is use the system or user-level installation to find the runtime, but have the app installed in a temporary repo OR just mount the files to /app directly if that's possible.

It works for runtimes/extensions/apps. It will also use system level runtimes if they there.
