### ISSUE TITLE
"var_summary_get_metadata: assertion failed: (start <= end)" during flatpak update

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak#4470] opened 2021-10-09 16:56 UTC
## Linux distribution and version
Fedora 35 Workstation Beta

## Flatpak version
flatpak-1.12.1-1.fc35.x86_64

## Description of the problem
This started randomly happening today and disappeared after a few hours. "flatpak update" was crashing on SIGABRT with:

```
$ flatpak update
Looking for updates?
**
flatpak:ERROR:common/flatpak-variant-impl-private.h:1197:var_summary_get_metadata: assertion failed: (start <= end)
Bail out! flatpak:ERROR:common/flatpak-variant-impl-private.h:1197:var_summary_get_metadata: assertion failed: (start <= end)
```

It was also causing GNOME Software to crash every time on startup.

The problem was already mentioned by some people as present on latest F35, but nobody actually reported it as an (upstream) issue. It can also be resolved by removing the Flatpak cache [as mentioned here](https://github.com/flatpak/flatpak/issues/4005#issuecomment-908714653). Unfortunately, since the problem randomly disappeared, it is really hard to reproduce it, at least in my case.

**Comment by mwleeds** [comment] 2021-11-12 20:52
> This is filled also downstream (with many duplicates): https://bugzilla.redhat.com/show_bug.cgi?id=1948949
> 
> [Here](https://github.com/flatpak/flatpak/files/7328315/bad-summaries.zip) is a save of my broken summary files for a system flathub. When I overwrite the files in `~/.cache/flatpak/system-cache/summaries/` I'm able to reproduce the crash also with `flatpak remote-ls flathub --system`.
> 
> I do not know how this broke, might be I had a crash in a time when the file had been updating or something, which left it in an inconsistent state.
> 
> I also tried `sudo flatpak repair`, but it did not help. The only thing which helps is to remove the summaries cache directory.

Using your summary files and `flatpak remote-ls --cached flathub`, I'm getting the error message from #4127 not the one from this issue:
```
$ flatpak remote-ls --cached flathub
**
flatpak:ERROR:common/flatpak-variant-impl-private.h:1185:var_summary_get_ref_map: assertion failed: (end <= v.size)
Bail out! flatpak:ERROR:common/flatpak-variant-impl-private.h:1185:var_summary_get_ref_map: assertion failed: (end <= v.size)
Aborted (core dumped)
```

**Comment by mwleeds** [comment] 2021-11-12 23:19
I'm going to close this in favor of #4127 since I am nearly certain both issues have the same root cause (since they are both symptoms of a corrupt `.sub` summary).

**Closed by mwleeds** 2021-11-12 23:19 UTC
Labels: bug, high priority

**Comment by genodeftest** [comment] 2021-12-23 09:58
@mwleeds : Is it possible that this error is different than the one described in #4127?

1. I can reproduce the crash with the command line above:
```
$ LC_ALL=C flatpak remote-ls --cached flathub
**
flatpak:ERROR:common/flatpak-variant-impl-private.h:1185:var_summary_get_ref_map: assertion failed: (end <= v.size)
Bail out! flatpak:ERROR:common/flatpak-variant-impl-private.h:1185:var_summary_get_ref_map: assertion failed: (end <= v.size)
Aborted (core dumped)
```
2. The file you noted in the workaround on #4127 does not exist on my computer:
```
$ LC_ALL=C rm ~/.cache/flatpak/system-cache/summaries/*
rm: cannot remove '/home/christian/.cache/flatpak/system-cache/summaries/*': No such file or directory
```
Furthermore, `~/.cache/flatpak/system-cache/` is empty, i.e. there is no `summaries` directory in here.
3. Even after clearing the cache (`$ gio trash ~/.cache/flatpak/`), the issue persists. In this case, there are no files at all below `~/.cache/flatpak`.

Or is there a different workaround needed?

**Comment by mwleeds** [comment] 2021-12-23 18:04
@genodeftest sounds like on your system the cached summary is being stored at a different path. It might be possible to tell where by prepending the flatpak command with `strace -yy`

**Comment by LouiseAmelieRB** [comment] 2022-06-08 14:51
@mwleeds I'm not sure if this is still relevant for this issue specifically, but I also had the same error message. Deleting the cache as described in the workaround in #4127 did nothing. The only way I managed to fix it was:
```bash
flatpak remote-delete flathub --user
```
and use a system-wide remote instead.
