### ISSUE TITLE
Cannot Install Monodevelop 6.1 in Ubuntu 16.04 lts

### ISSUE THREAD

**Issue by Fariv** [flatpak/flatpak#733] opened 2017-04-25 08:12 UTC
I followed the instruction written in monodevelop website and copied and pasted it  `flatpak install --from https://download.mono-project.com/repo/monodevelop.flatpakref`

And it was progressing but later my internet connection was stopped for few seconds (may be 4-5 secs) but I found out that the download was interrupted.
From than, I can't seem to redownload it.

Terminal shows `user@user:~$ flatpak install --from https://download.mono-project.com/repo/monodevelop.flatpakref`
`Installing: com.xamarin.MonoDevelop/x86_64/stable`
`Required runtime for com.xamarin.MonoDevelop/x86_64/stable (org.freedesktop.Platform/x86_64/1.4) is not installed, searching...`
`Found in remote gnome, do you want to install it? [y/n]: y`
`Installing: org.freedesktop.Platform/x86_64/1.4 from gnome`

`Receiving delta parts: 0/8 76.2 kB/s 10.3 MB/117.3 MB 23 minutes 24 seconds remaining `                                                                 
`(flatpak install:6879): libsoup-CRITICAL **: async_send_request_return_result: assertion 'item->task != NULL' failed`

**`error:`** `While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome: Message` Corrupt

**Comment by alexlarsson** [comment] 2017-04-25 08:14
Can you give some more information about what happens?

**Comment by alexlarsson** [comment] 2017-04-25 08:29
Hmm, this looks like an ostree bug, and I have the vague feeling that I've seen it before. 

@cgwalters, do you know anything about this?

**Comment by alexlarsson** [comment] 2017-04-25 08:31
Can you try manually installing the runtime again. 
I.e. `flatpak install gnome org.freedesktop.Platform/x86_64/1.4`

**Comment by Fariv** [comment] 2017-04-25 08:40
well....
now, it shows 

`user@user:~$ flatpak install gnome org.freedesktop.Platform/x86_64/1.4`

`Installing: org.freedesktop.Platform/x86_64/1.4 from gnome`

`Receiving delta parts: 1/8 48.1 kB/s 17.3 MB/117.3 MB 34 minutes 38 seconds remaining`                                                                  
`error: While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome: Peer failed to perform TLS handshake`

**Comment by Fariv** [comment] 2017-04-25 08:46
after retrying it shows previous error. 
I mean this one 

> user@user:~$ flatpak install gnome org.freedesktop.Platform/x86_64/1.4
> Installing: org.freedesktop.Platform/x86_64/1.4 from gnome
> 
> Receiving delta parts: 1/8 121.0 kB/s 18.3 MB/115.7 MB 13 minutes 24 seconds remaining                                                                 
> (flatpak install:8459): libsoup-CRITICAL **: async_send_request_return_result: assertion 'item->task != NULL' failed
> 
> **error:** While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome: Message Corrupt

@alexlarsson

**Comment by alexlarsson** [comment] 2017-04-25 08:50
It works fine here, but that error smells like some kind of threading/race condition.

**Comment by Fariv** [comment] 2017-04-25 08:50
now it shows this 

> user@user:~$ flatpak install gnome org.freedesktop.Platform/x86_64/1.4
> Installing: org.freedesktop.Platform/x86_64/1.4 from gnome
> 
> Receiving delta parts: 1/8 189.6 kB/s 25.2 MB/115.7 MB 7 minutes 56 seconds remaining                                                                  
> **error:** While pulling runtime/org.freedesktop.Platform/x86_64/1.4 from remote gnome: Socket I/O timed out

**Comment by alexlarsson** [comment] 2017-04-25 08:52
Is that a network performance you expect btw?  I get 5 MB/s.

**Comment by Fariv** [comment] 2017-04-25 08:52
do you have any suspicion? may be, my Ubuntu 16.04 has something wrong in it. do you have any suggestion.

**Comment by alexlarsson** [comment] 2017-04-25 08:53
Do you have a proxy configuration? Some people have reported issues with that. I don't have a great suggestion though, and its hard to debug without being able to reproduce.

**Comment by Fariv** [comment] 2017-04-25 08:54
mine is mobile data. so it's speed is not stable. Max speed may be 200 kb/s and it fluctuates, sometimes

**Comment by Fariv** [comment] 2017-04-25 08:54
its a hotspot from my cellphone.

**Comment by alexlarsson** [comment] 2017-04-25 08:55
Lets wait for @cgwalters and see if he knows of any existing knowledge about this.

**Comment by Fariv** [comment] 2017-04-25 08:55
okay, thanks :)

**Comment by joakimx** [comment] 2017-06-20 19:09
Well, not sure if this helps but using library wifi I got the same error message, but switching to my mobile/data the issue was resolved. So it has to do with network connection?

**Comment by mwleeds** [comment] 2022-07-30 22:30
I assume this has probably been fixed in the intervening 5 years, since we haven't had folks commenting here saying they are affected.

**Closed by mwleeds** 2022-07-30 22:30 UTC
