### ISSUE TITLE
A lot of Flatpak applications with a file picker crashes when I try to open a file

### ISSUE THREAD

**Issue by pizzadude** [flatpak/flatpak#2558] opened 2019-01-11 05:06 UTC
## Linux distribution and version
Linux Mint 19.1

## Flatpak version
Flatpak 1.0.6 (from the official ppa)

## Description of the problem
Every flatpak application that uses the gnome filepicker like Discord or Filezilla crashes when I try to open / attach a file.

## Steps to reproduce
Fully update flatpak
Install filezilla or discord
Try to import something into filezilla or try to attach a file in discord
Instead of showing the filepicker / chooser it crashes.

```
Reading locale option from /home/pizzadude/.config/filezilla/filezilla.xml
wxD-Bus: Signal from /org/freedesktop/DBus, member NameAcquired
wxD-Bus: Reply with serial 2
wxD-Bus: Reply to RegisterClient, our object path is /org/gnome/SessionManager/Client41

(filezilla:2): Gdk-WARNING **: 00:02:43.002: Can't set ParentRelative background for window 0x8200366, depth of parent doesn't match

(filezilla:2): GLib-GIO-CRITICAL **: 00:02:44.185: g_unix_is_system_fs_type: assertion 'fs_type != NULL && *fs_type != '\0'' failed

(filezilla:2): GLib-GIO-CRITICAL **: 00:02:44.185: g_unix_is_system_device_path: assertion 'device_path != NULL && *device_path != '\0'' failed
```

I searched the error and I only found this https://gitlab.gnome.org/GNOME/glib/issues/1645

This only started happening today.

**Comment by eszlari** [comment] 2019-01-14 15:20
I can't reproduce this under Kubuntu 18.10. Maybe KDE is unaffected by it.

**Comment by fkrull** [comment] 2019-01-14 16:40
I also have this problem, but not in every application.

Affected:
* [VS Code](https://flathub.org/apps/details/com.visualstudio.code) (see also flathub/com.visualstudio.code#67)
* [Postman](https://flathub.org/apps/details/com.getpostman.Postman)
* [Sublime Text](https://flathub.org/apps/details/com.sublimetext.three)
* [Slack](https://flathub.org/apps/details/com.slack.Slack)
* [Mattermost](https://flathub.org/apps/details/com.mattermost.Desktop)
* [Filezilla](https://flathub.org/apps/details/org.filezillaproject.Filezilla)

Unaffected:
* [SpeedCrunch](https://flathub.org/apps/details/org.speedcrunch.SpeedCrunch)
* [Quod Libet](https://flathub.org/apps/details/io.github.quodlibet.QuodLibet)
* [Firefox](https://firefox-flatpak.mojefedora.cz/)
* [gedit](https://flathub.org/apps/details/org.gnome.gedit)
* [KeepassXC](https://flathub.org/apps/details/org.keepassxc.KeePassXC)
* [VLC](https://flathub.org/apps/details/org.videolan.VLC)
* [Gimp](https://flathub.org/apps/details/org.gimp.GIMP)
* [LibreOffice](https://flathub.org/apps/details/org.libreoffice.LibreOffice)

Interestingly, all my affected apps use prebuilt binaries (as does Discord, certainly), with the curious exception of Filezilla.

This is on Ubuntu 18.04 (GNOME/gnome-shell) with Flatpak 1.0.6 from https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak.

**Comment by eszlari** [comment] 2019-01-14 16:59
I opened a bug for `freedesktop-sdk`:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/594

**Comment by fxha** [comment] 2019-01-14 17:02
It's an issue in `GLib` in the flatpak runtime which is already fixed upstream. `vscode`, `slack` etc are using the `org.electronjs.Electron2.BaseApp` / `org.freedesktop.Sdk` package which depends on an isolated `GTK` runtime with the bad library. I don't know in which package the `GLib` library is bundled but it's definitely a flatpak runtime issue.

**Comment by zer0hedge** [comment] 2019-01-15 06:43
[Signal](https://hobo.house/2018/03/16/using-signal-desktop-on-fedora-with-flatpak/) is affected too. Flatpak 1.0.6, Fedora 28

**Comment by pizzadude** [comment] 2019-01-15 13:51
Snes9x is affected, and instead of crashing when you open the file picker it crashes at launch.

**Comment by scaratec** [comment] 2019-01-16 20:58
Atom is also affected. Currently unusable just like VS Code.

**Comment by matthiasclasen** [comment] 2019-01-16 22:36
the fix has been merged and is going through ci

**Closed by matthiasclasen** 2019-01-16 22:36 UTC

**Comment by scaratec** [comment] 2019-01-17 07:21
How can we use the fix? I*m using Ubuntu 18.04. I've run `flatpak update` and Flatpak itself is in the version 1.0.6.

**Comment by jjardon** [comment] 2019-01-17 16:10
@scaratec The fix is available in freedesktop-sdk 18.08.26, which has been imported to flathub now; please run `flatpak update` again

**Comment by fkrull** [comment] 2019-01-17 18:04
Yup, it works again for me. Great, thanks!

**Comment by scaratec** [comment] 2019-01-17 18:06
@jjardon Thank you so much!! It is working again!

**Comment by HunarPG** [comment] 2025-02-01 10:41
I seem to have the same issue right now
I am using vanilla arch with kde plasma and x11
Affected apps are Roselia Mupen ui N64 emulator and zen browser for me

**Comment by hfiguiere** [comment] 2025-02-01 14:08
Issue was closed 6 years ago. File a new. Don't comment on old one. It's rude.
