### ISSUE TITLE
I can not input Chinese(zh-cn) within flowblade

### ISSUE THREAD

**Issue by yichuang-zh** [flatpak/flatpak#3200] opened 2019-10-29 02:44 UTC
Debian Stretch 9.11 /Gnome
 Flatpak 1.2.4
I can not input Chinese(zh-cn) within flowblade

Open flowblade installed from flathub, click menu Tools>Titler, then press Ctrl+Space to switch to Chinese input method fcitx, but the fcitx did not appear. I can't type Chinese, I can only type in English.

ps:
I can input Chinese within the version of flowblade installed from Debian.

**Comment by mwleeds** [comment] 2019-11-08 18:35
Duplicate of https://github.com/flatpak/flatpak/issues/2031 ?

**Comment by yichuang-zh** [comment] 2019-11-10 09:12
I have read the contents of your prompt #2031 .
It seems that the problem described by #2031 is the same as the problem I am having.

Thanks you.

**Closed** 2019-11-10 16:51 UTC
