### ISSUE TITLE
bwrap: Can't make symlink at /var/run: File exists

### ISSUE THREAD

**Issue by omichalek** [flatpak/flatpak#2871] opened 2019-04-30 19:09 UTC
## Linux distribution and version
openSUSE Tumbleweed
## Flatpak version
1.2.4

Why is this still happening? I ran this program maybe a week ago without any problem.

```
user@machine:~$ flatpak run org.fedoraproject.MediaWriter
bwrap: Can't make symlink at /var/run: File exists
user@machine:~$ ls -al /var/run
lrwxrwxrwx 1 root root 4 dub 24  2018 /var/run -> /run
user@machine:~$ flatpak --version
Flatpak 1.2.4
user@machine:~$ uname -a
Linux machine 5.0.5-1-default #1 SMP Wed Mar 27 11:22:35 UTC 2019 (0fb0b14) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alexlarsson** [comment] 2019-05-09 10:13
This is a duplicate of #2710 which is now fixed.

**Closed by alexlarsson** 2019-05-09 10:13 UTC
