### ISSUE TITLE
.var/app variable

### ISSUE THREAD

**Issue by damianatorrpm** [flatpak/flatpak#3036] opened 2019-07-30 14:58 UTC
## Linux distribution and version
Fedora Rawhide Silveblue 

## Flatpak version
1.4.0

## Description of the problem
Is there an environment variable to set this to a different directory?
If I have the same application installed system-wide and as user but different branches of them (stable, testing) I can make sure that the testing one does not screw up the configuration used by the stable one, by pointing the testing branch to user a different directory for configuration rather than .var/app/

**Comment by mwleeds** [comment] 2019-07-30 17:44
No that's not configurable. It's something that will be added to the freedesktop.org spec eventually. Closing this as a duplicate of https://github.com/flatpak/flatpak/issues/2746

**Closed by mwleeds** 2019-07-30 17:44 UTC

**Comment by damianatorrpm** [comment] 2019-07-31 06:07
@mwleeds Exactly it's not but it should be. 

flatpak-run.c
```
1418 | g_autoptr(GFile) var_app = g_file_resolve_relative_path (home, ".var/app");
-- | --
1419 |  
1420 | return g_file_get_child (var_app, app_id);
… |  
1993 | filename = g_build_filename (g_get_home_dir (),
1994 | ".var/app", app_id,
```
any other places this is needed to be patched you know of. I will create a copr of the forked flatpak
