### ISSUE TITLE
lot of blank lines when installing

### ISSUE THREAD

**Issue by biji** [flatpak/flatpak#266] opened 2016-08-26 12:14 UTC
`flatpak install gnome-nightly org.gnome.Platform master`
show a lot of blank lines (enter) in terminal, previously it show progress bar

I'm using fedora 24

thanks

**Comment by dbnicholson** [comment] 2016-08-26 17:19
I believe this is a duplicate of #251.

**Comment by alexlarsson** [comment] 2016-08-29 10:14
closing as dup

**Closed by alexlarsson** 2016-08-29 10:14 UTC
