### ISSUE TITLE
flatpak autoremove command?

### ISSUE THREAD

**Issue by hubslave** [flatpak/flatpak#1513] opened 2018-03-21 23:49 UTC
Hello,

I was just wondering if flatpak has some similar command to `yum autoremove`

Flatpak applications sometimes install "dependencies" such as kde platform, gnome platform etc.

And sometimes new version of applications pull new dependencies, such as new version of this platform, but the old version of platform still stays on the system.

So I can have installed gnome.platform.3.22, gnome.platform.3.24, gnome.platform.3.26 at the same time, even though maybe just the latest one is needed as a dependency to applications in my computer and gnome.platform.3.22 and gnome.platform.3.24 is not needed anymore.

Is there some command which can remove this unneeded (obsolete) dependencies?

I'm sorry if this question was already answered but I can't find any solution to this problem.

Thank you very much and have a nice day :)

**Comment by user5145** [comment] 2018-03-22 22:48
it's a bit similar to #506 
I agree it's probably the most requested feature for now. The easiest method to get rid of it is to remove all runtimes manually and update flatpak apps.

**Comment by TingPing** [comment] 2018-03-22 22:58
Duplicate of #506

**Closed by TingPing** 2018-03-22 22:58 UTC

**Comment by hubslave** [comment] 2018-03-22 23:16
@user5145 Thank you very much for your tip, I usually do it this way too :)
