### ISSUE TITLE
remote-ls fails and exits on invalid/unavailable local repositories

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#4840] opened 2022-04-07 09:28 UTC
`flatpak-1.12.7-1.fc36.x86_64`

I'm trying to list all the runtimes with "kde" in the name, and it's an excercise in frustration when I have multiple local repositories configured for applications that are built locally:
```sh
$ flatpak remote-ls | grep -i kde
error: Unable to load summary from remote gbe-plus: Remote listing for gbe-plus not available; server has no summary file. Check the URL passed to remote-add was valid.
$ flatpak remote-delete gbe-plus 
$ flatpak remote-ls | grep -i kde
error: Unable to load summary from remote ghb-test: Remote listing for ghb-test not available; server has no summary file. Check the URL passed to remote-add was valid.
$ flatpak remote-delete ghb-test
$ flatpak remote-ls | grep -i kde
error: Unable to load summary from remote libportal-test: Remote listing for libportal-test not available; server has no summary file. Check the URL passed to remote-add was valid.
$ flatpak remote-delete libportal-test
$ flatpak remote-ls | grep -i kde
error: Unable to load summary from remote rhythmbox: Remote listing for rhythmbox not available; server has no summary file. Check the URL passed to remote-add was valid.
```
at which point I stopped removing local repositories.

**Comment by hadess** [comment] 2022-04-07 17:17
> @hadess how did you create those repos? What does your repo config file look like?

For the rhythmbox repo, the repository directory is an empty directory. I would expect the code in flatpak to skip over invalid repositories.

(Most of those are repositories are created when I first start maintaining an application, I would create a local repo I can install test builds from without hitting Flathub. The repos live in the source directory, so get nuked by `git clean -dxf`, and the directory might get recreated if I launch a build, but stop it before it has time to be exported to the repo)

**Comment by mwleeds** [comment] 2022-04-07 19:53
Yeah I would agree, Flatpak should treat an error from any single remote as a warning rather than a fatal error. I'm not convinced it would be good to just silently skip over the invalid ones.

**Comment by hadess** [comment] 2022-04-07 20:57
> I'm not convinced it would be good to just silently skip over the invalid ones.

When did I mention silently skipping over invalid remotes? It errors out when it encounters the first one. `flatpak remote-ls` is unusable with local development repos in various state of brokenness.

**Comment by mwleeds** [comment] 2022-04-07 22:16
You said "skip over invalid repositories" but I understand that doesn't necessarily mean skip over them silently. :+1:

**Comment by mwleeds** [comment] 2022-04-07 22:27
Thanks for the bug report

**Comment by hfiguiere** [comment] 2024-02-10 20:52
Dupe of #1439

**Closed by hfiguiere** 2024-02-10 20:52 UTC
Labels: bug, cli
