### ISSUE TITLE
[Feature request]: Ability to run executables by name via PATH

### ISSUE THREAD

**Issue by CodeCubeNeo** [flatpak/flatpak#5190] opened 2022-11-25 12:50 UTC
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Hello. I know this is a long shot, but it would make the whole flatpak ecosystem more scriptable and usable if it had the same approach to standalone executables (not to be run throught flatpak, ig something like snapcraft). Any input is welcome

**Comment by matthiasclasen** [comment] 2022-11-26 14:37
It is  not clear what you are asking for

**Comment by rusty-snake** [comment] 2022-11-26 15:57
My understanding is he asks for a single executable that does not depend on system libraries which bundles app+runtime together with flatpak+xdp+xdp+bwrap. So you can distribute a single file an execute it.

If bwrap has to be suid this can not work.

**Comment by CodeCubeNeo** [comment] 2022-11-26 18:49
With snaps you can run any package through the terminal by just typing "gimp". For flatpak jou have to run it through flatpak, smth like " flatpak @f org.gimp.gimp". Does that make more sense. Ig that flatpak apps this way would be detected by d-menu?

**Comment by RushingAlien** [comment] 2022-11-28 02:10
you can add `/var/lib/flatpak/exports/bin` and `~/.local/share/flatpak/exports/bin` to PATHicate similar results
now you can simply type `org.gimp.GIMP` to run it from  the terminal

**Comment by smcv** [comment] 2022-11-29 15:02
I've retitled the feature request to clarify what was being requested, because it was not at all clear what "standalone" was meant to mean. In the context of Flatpak, I would usually interpret "standalone" as [something similar to this previous comment](https://github.com/flatpak/flatpak/issues/5190#issuecomment-1328070686), or maybe a request to be able to run an app without a runtime, both of which are intentionally not something we support.

> you can add /var/lib/flatpak/exports/bin and ~/.local/share/flatpak/exports/bin to PATH to replicate similar results

Yes, adding `exports/bin` to the `PATH` and running the app by its app-ID is Flatpak's official answer to this.

#3573 is a previous request to add `exports/bin` to the `PATH` by default. This was intentionally not done when the `exports/bin` feature was added in #1254. The author of that feature [wrote](https://github.com/flatpak/flatpak/issues/1188#issuecomment-351963471): "I don't want to auto-add the wrapper dirs to the real PATH, because such a modification is bound to break a lot of users setups". See #3573 for more on that.

`exports/bin` intentionally contains namespaced reversed-DNS names like `org.gimp.GIMP`, not short names like `gimp`. If you are a CLI user and you want to invoke Flatpak apps from a CLI by a short name of your choice, you have control over what those short names mean for you: you can set up shell aliases like `alias gimp='flatpak run org.gimp.GIMP'`, or functions like `gimp () { flatpak run org.gimp.GIMP "$@" }`, during your shell initialization.

Flatpak intentionally does not use non-namespaced names. This is partly a security feature: we don't want an app with a crafted name like `com.example.DrivingTestPractice.Guaranteed.Pass` to be able to steal input that was intended for the OS's installation of the `pass(1)` password manager. Snap's security model seems to rely on the operators of Canonical's centralized Snap app repository being able to recognise and ban malicious apps that try to use this trick before they do too much damage (taking on that responsibility is a choice they can make, but certainly not the one I would have chosen).

Not using non-namespaced names is also partly so that the maintainers of Flathub and other Flatpak repositories don't have to spend their time resolving the fights over short names that traditional Linux distributions get dragged into, like [whether `yarn` is a packaging format or a test tool](https://github.com/yarnpkg/yarn/issues/3189) and [whether `node` is an amateur radio tool or a JavaScript runtime](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907). Canonical are perhaps more willing to deal with this sort of thing than Flathub is, because Canonical also produce a traditional Linux distribution (Ubuntu), so they are going to have to deal with upstreams fighting over a desirable short name *anyway*.

**Closed by smcv** 2022-11-29 15:02 UTC
Labels: enhancement
