### ISSUE TITLE
Flatpak doesn't automatically create application menu entry anymore?

### ISSUE THREAD

**Issue by sprite-1** [flatpak/flatpak#2886] opened 2019-05-08 01:21 UTC
## Linux distribution and version
elementary OS 5.0
## Flatpak version
1.3.3
## Description of the problem
When I used flatpak before to install an application, it automatically created an entry for the app in the application menu. Now, trying to install the same application, it doesn't do that anymore.
## Steps to reproduce
1. Install [Authenticator](https://flathub.org/apps/details/com.github.bilelmoussaoui.Authenticator) from the Flathub
2. There's no automatically created application menu entry

**Comment by mwleeds** [comment] 2019-05-08 16:46
Is it possible you need to log out and back in? I believe that's the case right after you install flatpak itself.

**Comment by sprite-1** [comment] 2019-05-08 17:11
Does it specifically need to be a logout? Because I restarted after installing flatpak as per the instructions here

https://flatpak.org/setup/elementary%20OS/

**Comment by mwleeds** [comment] 2019-05-08 19:22
No a reboot should work. Check if you can reproduce the issue with applications other than Authenticator?

**Comment by sprite-1** [comment] 2019-05-08 22:40
Well I've installed HexChat and Almond to the same effect (no shortcuts created)

**Comment by matthiasclasen** [comment] 2019-05-09 15:04
Most likely the location where flatpak extracts the desktop files does not get added to XDG_DATA_DIRS for you. What do the following commands say ?

```
echo $XDG_DATA_DIRS 
ls /var/lib/flatpak/exports/share/applications
ls /etc/profile.d/
```

**Comment by sprite-1** [comment] 2019-05-10 07:04
`echo $XDG_DATA_DIRS ` result
```
/usr/share/gnome:/usr/share/pantheon:/home/sprite-1/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
```

`ls /var/lib/flatpak/exports/share/applications` result
```
com.github.bilelmoussaoui.Authenticator.desktop  io.github.Hexchat.desktop
edu.stanford.Almond.desktop                      mimeinfo.cache
```

`ls /etc/profile.d/` result
```
01-locale-fix.sh       flatpak.sh                      qt-qpa-platformtheme.sh
apps-bin-path.sh       gtk-csd.sh                      qt-style-override.sh
bash_completion.sh     input-method-config.sh          vte-2.91.sh
cedilla-portuguese.sh  pantheon-filechooser-module.sh  xdg_dirs_desktop_session.sh
```

Also for some reason it just randomly started working now after a reboot (one of the many I did), the icons were there. I tried installing another app (GNOME Maps) and that worked now too with the shortcut being properly created.

**Comment by mwleeds** [comment] 2019-05-10 07:14
Looks like $XDG_DATA_DIRS is set correctly for you. Closing this issue until someone else can reproduce. It might also make sense to report it as a bug against Elementary OS in that case.

**Closed by mwleeds** 2019-05-10 07:14 UTC

**Comment by ThellraAK** [comment] 2020-05-03 06:01
In Lubuntu 20.04 this also happened to me, with virtually the same outputs.

:~$ echo $XDG_DATA_DIRS 
/usr/share/Lubuntu:/home/hilarie/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop

:~$ ls /var/lib/flatpak/exports/share/applications
io.github.endless_sky.endless_sky.desktop  mimeinfo.cache  org.flarerpg.Flare.desktop

:~$ ls /etc/profile.d/
01-locale-fix.sh  bash_completion.sh     flatpak.sh  gawk.sh      vte.csh                      Z97-byobu.sh
apps-bin-path.sh  cedilla-portuguese.sh  gawk.csh    vte-2.91.sh  xdg_dirs_desktop_session.sh

**Comment by joe733** [comment] 2021-02-05 10:26
Same here, no icon for Slack.
OS: elementary 5.1.7

```bash
jovial@xpsl502x:~$ echo $XDG_DATA_DIRS
/usr/share/gnome:/usr/share/pantheon:/home/jovial/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

jovial@xpsl502x:~$ ls /var/lib/flatpak/exports/share/applications
ls: cannot access '/var/lib/flatpak/exports/share/applications': No such file or directory

jovial@xpsl502x:~$ ls /etc/profile.d/
01-locale-fix.sh       flatpak.sh              pantheon-filechooser-module.sh  vte-2.91.sh
bash_completion.sh     gtk-csd.sh              qt-qpa-platformtheme.sh         xdg_dirs_desktop_session.sh
cedilla-portuguese.sh  input-method-config.sh  qt-style-override.sh
```

**Comment by zilexa** [comment] 2021-07-14 15:58
Is there a way to solve this without being required to reboot?

**Comment by mwleeds** [comment] 2021-07-14 19:31
You need to either reboot or logout and back in after installing Flatpak; see https://github.com/flatpak/flatpak.github.io/pull/340

**Comment by eloyesp** [comment] 2024-10-22 14:29
An possible solution would be to run `update-desktop-database` after the install to force the load of the desktop entries.
