### ISSUE TITLE
Provide a proper message when the package is not available for the architecture

### ISSUE THREAD

**Issue by AstroFlann** [flatpak/flatpak#5474] opened 2023-07-10 23:44 UTC
### **ChromeOS**
So basically I tried installing bottle and alot of other things, (examples: minecraft, vinegar, grapejuice, OBS, audacity, and alot of other things that have .com or are from offical companys) 
Heres the Error
```
blazingwolfie3001@penguin:~$ flatpak install flathub com.usebottles.bottles
Looking for matches…
error: Nothing matches com.usebottles.bottles in remote flathub
```
And yes, other apps work perfectly fine.

I need help please ( i also posted this on [flatpak discourse](https://discourse.flathub.org/t/i-tried-to-install-bottle-and-it-gave-me-an-error-message/4617))

**Comment by hfiguiere** [comment] 2023-07-11 19:22
Likely because you don't run `x86_64` aka Intel 64 bits, and instead run some sort of ARM.

Bottles don't make sense on ARM anyway.

This is not a flatpak issue.

**Comment by JakobDev** [comment] 2023-07-13 08:03
Maybe Flatpak should print a Message, that this App is not available for the used Architecture instead that the App is not found.

**Comment by smcv** [comment] 2023-07-14 09:12
Traditional package managers have the same behaviour: for example if you try to `apt install zsnes` (an x86-only package) on an ARM Debian/Ubuntu device, the error message you will get is "Unable to locate package zsnes" rather than "Not available on this architecture".

> Maybe Flatpak should print a Message, that this App is not available for the used Architecture instead that the App is not found.

That would require one of two things:

* the metadata that Flatpak downloads from Flathub being able to provide a list of apps (technically "refs") that exist in the same repository for other architectures but are not installable on this one, which it currently cannot;
* Flatpak downloading the metadata for *all* architectures, not just the current one, which would be a waste of bandwidth; in fact this was done in the past, but Flatpak stopped doing that because the metadata downloaded from Flathub was uncomfortably close to a size limit that would have made it no longer work

**Comment by JakobDev** [comment] 2023-07-14 10:36
> Traditional package managers have the same behaviour: for example if you try to `apt install zsnes` (an x86-only package) on an ARM Debian/Ubuntu device, the error message you will get is "Unable to locate package zsnes" rather than "Not available on this architecture".

That's true, but that doesn't mean Flatpak can do it better. Traditional package systems also don't have a fancy Website (I know that things like https://packages.ubuntu.com exists, but this is more technical and not for end users), so they will most likely use Gnome Software/Discover or some other program to search Apps, which only shows available Apps,. With Flathub we have a Website that is made for end users. Flathub shows the Architecture, but this can be overseen by non experienced Users.

> That would require one of two things:

A would prefer to first one. We could add a new Metadata field e.g. `NotExistingMessage` which contains text. If Flatpak doesn't find a App, it will look for this field. When it is found, it will simply print the Message. Flathub could populate this filed with a "This App is not available for your architecture" Message, but it could also be used if the the App is not available for another reason.

**Comment by randomairborne** [comment] 2024-03-21 01:40
I agree- because of the way flatpak presents itself, compared to distro package managers, I think that flatpak should report that "a package was found, but it was incompatible", or something, anything other then "that doesn't exist". What's the size limit that would make it no longer work?

**Comment by razzeee** [comment] 2024-07-16 23:53
This should be linked to https://github.com/flatpak/flatpak/issues/3996

**Comment by chrisawi** [comment] 2024-07-17 00:45
Duplicate of #3996

**Closed by chrisawi** 2024-07-17 00:45 UTC
Labels: cli
