### ISSUE TITLE
when installing an app or runtime, the progress indicator behaves weirdly with fish

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak#257] opened 2016-08-19 08:20 UTC
I'm using fish (instead of, say, bash) and when I'm installing something, I guess flatpak tries to render a fancy spinner type of progress indicator.

That, however, behaves funnily in my shell. It seems to be producing many newlines, because I see my terminal emulator scroll heavily.  That's unfortunate, because I can't tell whether it's working, waiting for the network, or doing something else entirely different.

To reproduce, I guess you "only" need to start fish and do a, say, 
```
flatpak --user remote-add --gpg-import=gnome-sdk.gpg gnome https://sdk.gnome.org/repo/
flatpak install --user --runtime gnome org.gnome.Sdk 3.20
```

Now this might not be flatpak's fault and I'll happily file a bug against fish. But it'd be nice if it could be detected somehow if the progress output makes sense.

**Comment by dbnicholson** [comment] 2016-08-26 17:17
I might be wrong, but I believe this is a libglnx issue fixed by https://git.gnome.org/browse/libglnx/commit/?id=c072ef1ebab052bdecb0d9a52c14813728f83859, which actually manifests in ostree. I've seen similar on bash.

**Comment by dbnicholson** [comment] 2016-08-26 17:18
I think this is a duplicate of #251.

**Comment by alexlarsson** [comment] 2016-08-29 10:14
closing as dup

**Closed by alexlarsson** 2016-08-29 10:14 UTC
