### ISSUE TITLE
flatpak uninstall --unused offers to remove used bits

### ISSUE THREAD

**Issue by afranke** [flatpak/flatpak#2373] opened 2018-12-02 13:33 UTC
Fedora 29, flatpak-1.0.6-1.fc29.x86_64, ostree-2018.9-1.fc29.x86_64.

```
$ flatpak list
Ref                                                    Options     
com.visualstudio.code.oss/x86_64/stable                user,current
org.audacityteam.Audacity/x86_64/stable                user,current
org.blender.Blender/x86_64/stable                      user,current
org.darktable.Darktable/x86_64/stable                  user,current
org.gimp.GIMP/x86_64/stable                            user,current
org.gnome.Builder/x86_64/master                        user,current
org.gnome.Calendar/x86_64/stable                       user,current
org.gnome.Fractal/x86_64/stable                        user,current
org.gnome.Maps/x86_64/stable                           user,current
org.gnome.Recipes/x86_64/stable                        user,current
org.gnome.Weather/x86_64/stable                        user,current
org.inkscape.Inkscape/x86_64/stable                    user,current
org.perezdecastro.Revolt/x86_64/master                 user,current
org.stellarium.Stellarium/x86_64/stable                user,current
org.audacityteam.Audacity.Codecs/x86_64/stable         user,runtime
org.freedesktop.Platform.GL.default/x86_64/1.6         user,runtime
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0  user,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6        user,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08      user,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6             user,runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08     user,runtime
org.freedesktop.Platform/x86_64/1.6                    user,runtime
org.freedesktop.Platform/x86_64/18.08                  user,runtime
org.freedesktop.Sdk.Extension.rust-stable/x86_64/1.6   user,runtime
org.freedesktop.Sdk.Extension.rust-stable/x86_64/18.08 user,runtime
org.freedesktop.Sdk/x86_64/1.6                         user,runtime
org.gnome.Platform/x86_64/3.24                         user,runtime
org.gnome.Platform/x86_64/3.26                         user,runtime
org.gnome.Platform/x86_64/3.28                         user,runtime
org.gnome.Platform/x86_64/3.30                         user,runtime
org.gnome.Platform/x86_64/master                       user,runtime
org.gnome.Sdk.Docs/x86_64/3.26                         user,runtime
org.gnome.Sdk.Docs/x86_64/3.28                         user,runtime
org.gnome.Sdk.Docs/x86_64/master                       user,runtime
org.gnome.Sdk/x86_64/3.26                              user,runtime
org.gnome.Sdk/x86_64/3.28                              user,runtime
org.gnome.Sdk/x86_64/master                            user,runtime
org.kde.KStyle.Adwaita/x86_64/5.11                     user,runtime
org.kde.Platform/x86_64/5.11                           user,runtime

$ flatpak uninstall --unused
Uninstalling from user:
org.audacityteam.Audacity.Codecs/x86_64/stable
org.audacityteam.Audacity.Locale/x86_64/stable
org.darktable.Darktable.Locale/x86_64/stable
org.freedesktop.Platform.GL.default/x86_64/1.6
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0
org.freedesktop.Platform.Locale/x86_64/1.6
org.freedesktop.Sdk.Extension.rust-stable/x86_64/1.6
org.freedesktop.Sdk.Extension.rust-stable/x86_64/18.08
org.freedesktop.Sdk.Locale/x86_64/1.6
org.gimp.GIMP.Locale/x86_64/stable
org.gnome.Calendar.Locale/x86_64/stable
org.gnome.Fractal.Locale/x86_64/stable
org.gnome.Maps.Locale/x86_64/stable
org.gnome.Platform.Locale/x86_64/3.30
org.gnome.Platform/x86_64/3.24
org.gnome.Platform.Locale/x86_64/3.24
org.gnome.Platform/x86_64/master
org.gnome.Platform.Locale/x86_64/master
org.gnome.Recipes.Locale/x86_64/stable
org.gnome.Sdk.Docs/x86_64/3.26
org.gnome.Sdk.Locale/x86_64/3.26
org.inkscape.Inkscape.Locale/x86_64/stable
org.kde.KStyle.Adwaita/x86_64/5.11
org.kde.Platform.Locale/x86_64/5.11
Is this ok [y/n]: n
```
Why does it suggest removing the `.Locale` when the applications are installed? What about `org.audacityteam.Audacity.Codecs` when I still have Audacity installed?

**Comment by mwleeds** [comment] 2018-12-03 20:18
I did a bit of digging into this for the case where `org.gnome.gedit` is installed but `flatpak uninstall --unused` suggests to uninstall `org.gnome.gedit.Locale`. It turned out that [this call](https://github.com/flatpak/flatpak/blob/754d68c74a24fd4e47031bf74f929fdbb1db4c88/common/flatpak-dir.c#L12531) to `ostree_repo_resolve_rev` failed, and it failed because `/var/lib/flatpak/repo/refs/remotes/flathub/runtime/org.gnome.gedit.Locale/x86_64/` exists but `/var/lib/flatpak/repo/refs/remotes/flathub/runtime/org.gnome.gedit.Locale/x86_64/stable` doesn't. Then when I re-installed Gedit the locale ref was installed correctly.

So the question is, what happened to the locale ref? What deleted it?

**Comment by matthiasclasen** [comment] 2018-12-03 21:12
Probably too late now, but do you happen to know if the metadata changed during the reinstall ?

Would be useful to compare the [Extension ... .Locale] sections of apps where it does and doesn't try to remove.

**Comment by mwleeds** [comment] 2018-12-03 21:46
I don't think so. I think it was
```
[Extension org.gnome.gedit.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true
```
before the reinstall.

**Comment by mwleeds** [comment] 2018-12-03 21:48
By the way after running `sudo flatpak repair` the problem is no longer reproducible:
```
$ flatpak uninstall --unused
Uninstalling from system:
org.kde.Platform/x86_64/5.11
org.kde.Platform.Locale/x86_64/5.11
Is this ok [Y/n]: 
```

**Comment by Mikaela** [comment] 2019-09-13 20:30
Hi, I am seeing a behaviour where `flatpak update` installs `runtime/org.freedesktop.Platform.GL.default/x86_64/19.08` and `flatpak uninstall --unused` removes it so `flatpak update` will install it again. Is this the same issue?

**Comment by mwleeds** [comment] 2019-09-13 20:33
> Hi, I am seeing a behaviour where `flatpak update` installs `runtime/org.freedesktop.Platform.GL.default/x86_64/19.08` and `flatpak uninstall --unused` removes it so `flatpak update` will install it again. Is this the same issue?

That issue was fixed in [this commit](https://github.com/flatpak/flatpak/commit/e4b1d16b7d101e0e2b038fc04ae29159097f7bae) which hasn't been released yet.

**Comment by echosa** [comment] 2019-10-01 14:34
I'm seeing a similar issue. Package `us.zoom.Zoom` requires `org.freedesktop.Platform.GL.default` to work. However, if I `flatpak uninstall --unused`, then `org.freedesktop.Platform.GL.default` is removed and Zoom no longer works until I reinstall it.

**Comment by mwleeds** [comment] 2019-10-03 02:55
@echosa which version of Flatpak are you using?

**Comment by echosa** [comment] 2019-10-04 13:45
@mwleeds 1.4.2
```
$ flatpak --version
Flatpak 1.4.2
```

**Comment by echosa** [comment] 2019-10-18 16:07
@mwleeds Any thoughts on this, perchance?

**Comment by mwleeds** [comment] 2019-10-19 02:57
@echosa you need Flatpak 1.4.3 to have the fix for that issue

**Comment by mwleeds** [comment] 2019-10-19 03:03
Using Flatpak 1.5.0, I can't reproduce the problem this issue was originally about (which seems to be separate from the issue with `org.freedesktop.Platform.GL.default`). With Audacity installed, its Locale extension is not suggested for uninstallation by `uninstall --unused`.

**Closed by mwleeds** 2019-10-19 03:03 UTC
Labels: bug
