### ISSUE TITLE
Flatpak doesn't understand what my default applications are 

### ISSUE THREAD

**Issue by DarrienG** [flatpak/flatpak#4363] opened 2021-08-08 15:21 UTC
## Linux distribution and version

```
~ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

## Flatpak version

```
~ flatpak --version
Flatpak 1.8.5
```

## Description of the problem

Flatpak applications don't understand default applications the user sets. For instance, if I set a default application in gnome settings, say image viewer:

![Screenshot from 2021-08-08 11-16-10](https://user-images.githubusercontent.com/5041953/128636960-ef4897bf-d629-44ea-9794-bf14cb4d8a02.png)

If I'm using say Firefox flatpak and download an image. Trying to open it from the download dialog shows this instead of opening it in my default image viewier:

![Screenshot from 2021-08-08 11-16-51](https://user-images.githubusercontent.com/5041953/128636954-c50f69bd-7138-4dfe-b4aa-715b106e1e61.png)

FWIW the behavior here isn't great either, the dialog always shows up behind the application you're running.

## Steps to reproduce

* Install [flatpak firefox](https://flathub.org/apps/details/org.mozilla.firefox)
* search up an image of something
* download the image
* click the download dialog and try to open the image
![Screenshot from 2021-08-08 11-19-27](https://user-images.githubusercontent.com/5041953/128637019-2d1ace92-79b9-42fa-aecf-f4f3dd1fc734.png)
* You'll get the popup rather than opening the app in the default application

![Screenshot from 2021-08-08 11-16-51](https://user-images.githubusercontent.com/5041953/128637033-25b1fd32-2036-47ca-b430-e5b428b48415.png)

AFAIK there is no way to set default applications across the flatpak runtime, so there is no workaround for this.

This is reproducible in other flatpak applications (e.g. signal desktop).

**Comment by refi64** [comment] 2021-08-24 16:06
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/472. (That being said, note that the portal should remember your defaults after...3 uses I think?)

**Closed by refi64** 2021-08-24 16:06 UTC

**Comment by DarrienG** [comment] 2021-08-24 16:30
Hmm perhaps I'm using an outdated version on CentOS. It doesn't remember my choices after 3 usages 🤔

That would be a nice addition though if it isn't already in a later version!

**Comment by zoliky** [comment] 2023-05-21 21:41
@DarrienG I'm experiencing the same issue where the Flatpak version of Chrome is not appearing in GNOME's default applications dropdown list. Have you managed to find a solution to this problem?

**Comment by DarrienG** [comment] 2023-05-21 21:51
> @DarrienG I'm experiencing the same issue where the Flatpak version of Chrome is not appearing in GNOME's default applications dropdown list. Have you managed to find a solution to this problem?

@zoliky I gave up and moved to macOS. Apologies. 

I hope you are able to find a solution to the issue!
