### ISSUE TITLE
git master fails tests on ppc64el

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#3503] opened 2020-03-26 17:28 UTC
## Linux distribution and version

Debian unstable

## Flatpak version

Approximately b05b9f71

## Description of the problem

`testlibrary`, `tests/test-info@user.wrap`, `tests/test-completion.sh` fail with:

```
Bail out! flatpak:ERROR:common/flatpak-variant-impl-private.h:2223:var_sparse_cache_entry_get_key: assertion failed: (end < v.size)
```

## Steps to reproduce

Build the Debian experimental package.

**Comment by smcv** [comment] 2020-03-26 18:31
The problem appears to be (again) the optimized version of `ref_get_offset_size()`. If I force the `ppc64el` machine to use the simple/obvious code path, it passes tests.

I'm not sure what is different about ppc64el here, but this makes me wonder whether the optimization is worth it. Does it have a noticeable result in benchmarks?

One unusual thing about the whole powerpc family, including ppc64el, is that char is unsigned. I don't know whether that's relevant or not - there doesn't seem to be a char involved in this expression.

I tried sprinkling `(guint32)` casts and `U` suffixes through the expression, but wasn't able to find anything that worked.

Maybe the behaviour of the `>>` operator (arithmetic vs. logical shift) could be a factor? I think C leaves that implementation-defined.

**Comment by nanonyme** [comment] 2020-11-23 20:21
Note this is failing for us not just in tests but with actual flatpak usage: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/867697942 (1.8.2)

```
flatpak remote-ls --all fdo-sdk-test-repo --columns ref,download-size,installed-size | awk "/ppc64le/ && /21.08beta/"
**
flatpak:ERROR:./common/flatpak-variant-impl-private.h:2223:var_sparse_cache_entry_get_key: assertion failed: (end < v.size)
flatpak install -y --arch=ppc64le --user fdo-sdk-test-repo org.freedesktop.{Platform,Sdk}//21.08beta
Looking for matches?
**
flatpak:ERROR:./common/flatpak-variant-impl-private.h:2223:var_sparse_cache_entry_get_key: assertion failed: (end < v.size)
```

**Comment by smcv** [comment] 2020-11-24 11:00
Here's the workaround I've applied in Debian:

```diff
From: Simon McVittie <smcv@debian.org>
Date: Mon, 30 Mar 2020 09:34:45 +0100
Subject: variant-schema-compiler: Disable optimized calculation of offset
 size

This doesn't seem to give the expected answers on ppc64el, which makes
me worry that it might be relying on undefined or implementation-defined
behaviour. Disable it everywhere until we work out what is going on.

Signed-off-by: Simon McVittie <smcv@debian.org>
---
 variant-schema-compiler/variant-schema-compiler | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/variant-schema-compiler/variant-schema-compiler b/variant-schema-compiler/variant-schema-compiler
index fe2fb24..cb9fd6a 100755
--- a/variant-schema-compiler/variant-schema-compiler
+++ b/variant-schema-compiler/variant-schema-compiler
@@ -118,7 +118,7 @@ typedef struct {{
 G_GNUC_CONST static inline guint
 {prefix_}ref_get_offset_size (gsize size)
 {{
-#if defined(__GNUC__) && (__GNUC__ >= 4) && defined(__OPTIMIZE__) && defined(__LP64__)
+#if 0
   /* Instead of using a lookup table we use nibbles in a lookup word */
   guint32 v = (guint32)0x88884421;
   return (v >> (((__builtin_clzl(size) ^ 63) / 8) * 4)) & 0xf;
```

**Comment by nanonyme** [comment] 2020-11-27 17:42
@smcv is this actually https://gitlab.gnome.org/alexl/variant-schema-compiler/-/issues/2? If so, updating submodule might help.

**Comment by nanonyme** [comment] 2020-11-27 18:09
Actually tracing back on things, seems this is probably already fixed in master and released through 1.8.3.

**Comment by nanonyme** [comment] 2020-11-27 19:31
Looks like I'm only half right. https://github.com/flatpak/flatpak/commit/fb0691e895f0fc1e17afda5c01c48d5fdbc5a95e doesn't exist in flatpak-1.8.x

**Comment by nanonyme** [comment] 2020-11-27 20:19
Created  https://github.com/flatpak/flatpak/issues/4000 just in case since the other finding was about a maintenance branch.

**Comment by alexlarsson** [comment] 2020-11-30 08:15
@nanonyme @smcv I added a selftest to the schema compiler, which tries to validate ref_get_offset_size():
 https://gitlab.gnome.org/alexl/variant-schema-compiler/-/commit/04abfc9e53bb17a12fba5ea2307db6366bc8208e

I ran this on ppc64le in qemu, but it passed. Can you try it on some real hardware?

**Comment by alexlarsson** [comment] 2020-11-30 08:26
Maybe there is some specific optimization flag that causes it to miscompile? The selftest is just `-O2`

**Comment by alexlarsson** [comment] 2020-11-30 11:24
I managed to reproduce this in qemu in a full build of flapak.
The root cause has been fixed by:

https://gitlab.gnome.org/alexl/variant-schema-compiler/-/commit/46b017df9401c5b97a42edb30074186278eabeac

Which was imported into flatpak at fb0691e895f0fc1e17afda5c01c48d5fdbc5a95e, but isn't currently on the flatpak-1.8.x branch.

**Closed** 2021-01-15 02:19 UTC
