### ISSUE TITLE
[Feature request]: `home` permission: exclude all dotfiles and directories

### ISSUE THREAD

**Issue by boredsquirrel** [flatpak/flatpak#5773] opened 2024-04-11 21:26 UTC
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Explanation
[This closed issue](https://github.com/flatpak/flatpak/issues/3637) addresses the problem.

If an app has access to home, it can
- override its own permission or of other apps in `~/.local/share/flatpak/overrides`
- read and write `~/.bashrc` or other shell configs, and this catch the sudo password
- read `~/.ssh` and `~/.gnupg` (which are not protected at all, being only readable by this user
- read and write `~/.mozilla` if the user uses that, which stores unencrypted browser info

This is just horrible. And there should be an easy fix?

### Question
How is the block for `~/.var/app` done? Couldnt in a similar way apps simply have access to all, or at least selected, dotfiles blocked?

### Why this is important
This is important, as users may have messy home directories, and simply can not have well working legacy apps with only xdg-dir permissions. And I also doubt that we will have a portal-only app ecosystem anytime soon.

### Workaround for breaking apps
If apps really need access to stuff like that, the permissions can be added manually and transparently. This is how [Flatweep does it](https://github.com/giantpinkrobots/flatsweep/blob/main/io.github.giantpinkrobots.flatsweep.json):

```

```

**Comment by chrisawi** [comment] 2024-04-11 21:37
Duplicate of https://github.com/flatpak/flatpak/issues/4632

**Closed by chrisawi** 2024-04-11 21:37 UTC
Labels: enhancement, needs triage
