### ISSUE TITLE
as_ref_string_new, as_ref_string_unref assertions failed

### ISSUE THREAD

**Issue by eode** [flatpak/flatpak#4219] opened 2021-04-11 19:34 UTC
## Linux distribution and version
Ubuntu 20.04

## Flatpak version
1.6.5
## Description of the problem
```
$ flatpak search clementine    # also occurs with any other search I do
(flatpak search:52956): As-CRITICAL **: 14:26:35.658: as_ref_string_new: assertion 'str != NULL' failed

(flatpak search:52956): As-CRITICAL **: 14:26:35.658: as_ref_string_new: assertion 'str != NULL' failed
Name                      Description                            Application ID                     Version    Branch  Remotes
Clementine Music Player   Plays music files and Internet radio   org.clementine_player.Clementine   1.4.0rc2   stable  flathub

(flatpak search:52956): As-CRITICAL **: 14:26:35.908: as_ref_string_unref: assertion 'rstr != NULL' failed

(flatpak search:52956): As-CRITICAL **: 14:26:35.908: as_ref_string_unref: assertion 'rstr != NULL' failed
```

No remotes other than the default (flathub) are installed.  I don't really expect it should, but `flatpak repair` didn't fix anything.

## Steps to reproduce
```
flatpak search <anything>
```

**Comment by smtnsk** [comment] 2021-04-12 14:42
Occurs also on Alpine Linux with Flatpak 1.10.2.

**Comment by Mine-Ranger** [comment] 2021-04-12 17:07
> ## Linux distribution and version
> Ubuntu 20.04
> 
> ## Flatpak version
> 1.6.5
> 
> ## Description of the problem
> ```
> $ flatpak search clementine    # also occurs with any other search I do
> (flatpak search:52956): As-CRITICAL **: 14:26:35.658: as_ref_string_new: assertion 'str != NULL' failed
> 
> (flatpak search:52956): As-CRITICAL **: 14:26:35.658: as_ref_string_new: assertion 'str != NULL' failed
> Name                      Description                            Application ID                     Version    Branch  Remotes
> Clementine Music Player   Plays music files and Internet radio   org.clementine_player.Clementine   1.4.0rc2   stable  flathub
> 
> (flatpak search:52956): As-CRITICAL **: 14:26:35.908: as_ref_string_unref: assertion 'rstr != NULL' failed
> 
> (flatpak search:52956): As-CRITICAL **: 14:26:35.908: as_ref_string_unref: assertion 'rstr != NULL' failed
> ```
> 
> No remotes other than the default (flathub) are installed. I don't really expect it should, but `flatpak repair` didn't fix anything.
> 
> ## Steps to reproduce
> ```
> flatpak search <anything>
> ```

It Happened to me also on Pop!_OS 20.04 LTS everytime I search the same error happens all functions are working fine install ,uninstall everything and I have also tried flatpak repair but don't seem to fix the isssue.

**Comment by edmundlaugasson** [comment] 2021-04-12 21:43
Occurs also in Linux Mint 20.1....

**Comment by stuzenz** [comment] 2021-04-14 07:20
Same issue here on this system

```
➜ flatpak search enso   

(flatpak search:142050): As-CRITICAL **: 19:16:46.090: as_ref_string_new: assertion 'str != NULL' failed

(flatpak search:142050): As-CRITICAL **: 19:16:46.090: as_ref_string_new: assertion 'str != NULL' failed

(flatpak search:142050): As-CRITICAL **: 19:16:46.528: as_ref_string_new: assertion 'str != NULL' failed

(flatpak search:142050): As-CRITICAL **: 19:16:46.528: as_ref_string_new: assertion 'str != NULL' failed
Name         Description           Application ID                   Version       Branch       Remotes
Agenda       Get things done       com.github.dahenson.agenda       1.0.12        stable       flathub

(flatpak search:142050): As-CRITICAL **: 19:16:46.826: as_ref_string_unref: assertion 'rstr != NULL' failed

(flatpak search:142050): As-CRITICAL **: 19:16:46.826: as_ref_string_unref: assertion 'rstr != NULL' failed

(flatpak search:142050): As-CRITICAL **: 19:16:46.894: as_ref_string_unref: assertion 'rstr != NULL' failed

(flatpak search:142050): As-CRITICAL **: 19:16:46.894: as_ref_string_unref: assertion 'rstr != NULL' failed
(base) 
courses on  master is 📦 v0.4.0 via ⬢ v14.16.1 via 🅒 base 
➜ uname -a
Linux arch-t460p 5.11.13-arch1-1 #1 SMP PREEMPT Sat, 10 Apr 2021 20:47:14 +0000 x86_64 GNU/Linux
(base) 

```

**Comment by KucharczykL** [comment] 2021-04-14 11:20
flatpak 1.10.2
openSUSE Tumbleweed

```
$ flatpak remote-ls --updates
(flatpak remote-ls:17770): As-CRITICAL **: 13:15:16.760: as_ref_string_new: assertion 'str != NULL' failed
(flatpak remote-ls:17770): As-CRITICAL **: 13:15:16.760: as_ref_string_new: assertion 'str != NULL' failed
(flatpak remote-ls:17770): As-CRITICAL **: 13:15:16.847: as_ref_string_unref: assertion 'rstr != NULL' failed
(flatpak remote-ls:17770): As-CRITICAL **: 13:15:16.848: as_ref_string_unref: assertion 'rstr != NULL' failed
```

**Comment by rccavalcante** [comment] 2021-04-14 11:42
Flatpak 1.10.2
Manjaro Linux x86_64
5.11.10-1-MANJARO

```
flatpak search simplenote
(flatpak search:7992): As-CRITICAL **: 08:41:33.278: as_ref_string_new: assertion 'str != NULL' failed
(flatpak search:7992): As-CRITICAL **: 08:41:33.278: as_ref_string_new: assertion 'str != NULL' failed
Name               Description                            Application ID                    Version        Branch        Remotes
Simplenote         The simplest way to keep notes         com.simplenote.Simplenote         2.9.0          stable        flathub
(flatpak search:7992): As-CRITICAL **: 08:41:33.402: as_ref_string_unref: assertion 'rstr != NULL' failed
(flatpak search:7992): As-CRITICAL **: 08:41:33.402: as_ref_string_unref: assertion 'rstr != NULL' failed
```

**Comment by To-Sang** [comment] 2021-04-14 17:58
### Ubuntu version
Ubuntu 20.04.2 LTS
### Flatpak version
1.6.5
### Description of the problem

```
flatpak search chrome

(flatpak search:8355): As-CRITICAL **: 00:53:21.611: as_ref_string_new: assertion 'str != NULL' failed

(flatpak search:8355): As-CRITICAL **: 00:53:21.611: as_ref_string_new: assertion 'str != NULL' failed
Name                             Description                                                                                                               Application ID                         Version       Branch Remotes
Chromium Web Browser             The web browser from Chromium project                                                                                     org.chromium.Chromium                  89.0.4389.128 stable flathub
ungoogled-chromium               A lightweight approach to removing Google web service dependency                                                          com.github.Eloston.UngoogledChromium   89.0.4389.114 stable flathub
CrosAdapta                       Chrome OS GTK theme                                                                                                       org.gtk.Gtk3theme.CrosAdapta                         3.22   flathub
Firestorm Viewer                 Client for accessing 3D virtual worlds                                                                                    org.firestormviewer.FirestormViewer    6.3.9.58205   stable flathub
Joplin                           A free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks. net.cozic.joplin_desktop               1.7.11        stable flathub
Google Play Music Desktop Player Run Google Play Music as a standalone desktop app                                                                         com.googleplaymusicdesktopplayer.GPMDP 4.7.1         stable flathub
Postman                          Postman is a complete API development environment.                                                                        com.getpostman.Postman                 8.2.2         stable flathub

(flatpak search:8355): As-CRITICAL **: 00:53:21.860: as_ref_string_unref: assertion 'rstr != NULL' failed

(flatpak search:8355): As-CRITICAL **: 00:53:21.860: as_ref_string_unref: assertion 'rstr != NULL' failed

```
How can i fix it now :(

**Comment by smcv** [comment] 2021-04-14 19:24
Thanks, but we don't need any more reports of this.

This isn't actually a bug in Flatpak, and Flatpak changes are not going to fix it. It seems to be caused by `org.cubocore.CoreImage` on Flathub, which has

```
<suggests>
  <id/>
</suggests>
```

in its metadata. That's not valid (flathub/org.cubocore.CoreImage#1 should fix this).

appstream-glib doesn't detect that as invalid, and instead shows critical warnings during parsing (hughsie/appstream-glib#396).

**Comment by chrisfxwolf** [comment] 2021-04-16 14:53
As well in openSUSE Leap 15.2 with flatpak version 1.10.2

`$ flatpak remote-ls --updates

(flatpak remote-ls:7271): As-CRITICAL **: 15:50:55.776: as_ref_string_new: assertion 'str != NULL' failed

(flatpak remote-ls:7271): As-CRITICAL **: 15:50:55.776: as_ref_string_new: assertion 'str != NULL' failed

(flatpak remote-ls:7271): As-CRITICAL **: 15:50:56.002: as_ref_string_unref: assertion 'rstr != NULL' failed

(flatpak remote-ls:7271): As-CRITICAL **: 15:50:56.002: as_ref_string_unref: assertion 'rstr != NULL' failed`

**Comment by smcv** [comment] 2021-04-16 14:59
Please don't report this issue. We know about it, and I have sent a fix to the project that is causing it. Leaving more comments here is not going to get it solved sooner.

**Comment by dominix** [comment] 2021-04-18 21:48
it is clearly looks like a bug in flatpak as it clearly show that it lacks validation entry point in the repository, or otherwise flatpak should be able to avoid to annoy everybody with an incorrectly formatted entry point, just ignoring it.

**Comment by smcv** [comment] 2021-04-19 08:10
Flatpak validates and parses the AppStream metadata from the repository by passing it to appstream-glib, which had a bug that makes it emit these warnings (hughsie/appstream-glib#396, now fixed upstream, but presumably not fixed in your distribution yet). It would not make sense for Flatpak to implement its own validation and parsing of AppStream - that would just mean we had new, different bugs.

**Comment by hfiguiere** [comment] 2024-02-10 19:37
considering fixed.

**Closed by hfiguiere** 2024-02-10 19:37 UTC
Labels: 3rd party integration, flathub
