### ISSUE TITLE
Wrong fatal error when building

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#389] opened 2016-11-02 15:36 UTC
I am describing the projects to build in the json file from using git URLs.

I am getting several errors like this one, on a per repository basis:
`fatal: Path '.gitmodules' does not exist in '080efedd21ea184643ca794b2a63717d3c110d23'`

`.gitmodules` shouldn't be necessary and in fact the build process continues, nevertheless having "fatal" messages in the output makes me cringe.

Our json file for reference:
https://quickgit.kde.org/?p=flatpak-kde-runtime.git&a=blob&h=84693e8a76be0abf7c57a0d641d040da972f95a3&f=org.kde.Sdk.json&o=plain

**Comment by mwleeds** [comment] 2016-11-08 01:42
This is a duplicate of #366 and was fixed by 8b50648ec0d710ee258193112a474b86c39b3948

**Comment by aleixpol** [comment] 2016-11-08 13:31
If it's fixed, feel free to close the issue :)

**Closed** 2016-11-11 09:25 UTC
