### ISSUE TITLE
Frequent failures trying Instal Flatpak apps ... progress is hard to read !!!

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1345] opened 2018-01-26 08:01 UTC
hmmmmm ... i am on `Flatpak 0.9.7` ...

trying to install a flatpak app ... and failing each time ... I can't tell if the downloads are happening in continued manner or its starting from the beginning after each attempt to install it ... its a really annoying thing ...

Could somebody check if this is bug ?

```
flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[###-                ] Downloading: 92.4 MB/901.2 MB (258.0 kB/s)              
error: While pulling app/com.google.AndroidStudio/x86_64/stable from remote flathub: Error resolving “dl.flathub.org”: Temporary failure in name resolution

flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[####################] Downloading: 810.5 MB/810.5 MB (292.2 kB/s) 
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256


flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 33.7 MB (81.4 kB/s) 
error: While downloading https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip: Socket I/O timed out


flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 179.0 MB (257.5 kB/s)
error: While downloading https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip: Socket I/O timed out


flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 773.7 MB (295.1 kB/s)
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256


flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 394.0 MB (285.1 kB/s)
error: While downloading https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip: Socket I/O timed out


flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 120.4 MB (326.4 kB/s)
error: While downloading https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip: Socket I/O timed out


flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 148.1 MB (375.9 kB/s)T

```

**Comment by aiamuzz** [comment] 2018-01-26 08:34
another attempt failed ... for this app ... turns out its downloading repeatedly ... wasting valuable bandwith ...

```
flatpak --installation=myFlatpaks install com.google.AndroidStudio.flatpakref
Installing: com.google.AndroidStudio/x86_64/stable
Installing: com.google.AndroidStudio/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 773.7 MB (380.4 kB/s)T
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```

**Comment by aiamuzz** [comment] 2018-01-26 08:35
another app with the same error ... i have been trying to install these 2 apps from the last 2 days ... and they are returning the same error ...

```
flatpak --installation=myFlatpaks install com.visualstudio.code.flatpakref
Installing: com.visualstudio.code/x86_64/stable
Installing: com.visualstudio.code/x86_64/stable from flathub
[                    ] Downloading metadata: 0/(estimating) 66.9 MB (256.3 kB/s) 
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

```

**Comment by mwleeds** [comment] 2018-01-27 05:30
@aiamuzz not sure what OS you're on but is there a way you could update to a more recent version of flatpak?

**Comment by mdeguzis** [comment] 2018-03-30 01:33
I get this as well "Error resolving “dl.flathub.org” when using the official Arch Linux package. Followed exactly from http://docs.flatpak.org/en/latest/using-flatpak.html#the-flatpak-command.

**Comment by cjdm** [comment] 2018-05-31 22:22
I've been getting this error for a while, almost a month... I cannot install anything from Flathub. 
![flatpak](https://user-images.githubusercontent.com/29413765/40811397-0dfa2822-64ff-11e8-81e1-050a99aef273.jpg)
![gnome-software](https://user-images.githubusercontent.com/29413765/40811398-0e171428-64ff-11e8-86e9-e7643b8907b3.jpg)

**Comment by cjdm** [comment] 2018-06-13 00:06
I'm on Arch, I'm using Flatpak 0.11.8.2 and I get the same message every time I try to install a app: "Error resolving “dl.flathub.org”: Temporary failure in name resolution." It's very annoying... It's been over a month, maybe more, since the first time I started to get this warning.

**Comment by mwleeds** [comment] 2018-09-08 17:02
I'll go ahead and close this unless someone can reproduce on a recent version of flatpak.

**Closed by mwleeds** 2018-09-08 17:02 UTC

**Comment by VaZark** [comment] 2018-09-26 19:33
__Distro:__ Manjaro Gnome
__Flatpak version :__ 1.0.1

The was reproduced while trying download _`GravitDesigner`_

```
flatpak install flathub io.designer.GravitDesigner
Installing in system:
io.designer.GravitDesigner/x86_64/stable        flathub 4f32043850d1
  permissions: ipc, network, x11, dri
  file access: home
  tags: proprietary
io.designer.GravitDesigner.Locale/x86_64/stable flathub e8905641e9d4
Is this ok [y/n]: y
Installing: io.designer.GravitDesigner/x86_64/stable from flathub
[####################] Downloading: 69.6 MB/69.6 MB (9.9 MB/s) 
error: Failed to install io.designer.GravitDesigner/x86_64/stable: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```
