### ISSUE TITLE
error: Unable to load summary from remote fedora: Failed to update OCI summary: Server required TLS certificate

### ISSUE THREAD

**Issue by vatula** [flatpak/flatpak#2976] opened 2019-06-23 22:23 UTC
## Linux distribution and version
Fedora rawhide

- OS: Fedora 31 (Workstation Edition) x86_64
- Kernel: 5.2.0-0.rc5.git3.2.fc31.x86_64
- Shell: zsh 5.7.1

## Flatpak version
Flatpak 1.4.1

## Description of the problem
Flatpak fails to update
`flatpak -vv update`

`F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/atticdweller/.local/share/flatpak
Looking for updates…
F: Fetching summary file for remote ‘flathub’
F: Transaction: update flathub:app/ca.desrt.dconf-editor/x86_64/stable[$old]
...
F: Transaction: update flathub:runtime/org.darktable.Darktable.Locale/x86_64/stable[$old]
F: Calling system helper: GenerateOciSummary
F: Failed to download optional summary
F: Transaction: update fedora:runtime/org.fedoraproject.Platform/x86_64/f29[$old]
F: Fetching summary file for remote ‘steam-origin’
F: Transaction: update steam-origin:runtime/org.freedesktop.Platform.Compat.i386/x86_64/18.08[$old]
...
F: Transaction: update flathub:runtime/org.kde.PlatformTheme.QGnomePlatform.Sources/x86_64/5.12[$old]
F: Transaction: update flathub:runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/5.12[$old]
F: Updating remote metadata for steam-origin
F: Updating remote metadata for flathub
F: Updating remote metadata for fedora
F: marking op update:runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/5.12 resolved to 110323e87f95f12032cbf0dca4fd84a40a5ba59299c7db4f59adada3893446a2
F: marking op update:runtime/org.kde.PlatformTheme.QGnomePlatform.Sources/x86_64/5.12 resolved to ff6a09543e8b98e8cb778122e91a7e811228f7a7b92fc24b3494d043f96df62a
...
F: marking op update:runtime/org.freedesktop.Platform.GL.nvidia-430-14/x86_64/1.4 resolved to 22085b3c8af7e2e5490c1194335144991e17aa7486589a5fbd2eab978606649c
F: marking op update:runtime/org.freedesktop.Platform.Compat.i386/x86_64/18.08 resolved to fb16d111c6b5f4679b020734ae50696eb500b3635f581b169cae3f7449f0af1e
F: Calling system helper: GenerateOciSummary
F: Failed to download optional summary
error: Unable to load summary from remote fedora: Failed to update OCI summary: Server required TLS certificate
`

## Steps to reproduce
I started having this issue yesterday on Fedora Rawhide

**Comment by vatula** [comment] 2019-06-23 22:30
I am on LAN and don't experience any general connectivity issues

**Comment by alex285** [comment] 2019-07-02 00:48
same error here, only happens w Fedora OCI

**Comment by mwleeds** [comment] 2019-07-05 15:52
I see it too, on Silverblue rawhide.

**Comment by mwleeds** [comment] 2019-07-05 15:52
Maybe @owtaylor would know?

**Comment by mwleeds** [comment] 2019-07-05 16:12
Looks like the error "Server required TLS certificate" is from line 1393 of `tls/base/gtlsconnection-base.c` in `glib-networking.git`.

**Comment by tfmoraes** [comment] 2019-07-16 13:15
Same error. Using Silverblue Rawhide.

**Comment by owtaylor** [comment] 2019-08-05 14:30
This turned out to be a regression in glib-networking 2.61.1, fixed in 2.61.2.

I've [built](https://koji.fedoraproject.org/koji/taskinfo?taskID=36809677) that for Fedora now, hopefully will be fixed in tomorrow's Rawhide compose and Silverblue tree. Sorry this took so long to resolve.

**Comment by matthiasclasen** [comment] 2019-12-02 03:51
fixed in glib

**Closed by matthiasclasen** 2019-12-02 03:51 UTC
Labels: bug, oci
