### ISSUE TITLE
Python setlocale fails for mixed locales

### ISSUE THREAD

**Issue by dreua** [flatpak/flatpak#3514] opened 2020-03-29 13:31 UTC
## Linux distribution and version
Fedora 31
## Flatpak version
1.4.4
## Description of the problem
Python app does not start due to setlocale failing:

```
$ flatpak run com.github.jeromerobert.pdfarranger 
Traceback (most recent call last):
  File "/app/bin/pdfarranger", line 11, in <module>
    load_entry_point('pdfarranger==1.4.2', 'console_scripts', 'pdfarranger')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 49, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
### Workaround
For my locale this is fixed by running `flatpak update --subpath=de org.gnome.Platform.Locale`

### Related issues

- https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/442
- https://github.com/flathub/net.lutris.Lutris/issues/78
- https://dev.gajim.org/gajim/gajim/issues/9167

My current work

- jeromerobert/pdfarranger#37
- https://github.com/flathub/flathub/pull/1427

## Steps to reproduce
- Have a mixed locale setting (common if you want English language but your local date / time / currency formats)
- If you applied the workaround before, you need to `flatpak remove org.gnome.Platform.Locale` to reproduce
- Install and run an app that uses Python setlocale, in my case this is:
  - `flatpak install flathub com.github.jeromerobert.pdfarranger`
  - `flatpak run com.github.jeromerobert.pdfarranger`

**Comment by nanonyme** [comment] 2020-04-22 20:32
Ping @alexlarsson is this expected behaviour?

**Comment by dreua** [comment] 2020-04-26 13:20
Updated in main post: Steps to reproduce are much easier now that pdfarranger is on flathub.

**Comment by mcatanzaro** [comment] 2021-04-06 12:29
Proposal: mark this as a duplicate of #3712, which is the same issue but with more discussion.

**Comment by dreua** [comment] 2021-04-07 05:28
Proposal: Someone with knowledge and interest in the flatpak ecosystem should actually work on this stuff. I don't care which of this issues remains open, feel free to close mine if you think the other one is better. What does worry me is the lack of flatpak developers coming up with actual solutions here.

**Comment by mcatanzaro** [comment] 2021-09-08 19:55
> Proposal: mark this as a duplicate of #3712, which is the same issue but with more discussion.

I notice that basic bug management suggestions like "close this obsolete issue" or "this issue is a duplicate of this other issue" are often ignored on this issue tracker. If somebody with powers is watching, this one is still a duplicate, can be easily closed.

**Closed** 2021-09-13 00:18 UTC
