### ISSUE TITLE
Warning: org.freedesktop.Platform.openh264 not installed

### ISSUE THREAD

**Issue by jkotra** [flatpak/flatpak#3197] opened 2019-10-26 15:28 UTC
## Linux distribution and version
Arch Linux - Latest

## Flatpak version

```
Flatpak 1.5.0
```

## Description of the problem
I only have 1 app installed - Pycharm Community Edition.

```
 th4n0s@titan ~ flatpak update
Looking for updates…


        ID                                             Branch              Remote               Download
 1. [✗] org.freedesktop.Platform.openh264              19.08               flathub              593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

```
## Steps to reproduce

` flatpak update `

**Comment by mbooth101** [comment] 2019-11-20 15:50
This ticket is a duplicate of this one: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886

**Comment by totedati** [comment] 2019-11-26 06:32
From that gitlab #886 issue you should jump to the last lines and do this:
```
flatpak install org.freedesktop.Platform/x86_64/19.08
flatpak uninstall --unused
flatpak update
```
Problem solved ... At least for me:
```
hostnamectl
   Static hostname: berbecel
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 5c5f9ce2a63446e9b98b733ff081f2c9
           Boot ID: 931c620a439f4936be83872a5fe34ec9
  Operating System: Ubuntu 18.04.3 LTS
            Kernel: Linux 5.3.11-050311-generic
      Architecture: x86-64
```

**Comment by Sebastian1978** [comment] 2020-01-16 10:07
Didn't work for me. Still can't install openh264.
Flatpak 1.6.0

**Comment by jrodd96** [comment] 2020-01-24 22:01
Nor does this work for me on both Pop! OS 19.10 and my LFS 9.0 build as well. Flatpak 1.6.1

**Comment by MCOfficer** [comment] 2020-02-11 18:19
The downstream issue concluded that the problem is that  `org.freedesktop.Platform` is missing while installing. However, the proposed solution doesn't work if `flatpak uninstall --unused` removes everything installed in step 1, cause then you're right back where you started. 

This is what worked for me instead:
```
❯ flatpak install flathub org.freedesktop.Platform/x86_64/19.08
Looking for matches…


        ID                                                    Branch            Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default                   19.08             i             flathub             92,6 MB / 92,6 MB
 2. [✓] org.freedesktop.Platform.GL.nvidia-440-59             1.4               i             flathub            102,7 MB / 102,7 MB
 3. [✓] org.freedesktop.Platform.Locale                       19.08             i             flathub             23,5 MB / 318,2 MB
 4. [✗] org.freedesktop.Platform.openh264                     19.08             i             flathub            593,6 kB / 593,4 kB
 5. [✓] org.freedesktop.Platform                              19.08             i             flathub            223,4 MB / 238,1 MB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.


❯ flatpak install flathub org.freedesktop.Platform.openh264/x86_64/19.08
Looking for matches…


        ID                                           Branch           Op           Remote            Download
 1. [✓] org.freedesktop.Platform.openh264            19.08            i            flathub           593,6 kB / 593,4 kB

Installation complete.

```

**Comment by glaubersm** [comment] 2020-02-24 12:56
Same thing on Arch Linux running flatpak 1.6.2
None workaround posted here works for me.

**Comment by KaeLL** [comment] 2020-02-24 19:49
Same thing, running on Clear Linux 32380

> ```
> ❯ flatpak install flathub org.freedesktop.Platform.openh264/x86_64/19.08
> ```
got me this
```
 error: Failed to install org.freedesktop.Platform.openh264: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed
```

**Comment by MSilva61** [comment] 2020-02-25 13:00
Hello,I'm not a programmer what so ever,just wanted to put my two cents worth on this issue,in the hopes it might help some one.
I followed the instructions provided by MCOfficer,and it worked for me,how ever when I entered those commands I was given a choice between two options as you can see from the text below,
I chose at first 2,but was asked again to chose,as you can see my inputs,so I typed "user" only to be asked again,and typed 2 again and it worked,for both sets of commands. perhaps the problem lies in that flatpack,and the other parts are installed,in both system and user folders?.
I'm running Linux Mint 19,Cinnamon V 3.8.9 on a Dell Inspiron 1564 Laptop,4 Gb Mem.


*******-****:~$ flatpak install flathub org.freedesktop.Platform/x86_64/19.08
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 2
Which do you want to use (0 to abort)? [0-2]: user
Which do you want to use (0 to abort)? [0-2]: 2


        ID                                Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform.Locale   19.08  i  flathub  17.6 kB / 318.2 MB
 2. [✗] org.freedesktop.Platform.openh264 19.08  i  flathub 593.6 kB / 593.4 kB
 3. [✓] org.freedesktop.Platform          19.08  i  flathub  71.6 MB / 238.1 MB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

*******-****:~$ flatpak install flathub org.freedesktop.Platform.openh264/x86_64/19.08
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 2
Which do you want to use (0 to abort)? [0-2]: 2


        ID                                Branch Op Remote  Download
 1. [\] org.freedesktop.Platform.openh264 19.08  i  flathub 593.6 kB / 593.4 kB
        ID                                Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform.openh264 19.08  i  flathub 593.6 kB / 593.4 kB

Installation complete.
*******-****:~$

**Comment by KaeLL** [comment] 2020-02-26 15:12
Sounds like someone forgot to update the path to the correct dependency.

**Comment by MLDamazigh** [comment] 2020-03-13 12:57
Same thing with me (Ubuntu 19.10) i have tried all the proposed solutions here but without success.
any other solutions ????

**Comment by hfiguiere** [comment] 2024-02-10 18:58
Works fine here.

**Closed by hfiguiere** 2024-02-10 18:58 UTC
Labels: flathub

**Comment by Jacky2001** [comment] 2024-02-13 01:25
to solve the issue:

`flatpak install flathub org.freedesktop.Platform/x86_64/21.08`
