### ISSUE TITLE
org.freedesktop.Platform.Compat.i386 and org.freedesktop.Platform.GL32.default won't install as dependency (runtime 20.08)

### ISSUE THREAD

**Issue by fastrizwaan** [flatpak/flatpak#4164] opened 2021-03-08 08:31 UTC
## Linux distribution and version
Debian 10.8
Solus 4.2
Fedora 33

## Flatpak version
Flatpak 1.10.1

## Description of the problem
My flatpak-win32 is a wine flatpak, which needs 32 bit dependencies, while installing 32 bit dependencies are not installed
_org.freedesktop.Platform.Compat.i386 
org.freedesktop.Platform.GL32_

Strangely enough,  https://github.com/flathub/org.phoenicis.playonlinux/blob/master/org.phoenicis.playonlinux.yml installs the above i386 Compat and GL32 runtime dependencies.

`flatpak install --user flathub org.phoenicis.playonlinux`   installs dependencies! HOW?

I have copied the metata to my yml but still the issue perisists.
Kindly see if I'm making any mistake, as I have copied 32 bit info from other wine with compat.i386 ymls
https://github.com/fastrizwaan/flatpak-wine32/blob/main/io.github.flatpak-wine32.yml

As _org.phoenicis.playonlinux_ can install i386 depenencies, but same thing not working with lutris and my flatpak-win32 and winepak32. what should I do? I want Compat.i386 and GL32.default to install with flatpak-win32.

Thank you.

metadata:
```
$ cat build-dir/metadata

[Application]
name=io.github.flatpak-wine32
runtime=org.freedesktop.Platform/x86_64/20.08
sdk=org.freedesktop.Sdk/x86_64/20.08
command=wine

[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=all;
features=multiarch;
filesystems=host;
persistent=.wine;

[Environment]
WINEDLLOVERRIDES="mscoree,mshtml="
LD_LIBRARY_PATH=/app/lib:/app/lib32

[Extension org.freedesktop.Platform.Compat.i386]
directory=lib/i386-linux-gnu
version=20.08

[Extension org.freedesktop.Platform.Compat.i386.Debug]
directory=lib/debug/lib/i386-linux-gnu
no-autodownload=true
version=20.08

[Extension org.freedesktop.Platform.GL32]
directory=lib/i386-linux-gnu/GL
no-autodownload=true
subdirectories=true
add-ld-path=lib
download-if=active-gl-driver
enable-if=active-gl-driver
merge-dirs=vulkan/icd.d;glvnd/egl_vendor.d
version=20.08

[Extension io.github.flatpak_wine32.Locale]
directory=share/runtime/locale
autodelete=true
locale-subset=true

[Build]
built-extensions=io.github.flatpak_wine32.Locale;
```

**Comment by tinywrkb** [comment] 2021-03-08 13:35
Duplicate of #3094 and #3072.  
If you would have looked in the Lutris package repo you would have noticed that https://github.com/flathub/net.lutris.Lutris/issues/53 is pinned and it's exactly the as described here and is linking the mentioned Flatpak issues.

**Comment by hfiguiere** [comment] 2024-02-10 19:30
duplicate

**Closed by hfiguiere** 2024-02-10 19:30 UTC
Labels: duplicate
