### ISSUE TITLE
Error updating org.freedesktop.Platform.GL.nvidia-390-42

### ISSUE THREAD

**Issue by hubslave** [flatpak/flatpak#1512] opened 2018-03-21 23:42 UTC
Hello,

when doing routine update I got this error today:

```
1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds           
creating file OpenCL/vendors/nvidia.icd: No such file or directory
Warning: Failed to update org.freedesktop.Platform.GL.nvidia-390-42/x86_64/1.4: While trying to apply extra data: apply_extra script failed
```

flatpak 0.8.7, EL7.4

**Comment by TingPing** [comment] 2018-03-22 00:26
Duplicate of #1511

**Closed by TingPing** 2018-03-22 00:26 UTC
