### ISSUE TITLE
I can't find the flatpak package for Chinese input method. It's a pity.

### ISSUE THREAD

**Issue by chasezphp** [flatpak/flatpak#2970] opened 2019-06-21 11:04 UTC
## Steps to reproduce
I can't find the flatpak package for Chinese input method. It's a pity.

**Comment by mwleeds** [comment] 2019-06-25 20:41
Closing this as a duplicate of https://github.com/flatpak/flatpak/issues/2031

If that's incorrect and this is a separate issue, please re-open and give more information on exactly what flatpak you're looking for and what problem you're trying to solve.

**Closed by mwleeds** 2019-06-25 20:41 UTC
