### ISSUE TITLE
bwrap: execvp nautilus: No such file or directory

### ISSUE THREAD

**Issue by LapotinVal** [flatpak/flatpak#1679] opened 2018-05-16 08:37 UTC
last fedora 28, try install & run nautilus from gitlab gnome with flatpak file
if use runtime 3.26 or 3.28 to run nightly nautilus it start

**Comment by bugaevc** [comment] 2018-05-16 10:54
This is because, apparently, `flatpak run` no longer understands the `--user` argument:
```bash
$ flatpak --user list
Ref                                                  Options
org.gnome.Builder/x86_64/master                      current
...(lots of others)
$ flatpak --system list
Ref                                             Options
org.gimp.GIMP/x86_64/stable                     current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6      runtime
org.gnome.Platform/x86_64/3.28                  runtime
$ flatpak --user run org.gnome.Builder  # completion doesn't work anymore
error: Unknown option --user
$ flatpak run --user org.gnome.Builder  # same this way
error: Unknown option --user
$ flatpak run org.gnome.Builder  # completing org.gnome.Builder works
bwrap: execvp gnome-builder: No such file or directory
```
Flatpak 0.11.7, Fedora 28

**Comment by alatiera** [comment] 2018-05-16 12:30
Same error here, weird thing is that the broken things only happen to be things that are compiled against `org.gnome.Sdk/Platform master`. `Flathub`'s (stable)version of `org.gnome.Builder` and other apps from `Flathub` seem to work fine.

**Comment by alatiera** [comment] 2018-05-16 12:47
downgrading `flatpak` and `flatpak-libs` with `dnf downgrade flatpak flatpak-libs` from `0.11.7` to `0.11.3` does not seem to fix this so I assume the problem is lower on the stack.

**Comment by Exalm** [comment] 2018-05-17 14:14
GNOME Games nightly is affected as well, but downgrading the runtime fixes it. So it's most probably related to the new fd.o runtime.

@bugaevc: IIRC `flatpak run --user` never worked.

**Comment by albfan** [comment] 2018-05-18 05:10
@Exalm Can you explain details to downgrade runtime? What commit to to back to?. Maybe update https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading.

**Comment by Exalm** [comment] 2018-05-18 05:39
Well, I did
```
ostree --repo=.local/share/flatpak/repo pull --depth=250 --commit-metadata-only gnome-nightly runtime/org.gnome.Platform/x86_64/master
ostree --repo=.local/share/flatpak/repo log runtime/org.gnome.Platform/x86_64/master
```

Then took the last commit that has date in English and was built with Flatpak 0.11.3. :)
It's `b115edde9c61bec9a1b6b9df9dcaa5f4c653fd32565c3a2d05d37d90aaac5b4a`.

Then
```
flatpak --user update --commit=b115edde9c61bec9a1b6b9df9dcaa5f4c653fd32565c3a2d05d37d90aaac5b4a org.gnome.Platform//master
```

**Comment by alatiera** [comment] 2018-07-17 13:17
This seems has been fixed for a while (can't find reference when it was), its probably fine to close it.

**Closed** 2018-07-17 14:19 UTC

**Comment by mwleeds** [comment] 2020-04-21 23:48
For the sake of anyone else who comes to this bug report wondering why you get a `No such file or directory` error for a file that exists: in my case it's because the file has `#!/usr/bin/python` at the top and the runtime I'm trying to use doesn't have `python`.

**Comment by vlad88sv** [comment] 2020-09-22 02:07
For what is worth, I had this happening on Ubuntu 20.04 + Build 3.36.0 + Flatpak 1.6.5

It seems that this happens after cloning a repo + downloading dependencies (SDK, etc), and then running the app.

As per this answer [1] it's fixed by restarting Builder. This worked for me.

[1] https://stackoverflow.com/a/57645772/1172180

**Comment by lengyijun** [comment] 2023-01-19 11:36
Same issue for  me
```
flatpak run com.visualstudio.code.tool.fish 
Similar installed refs found for ‘com.visualstudio.code.tool.fish’:

   1) runtime/com.visualstudio.code.tool.fish/x86_64/21.08 (user)
   2) runtime/com.visualstudio.code.tool.fish/x86_64/22.08 (user)
   3) runtime/com.visualstudio.code.tool.fish/x86_64/20.08 (user)

Which do you want to use (0 to abort)? [0-3]: 1
bwrap: execvp /bin/sh: No such file or directory
```

**Comment by TingPing** [comment] 2023-01-19 16:54
@lengyijun Your issue is completely unrelated. `com.visualstudio.code.tool.fish` is an extension to `com.visualstudio.code` you aren't supposed to run it directly.

You can do `flatpak run --command=/some/path/to/extension/commands com.visualstudio.code` (I don't know the path offhand).
