### ISSUE TITLE
URLs cannot be opened

### ISSUE THREAD

**Issue by aleb** [flatpak/flatpak#74] opened 2016-06-03 06:21 UTC
For example a Gtk.AboutDialog can be set a website:
```
        dialog = Gtk.AboutDialog()
        dialog.set_website(APPURL)
```

Clicking the "Website" link in the dialog window shows an error message: Could not show link / No application is registered as handling this file.

**Comment by alexlarsson** [comment] 2016-06-03 10:33
Duplicate of https://github.com/flatpak/flatpak/issues/76

**Closed** 2016-06-03 10:32 UTC
