### ISSUE TITLE
Epiphany keeps crashing

### ISSUE THREAD

**Issue by pyluyten** [flatpak/flatpak#475] opened 2017-01-07 08:26 UTC
I did install Epiphany from org.gnome 3.22 but no way to open any URL. Note i started investigating because of feedreader so it's rather WebKit than Epiphany itself.

fedora 24

flatpak.x86_64                         0.8.0-1.fc24                     @updates
flatpak-libs.x86_64                    0.8.0-1.fc24                     @updates
xdg-desktop-portal.x86_64                                    0.4-1.fc24                                 @updates
xdg-desktop-portal-gtk.x86_64                                0.3-1.fc24                                 @updates

$ flatpak list
org.gnome.Epiphany  
org.gnome.feedreader

below is the terminal output, which goes on & on until i ctrl+c 

$ flatpak run org.gnome.Epiphany https://fedoramagazine.org/weather-updates-openweather-gnome-shell-extension/

** (epiphany:2): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"

(epiphany:2): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(epiphany:2): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

** (WebKitWebProcess:26): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

** (WebKitWebProcess:31): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:26): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 183 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:31): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 183 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

** (WebKitWebProcess:61): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"

** (WebKitWebProcess:71): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
libGL error: No matching fbConfigs or visuals found
Gtk-Message: Failed to load module "pk-gtk-module"
libGL error: failed to load driver: swrast
Gtk-Message: Failed to load module "pk-gtk-module"

(WebKitWebProcess:61): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 183 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**Comment by TingPing** [comment] 2017-01-07 08:40
Nvidia drivers?

**Comment by pyluyten** [comment] 2017-01-07 08:51
$ lspci -v -s 01:00.0
01:00.0 VGA compatible controller: NVIDIA Corporation GT218 [GeForce 8400 GS Rev. 3] (rev a2) (prog-if 00 [VGA controller])
	Subsystem: Gigabyte Technology Co., Ltd Device 34ed
	Flags: bus master, fast devsel, latency 0, IRQ 29
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia

**Comment by pyluyten** [comment] 2017-01-07 08:52
forgot version

xorg-x11-drv-nvidia-340xx.x86_64      1:340.98-1.fc24                   @rpmfusion-nonfree-updates
xorg-x11-drv-nvidia-340xx-kmodsrc.x86_64
xorg-x11-drv-nvidia-340xx-libs.x86_64 1:340.98-1.fc24                   @rpmfusion-nonfree-updates

**Comment by TingPing** [comment] 2017-01-07 09:22
Duplicate of #138

**Comment by alexlarsson** [comment] 2017-01-12 10:44
Yeah, we need to have a better story here. I'm going to look into the nvidia driver issue soon.

**Closed** 2017-01-12 10:44 UTC
