### ISSUE TITLE
GPG signatures found, but none are in trusted keyring

### ISSUE THREAD

**Issue by rszibele** [flatpak/flatpak#2043] opened 2018-08-29 13:49 UTC
## Linux distribution and version
OpenSUSE Leap 15

````
$ uname -a
Linux opensuse 4.18.5-1.g9e91e29-vanilla #1 SMP PREEMPT Fri Aug 24 12:38:43 UTC 2018 (9e91e29) x86_64 x86_64 x86_64 GNU/Linux
````

## Flatpak version
Flatpak 0.10.4

## Description of the problem
Installing QOwnNotes (for example) gives the following error message:
`GPG signatures found, but none are in trusted keyring`

## Steps to reproduce
````
# flatpak install flathub org.qownnotes.QOwnNotes
````

## What I've tried

````
# flatpak remote-delete --force flathub
# flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# flatpak install flathub org.qownnotes.QOwnNotes
````
Same issue.

````
# wget https://flathub.org/repo/flathub.gpg
# flatpak remote-modify --gpg-import=flathub.gpg flathub
# flatpak install flathub org.qownnotes.QOwnNotes
````
Same issue.

Trying to update Flatpak:
````
# flatpak update
Looking for updates...
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
^C
````

**Comment by mwleeds** [comment] 2018-08-29 18:49
Recent versions of ostree have patches that should at least make this error less likely or go away entirely, so perhaps you could update flatpak and libostree somehow.

Anyway, closing as a duplicate of #1450

**Closed by mwleeds** 2018-08-29 18:49 UTC
