### ISSUE TITLE
Gnome runtime update breaks SDL app

### ISSUE THREAD

**Issue by Taiko2k** [flatpak/flatpak#2052] opened 2018-08-31 00:09 UTC
## Linux distribution and version
Antergos, Linux Mint
## Flatpak version
flatpak 1.0.1-1
## Description of the problem

I'm not sure where issues with runtimes should be sent, I hope this is the right place.

I have an issue where my SDL based application has stopped working after a recent update to org.gnome.platform/x86_64. It previously did work on earlier versions of both 3.26 and 3.28, but now appears to segfault when making a call to SDL_CreateRenderer() after having updated the runtime.

---

What is the recourse for this kind of thing? Isn't part of the point of Flatpak is that applications don't break once released? With traditional packaging I could instruct a user to downgrade a conflicting system package until the issue is resolved, but how does one downgrade a minor version of a runtime? The former may be bad user experience, but this seems even worse to me. Apologies if my frustration here is misdirected.

**Comment by alexlarsson** [comment] 2018-08-31 07:09
There is no great place to discuss the gnome runtimes atm, but this is likely caused by something in the freedesktop 1.6 runtime which has issues tracked here: https://github.com/flatpak/freedesktop-sdk-images/. However, here is fine to. 

I understand that its a pain in the ass when something like this happens, and we *try* to keep runtime updates minimal and rare for this reason. However, sometimes they *do* happen. It is possible to downgrade the runtime with `flatpak remote-info --log` + `flatpak update --commit=COMMIT`, but that is not a great experience for your users.

As to fixing this. Do you know the exact commit that broke your app? What app was this? Do you have a backtrace of the crash?

**Comment by Taiko2k** [comment] 2018-08-31 08:00
Thanks for your reply.

Those commands work, I'm relieved. The update with the issue appears to be this latest one:

> Ref: runtime/org.gnome.Platform/x86_64/3.28
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.28
Collection ID: org.flathub.Stable
Date: 2018-08-30 19:06:39 +0000
Subject: build of org.gnome.Sdk, Thu Aug 30 11:32:42 UTC 2018
Commit: 9d3fe926d425ad837e40a0945020a00f09c1f531335987a753e07f276d76ee36

With the previous one working:

> Subject: build of org.gnome.Sdk, Mon Aug 13 14:53:04 UTC 2018
 Date: 2018-08-13 22:50:57 +0000
 Commit: f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8

The application is a music player of mine https://github.com/Taiko2k/tauonmb

I'm not very familiar with the process of debugging, but I ran gdb and it gave me this, hopefully it is helpful:

>Thread 5 "si_shader:0" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 106]
0x000000313092b360 in ?? () from /lib/libc.so.6

**Comment by alexlarsson** [comment] 2018-08-31 08:30
I tried to build https://github.com/Taiko2k/tauonmb-flatpak here and i have the same runtime version, but it works for me.

To debug it, you need to install the com.github.taiko2k.tauonmb.Debug extensions to get symbols. And then run `fatpak run -d --command=sh com.github.taiko2k.tauonmb` and gdb the app.

However, from the segfault above it looks like the crash is in the so_shader:0, which I assume is the OpenGL driver. That explains why I am not seeing this. What OpenGL driver are you using? 

Can you try removing `~/.var/app/com.github.taiko2k.tauonmb/cache/mesa_shader_cache` and see if that fixes things?

**Comment by Taiko2k** [comment] 2018-08-31 08:39
I'm using mesa. Removing `mesa_shader_cache` does in fact solve the problem. How strange.

**Comment by alexlarsson** [comment] 2018-10-01 09:53
Should be fixed now.

**Closed** 2018-10-01 09:52 UTC
