### ISSUE TITLE
Segmentation fault with missing fuse module

### ISSUE THREAD

**Issue by cxrvh** [flatpak/flatpak#2941] opened 2019-06-04 16:07 UTC
## Linux distribution
Arch Linux

## Flatpak version
1.4.0

## Description of the problem
When the fuse module is missing, Flatpak simply crashes with a segmentation fault.

```
$ flatpak update

Looking for updates?

       ID                                               Arch              Branch            Remote             Download
 1. [/] org.freedesktop.Platform                         x86_64            18.08             flathub              994.2?kB / 292.7?MB

Warning: Could not unmount revokefs-fuse filesystem at /var/tmp/flatpak-cache-QV9G2Z/org.freedesktop.Platform-8EN01Z: Child process exited with code 1
Warning: Could not unmount revokefs-fuse filesystem at /var/tmp/flatpak-cache-QV9G2Z/org.freedesktop.Platform-8EN01Z: Child process exited with code 1
Segmentation fault (core dumped)
```

That the fuse module is missing is actually printed in the console, but the message usually gets overwritten by the warnings:
```
Updating 1/9?fuse: device not found, try 'modprobe fuse' first
Updating 1/9? ???????????????????? 100%  497.1?kB/sfusermount: entry for /var/tmp/flatpak-cache-QV9G2Z/org.freedesktop.Platform-XBK01Z not found in /etc/mtab
fusermount: entry for /var/tmp/flatpak-cache-QV9G2Z/org.freedesktop.Platform-XBK01Z not found in /etc/mtab
```
## Steps to reproduce
1. Update kernel (Arch Linux doesn't keep the old kernel)
2. Update or install an app in a system-wide installation
3. After rebooting the new kernel, everything works again as expected

## Stack trace
```
       Message: Process 12030 (flatpak) of user 1000 dumped core.
                
                Stack trace of thread 12030:
                #0  0x000055a8afd3bf6a operation_error (flatpak)
                #1  0x00007fe7640aa6d0 ffi_call_unix64 (libffi.so.6)
                #2  0x00007fe7640aa0a0 ffi_call (libffi.so.6)
                #3  0x00007fe76558dcf8 g_cclosure_marshal_generic_va (libgobject-2.0.so.0)
                #4  0x00007fe765576465 g_signal_emit_valist (libgobject-2.0.so.0)
                #5  0x00007fe765577140 g_signal_emit (libgobject-2.0.so.0)
                #6  0x000055a8afdbcc93 flatpak_transaction_real_run (flatpak)
                #7  0x000055a8afd3e29b flatpak_cli_transaction_run (flatpak)
                #8  0x000055a8afdbbb80 flatpak_transaction_run (flatpak)
                #9  0x000055a8afd0d856 flatpak_builtin_update (flatpak)
                #10 0x000055a8afd0189a flatpak_run (flatpak)
                #11 0x000055a8afd01d64 main (flatpak)
                #12 0x00007fe765269ce3 __libc_start_main (libc.so.6)
                #13 0x000055a8afd0004e _start (flatpak)
                
                Stack trace of thread 12031:
                #0  0x00007fe7653360d1 __poll (libc.so.6)
                #1  0x00007fe7654997c0 n/a (libglib-2.0.so.0)
                #2  0x00007fe7654998ae g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe765499902 n/a (libglib-2.0.so.0)
                #4  0x00007fe765474f21 n/a (libglib-2.0.so.0)
                #5  0x00007fe765412a92 start_thread (libpthread.so.0)
                #6  0x00007fe765340cd3 __clone (libc.so.6)
                
                Stack trace of thread 12106:
                #0  0x00007fe7653360d1 __poll (libc.so.6)
                #1  0x00007fe7654997c0 n/a (libglib-2.0.so.0)
                #2  0x00007fe7654998ae g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe752a8fbde n/a (libdconfsettings.so)
                #4  0x00007fe765474f21 n/a (libglib-2.0.so.0)
                #5  0x00007fe765412a92 start_thread (libpthread.so.0)
                #6  0x00007fe765340cd3 __clone (libc.so.6)
                
                Stack trace of thread 12033:
                #0  0x00007fe7653360d1 __poll (libc.so.6)
                #1  0x00007fe7654997c0 n/a (libglib-2.0.so.0)
                #2  0x00007fe76549a7f2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fe765c655b8 n/a (libpolkit-agent-1.so.0)
                #4  0x00007fe765474f21 n/a (libglib-2.0.so.0)
                #5  0x00007fe765412a92 start_thread (libpthread.so.0)
                #6  0x00007fe765340cd3 __clone (libc.so.6)
                
                Stack trace of thread 12113:
                #0  0x00007fe76533b97d syscall (libc.so.6)
                #1  0x00007fe765448141 g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fe7654c9343 n/a (libglib-2.0.so.0)
                #3  0x00007fe76546df4b n/a (libglib-2.0.so.0)
                #4  0x00007fe765474f21 n/a (libglib-2.0.so.0)
                #5  0x00007fe765412a92 start_thread (libpthread.so.0)
                #6  0x00007fe765340cd3 __clone (libc.so.6)
                
                Stack trace of thread 12127:
                #0  0x00007fe76533b97d syscall (libc.so.6)
                #1  0x00007fe765448141 g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fe7654c9343 n/a (libglib-2.0.so.0)
                #3  0x00007fe76546df4b n/a (libglib-2.0.so.0)
                #4  0x00007fe765474f21 n/a (libglib-2.0.so.0)
                #5  0x00007fe765412a92 start_thread (libpthread.so.0)
                #6  0x00007fe765340cd3 __clone (libc.so.6)
                
                Stack trace of thread 12032:
                #0  0x00007fe7653360d1 __poll (libc.so.6)
                #1  0x00007fe7654997c0 n/a (libglib-2.0.so.0)
                #2  0x00007fe76549a7f2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fe76560b648 n/a (libgio-2.0.so.0)
                #4  0x00007fe765474f21 n/a (libglib-2.0.so.0)
                #5  0x00007fe765412a92 start_thread (libpthread.so.0)
                #6  0x00007fe765340cd3 __clone (libc.so.6)
```

**Comment by mwleeds** [comment] 2019-06-07 01:42
cc @uajain

**Comment by Ezwen** [comment] 2019-07-20 06:18
Same problem here this morning on Fedora 30:
```
$ flatpak update -y                                                                                                                                                                                                                   
Looking for updates…


        ID                                                    Arch               Branch            Remote             Download
        ID                                                    Arch               Branch            Remote             Download
        ID                                                    Arch               Branch            Remote             Download
        ID                                                    Arch               Branch            Remote             Download
 1. [—] im.riot.Riot                                          x86_64             stable            flathub             818,4 kB / 76,4 MB
 2. [ ] org.freedesktop.Platform.GL.nvidia-430-14             x86_64             1.4               flathub            < 70,6 MB

Warning: Could not unmount revokefs-fuse filesystem at /var/tmp/flatpak-cache-M93I5Z/im.riot.Riot-WXXI5Z: Child process exited with code 1
Warning: Could not unmount revokefs-fuse filesystem at /var/tmp/flatpak-cache-M93I5Z/im.riot.Riot-WXXI5Z: Child process exited with code 1
[1]    5385 segmentation fault (core dumped)  flatpak update -y
```

**Comment by Ezwen** [comment] 2019-07-20 06:26
Actually the cause was that I booted on the wrong kernel (ie. not the latest one I has installed) from grub, and probably this older kernel did not have `fuse` correctly compiled/installed. Problem solved by booting on the right kernel.

**Comment by mwleeds** [comment] 2020-10-23 00:48
Sounds like we can close this then.

**Closed by mwleeds** 2020-10-23 00:48 UTC
