### ISSUE TITLE
System flatpak in broken state: Cannot add or delete remote due to gpg keyring error

### ISSUE THREAD

**Issue by rugk** [flatpak/flatpak#2796] opened 2019-04-01 19:31 UTC
## Linux distribution and version
Fedora 29

## Flatpak version

flatpak 1.2.3

## Description of the problem

When I do:
```sh
$ flatpak --system remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
error: Remote flathub already exists
```

Which is– per sé – okay…

However:
```sh
flatpak --system remote-delete flathub     
The following refs are installed from remote 'flathub':

   1) runtime/org.gnome.Platform/x86_64/3.24

Remove them? [y/n]: y
F: Error updating remote metadata for 'flathub': GPG signatures found, but none are in trusted keyring
Uninstalling runtime/org.gnome.Platform/x86_64/3.24
```

(the uninstall fails)

Note, however, it listed more installed runtimes and things when I first executed the command, so I could uninstall _some_. It only fails for this particular runtime.

Likewise, if I want to install anything:
```
$ flatpak --system install atom         
Looking for matches?
F: An error was encountered searching remote ?flathub? for ?atom?: Unable to load summary from remote flathub: GPG signatures found, but none are in trusted keyring
error: No remote refs found similar to ?atom?
$ flatpak --system install io.atom.Atom        
Looking for matches?
F: An error was encountered searching remote ?flathub? for ?io.atom.Atom?: Unable to load summary from remote flathub: GPG signatures found, but none are in trusted keyring
error: No remote refs found similar to ?io.atom.Atom?

```

Only my system installation is broken, `--user` stuff works.

## Steps to reproduce

I have no idea how I caused this. 

## Workaround

Okay, I could not work around it by installing it like this, which seems to have added the flathub remote with a different name though :laughing::
```sh
flatpak --system install --from https://flathub.org/repo/appstream/io.atom.Atom.flatpakref
The application io.atom.Atom depends on runtimes from:
  https://dl.flathub.org/repo/
Configure this as new remote 'flathub-1' [Y/n]: y
Required runtime for io.atom.Atom/x86_64/stable (runtime/org.freedesktop.Sdk/x86_64/18.08) found in remote flathub-1
Do you want to install it? [Y/n]: y

io.atom.Atom permissions:
    ipc       network       pulseaudio            ssh-auth
    x11       devices       file access [1]       dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*,
        org.freedesktop.Flatpak, org.freedesktop.Notifications,
        org.freedesktop.secrets, org.gtk.vfs, org.gtk.vfs.*


        ID                                         Arch   Branch Op Remote      Download
 1. [?] org.freedesktop.Sdk                        x86_64 18.08  i  flathub-1     446.5 kB / 596.1 MB
 2. [ ] org.freedesktop.Sdk.Locale                 x86_64 18.08  i  flathub-1   < 319.3 MB (partial)
 3. [ ] org.freedesktop.Platform.Icontheme.Adwaita x86_64 1.0    u  gnome        < 12.6 MB
 4. [ ] org.freedesktop.Platform.html5-codecs      x86_64 18.08  i  flathub-1     < 4.9 MB
 5. [ ] io.atom.Atom                               x86_64 stable i  atom-origin < 141.5 MB
[…]
```

**Comment by rugk** [comment] 2019-04-01 19:33
Possibly related to a different error: In GNOME Software, I see that I have two remotes or so, one points to `dl.flathub.org` and one to `flathub.org`.

**Comment by mwleeds** [comment] 2019-04-01 23:14
You could try running `sudo rm /var/lib/flatpak/repo/tmp/cache/summaries/*` and then try again

**Comment by rugk** [comment] 2019-04-02 06:37
Okay, I'll try that…

**Comment by rugk** [comment] 2019-04-02 17:12
Did so. Deleting the remote still does not work (same error).

**Comment by mwleeds** [comment] 2019-04-11 17:49
Post the output of `ls -l /var/lib/flatpak/repo/`? It's possible you added the remote incorrectly and the GPG keyring isn't there.

**Comment by mwleeds** [comment] 2019-04-11 17:51
By the way this is sort of a duplicate of https://github.com/flatpak/flatpak/issues/1450 but if it's consistently reproducible and not transient for you maybe it's worth leaving this issue open and investigating separately.

**Comment by mwleeds** [comment] 2019-04-11 17:52
> Did so. Deleting the remote still does not work (same error).

It would be good to specify the commands you used. Whether or not you added back the remote using the `flatpakrepo` file is important.

**Comment by rugk** [comment] 2019-04-12 19:06
>  consistently reproducible 

Yep. :+1: 

> Post the output of ls -l /var/lib/flatpak/repo/?

```sh
ls -l /var/lib/flatpak/repo/                 
insgesamt 60
-rw-r--r--.   1 root root 2888  1. Apr 21:32 atom1-origin.trustedkeys.gpg
-rw-r--r--.   1 root root 2888  1. Apr 21:45 atom2-origin.trustedkeys.gpg
-rw-r--r--.   1 root root 2888  1. Apr 21:29 atom-origin.trustedkeys.gpg
-rw-r--r--.   1 root root 1616  1. Apr 21:45 config
drwxr-xr-x.   2 root root 4096 15. Nov 2016  extensions
-rw-r--r--.   1 root root 2888  1. Apr 21:29 flathub-1.trustedkeys.gpg
-rw-r--r--.   1 root root 1225 16. Jun 2017  flathub.trustedkeys.gpg
-rw-r--r--.   1 root root 1236 20. Nov 15:25 gnome-nightly.trustedkeys.gpg
-rw-r--r--.   1 root root  665 15. Jun 2017  gnome.trustedkeys.gpg
drwxr-xr-x. 258 root root 4096 15. Jun 2017  objects
-rw-r--r--.   1 root root 1236  8. Dez 16:25 org.gnome.Epiphany-origin.trustedkeys.gpg
-rw-r--r--.   1 root root 1239 15. Jun 2017  org.mozilla.FirefoxRepo.trustedkeys.gpg
drwxr-xr-x.   4 root root 4096 15. Nov 2016  refs
drwxr-xr-x.   2 root root 4096 12. Apr 20:49 state
drwxr-xr-x.   3 root root 4096 12. Apr 20:49 tmp
```

> It would be good to specify the commands you used. 

Always just doing it [as per the OP](https://github.com/flatpak/flatpak/issues/2796#issue-427873965) in "Description of the problem":
`flatpak --system remote-add flathub https://flathub.org/repo/flathub.flatpakrepo` and `flatpak --system remote-delete flathub`. Neither of it works.

> Whether or not you added back the remote using the flatpakrepo file is important.

If I cannot delete it, I cannot add it back… aka "Remote flathub already exists".

**Comment by mwleeds** [comment] 2019-04-12 21:14
> -rw-r--r--.   1 root root 2888  1. Apr 21:29 flathub-1.trustedkeys.gpg
> -rw-r--r--.   1 root root 1225 16. Jun 2017  flathub.trustedkeys.gpg

Pretty strange that these two keyrings which should be identical are different sizes. For me `flathub.trustedkeys.gpg` is 2852 bytes so I'm guessing for you `flathub-1.trustedkeys.gpg` is the correct one. You could try `sudo cp /var/lib/flatpak/repo/flathub-1.trustedkeys.gpg /var/lib/flatpak/repo/flathub.trustedkeys.gpg` or if you want to stick to the CLI use `remote-delete --force` to delete the remote and then re-add it?

**Comment by rugk** [comment] 2019-04-12 21:33
Both files are binary. (but totally different) Yes, flathub-1 is correct.

```sh
$ gpg2 --with-fingerprint flathub-1.trustedkeys.gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096/0x4184DD4D907A7CAE 2017-06-16 [SC] [expires: 2027-06-14]
      Key fingerprint = 6E5C 05D9 79C7 6DAF 93C0  8135 4184 DD4D 907A 7CAE
uid                             Flathub Repo Signing Key <flathub@flathub.org>
sub   rsa4096/0x562702E9E3ED7EE8 2017-06-16 [S] [expires: 2027-06-14]
      Key fingerprint = 54A6 CDDD 8919 FB20 4200  D8AC 5627 02E9 E3ED 7EE8
$ gpg2 --with-fingerprint flathub.trustedkeys.gpg  
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048/0x1BB80F88F015AA1E 2017-04-08 [SC]
      Key fingerprint = 39E6 9544 E78B 8C03 D7ED  254F 1BB8 0F88 F015 AA1E
uid                             Flathub <flathub@flatpak.org>
sub   rsa2048/0x8E940DE7A2A5E4A7 2017-04-08 [E]
      Key fingerprint = D2AA 1774 9F01 E097 ACAF  2D9A 8E94 0DE7 A2A5 E4A7
```

So it seems to be an old, expired key…

**Comment by rugk** [comment] 2019-04-12 21:35
And yes, after replacing the key, it does work. Thanks…

**Comment by mwleeds** [comment] 2019-08-20 21:25
So it seems the problem here was use of an outdated key, which doesn't seem to be in circulation any more.

**Closed by mwleeds** 2019-08-20 21:25 UTC
