### ISSUE TITLE
Feature Request - Transport encryption for the flatpak documentation

### ISSUE THREAD

**Issue by kaymio** [flatpak/flatpak#2870] opened 2019-04-30 17:51 UTC
## Linux distribution and version
every distribution and every version

## Flatpak version
any

## Description of the problem
When navigating to the [documentation for flatpak](https://docs.flatpak.org/)
Firefox shows me this

![2019-04-30 19-33-40](https://user-images.githubusercontent.com/22966929/56982251-2e1b3900-6b81-11e9-9267-bb144bb01b4a.png)

## Steps to reproduce

Navigate to https://docs.flatpak.org

Within the FOSS community we should look out for each other and protect everybody's privacy. Especially if there is a simple, automated way through the likes of [Let's encrypt](https://github.com/letsencrypt)

**Comment by mwleeds** [comment] 2019-04-30 19:06
According to [this blog post](http://blog.readthedocs.com/https-for-custom-domains/) it is possible to have HTTPS work with custom domains that redirect to readthedocs.org, but we need someone with control over the flatpak.org DNS records to make it work I believe.

**Comment by TingPing** [comment] 2019-04-30 19:26
I enabled the option months ago but its just stuck on `HTTPS status: pending_validation`, so yea maybe DNS changes needed.

**Comment by mwleeds** [comment] 2019-05-15 17:56
Closing as a duplicate of https://github.com/flatpak/flatpak-docs/issues/133

**Closed by mwleeds** 2019-05-15 17:56 UTC
Labels: enhancement, website
