### ISSUE TITLE
error: Failed to install io.designer.GravitDesigner: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

### ISSUE THREAD

**Issue by nahuelwexd** [flatpak/flatpak#3493] opened 2020-03-25 20:36 UTC
## Linux distribution and version

Fedora 32 (Workstation Edition)

## Flatpak version

Flatpak 1.6.2

## Description of the problem

While trying to install Gravit Designer from Flathub, the installation fails with `apply_extra script failed, exit status 256`

## Steps to reproduce

1. Run `flatpak install io.designer.GravitDesigner//stable`
2. Wait until installation fails

**Comment by mwleeds** [comment] 2020-03-25 21:15
I can reproduce this on Pop!_OS with Flatpak built from master:
```
↳ flatpak install flathub io.designer.GravitDesigner//stable
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1

io.designer.GravitDesigner permissions:
    ipc                  network       x11     dri
    file access [1]      tags [2]

    [1] home
    [2] proprietary

        ID                                    Branch   Op   Remote   Download
 1. [✓] org.freedesktop.Platform.GL.default   19.08    u    flathub   48.5 MB / 94.9 MB
 2. [✓] org.freedesktop.Platform.Locale       19.08    u    flathub   17.5 kB / 318.2 MB
 3. [✓] org.freedesktop.Platform.openh264     2.0      i    flathub  858.6 kB / 916.8 kB
 4. [✓] org.freedesktop.Platform              19.08    u    flathub    6.0 MB / 238.2 MB
 5. [✗] io.designer.GravitDesigner            stable   i    flathub  198.9 MB / 206.0 MB

Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install io.designer.GravitDesigner: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```
It's the same error message as #3238 but presumably a different root cause.

**Comment by mwleeds** [comment] 2020-03-25 21:18
My guess would be this is a side effect of https://github.com/flathub/io.designer.GravitDesigner/pull/19

cc @refi64

**Comment by mwleeds** [comment] 2020-03-25 21:18
cc @FakeShemp

**Comment by FakeShemp** [comment] 2020-03-25 21:26
It's related to https://github.com/flathub/io.designer.GravitDesigner/issues/20

**Comment by mwleeds** [comment] 2020-03-25 22:14
Okay, closing this then

**Closed by mwleeds** 2020-03-25 22:14 UTC

**Comment by FakeShemp** [comment] 2020-03-25 22:15
Help with alternatives to unzip are welcome :)
