### ISSUE TITLE
Flatpak gets confused when the same ref of an extension exists in two repositories

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#3128] opened 2019-09-24 22:49 UTC
Note that this happened when the freedesktop repo has openh264 with the multiple minimum versions (1.0.9, 1.2.5, 1.4.2) and flathub doesn't. cc @alexlarsson this is the bug we discussed on IRC while i was testing flatpak 1.0.9.

# What Happened
1) Configure https://cache.sdk.freedesktop.org/releases/  and flathub as repositories
2) Install an app from flathub that uses the freedesktop 19.08 runtime (eg Steam or Riot) and ensure the runtime comes from the freedesktop repo
3) Notice that the openh264 extension is correctly installed
4) Install an app from flathub that uses the GNOME 3.34 runtime (eg gedit)
5) Notice that the openh264 extension has an update and fails to install (it thinks there is an update, but the update is actually the commit from the flathub repo, even though it says fdsdk - so even though it knows the repo name, the wrong commit from the wrong repo is being selected somehow).

# What I expected to happen
At step 5 for the openh264 extension not to have an update, as the latest is already installed.

# Log
This is the console output example of what happened https://pastebin.ubuntu.com/p/wN8VB2YkCb/

**Comment by arderyp** [comment] 2019-09-26 00:24
I have the same problem.  Running latest ubuntu 18.04.  I was running default ubuntu flatpak, whcih was ancient, then I saw [this thread](https://forums.linuxmint.com/viewtopic.php?t=302122) about the issue I was experiencing:

```
$ sudo flatpak update
[sudo] password for arderyp: 
Looking for updates...
Installing in system:
org.freedesktop.Platform.openh264/x86_64/19.08 flathub c0062d844eea
Is this ok [y/n]: y
Installing: org.freedesktop.Platform.openh264/x86_64/19.08 from flathub
Warning: Failed to install org.freedesktop.Platform.openh264/x86_64/19.08: runtime/org.freedesktop.Platform.openh264/x86_64/19.08 needs a later flatpak version (1.4.2)

```

So, I [added the official flatpak PPA](https://flatpak.org/setup/Ubuntu/) and now I have flatpak version 1.4.3, and I keep getting this loop of needing to install openh264, it installing, then warning that it didnt install then telling me I need to install it:

```
$ sudo flatpak update
Looking for updates…


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

$ sudo flatpak update
Looking for updates…


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

$ sudo flatpak update
Looking for updates…


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

$ sudo flatpak repair
Working on the system installation at /var/lib/flatpak
Verifying flathub:runtime/com.github.wwmm.pulseeffects.Locale/x86_64/stable…
Verifying flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08…
Verifying flathub:appstream2/x86_64…
Verifying flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/19.08…
Verifying flathub:app/com.github.wwmm.pulseeffects/x86_64/stable…
Verifying flathub:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08…
Verifying flathub:runtime/org.gnome.Platform/x86_64/3.32…
Removing non-deployed ref flathub:runtime/org.freedesktop.Platform.openh264/x86_64/19.08…
Verifying flathub:runtime/org.gnome.Platform/x86_64/3.34…
Verifying flathub:runtime/org.gtk.Gtk3theme.Ambiance/x86_64/3.22…
Verifying flathub:runtime/org.gnome.Platform.Locale/x86_64/3.32…
Verifying flathub:runtime/org.gnome.Platform.Locale/x86_64/3.34…
Verifying flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/19.08…
Pruning objects
Erasing .removed

$ flatpak update
Looking for updates…


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           594.2 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

$ flatpak install openh264
Looking for matches…
Found similar ref(s) for ‘openh264’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘runtime/org.freedesktop.Platform.openh264/x86_64/19.08’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           593.6 kB / 593.4 kB

Error: org.freedesktop.Platform.openh264 not installed
error: Failed to install org.freedesktop.Platform.openh264: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed

$ flatpak update
Looking for updates…


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.
```

**Comment by arderyp** [comment] 2019-09-27 02:08
```
UPDATING FLATPAK PACKAGES
Looking for updates…


        ID                                         Arch            Branch          Op         Remote          Download
 1. [✓] org.gnome.Platform                         x86_64          3.34            u          flathub           1.0 kB / 318.3 MB
 2. [✓] org.gnome.Platform.Locale                  x86_64          3.34            u          flathub           1.0 kB / 322.7 MB
 3. [✗] org.freedesktop.Platform.openh264          x86_64          19.08           i          flathub         593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Changes complete.
```

**Comment by arderyp** [comment] 2019-09-27 02:26
no one seems to know where or how to resolve this issue:

https://github.com/cisco/openh264/issues/3171
https://github.com/flathub/org.freedesktop.Sdk.Extension.node10/issues/4
https://forums.linuxmint.com/viewtopic.php?t=302122

**Comment by refi64** [comment] 2019-09-27 03:25
I'm not sure why you mentioned the node10 issue, I closed it because it has
nothing to do with the node10 repo...

**Comment by arderyp** [comment] 2019-09-27 03:38
Yeah @refi64, that's all well and good. My point is that lots of people seem to be experiencing this flatpak issue with openh264 and reporting it in various forums and repos at the same time, as was the case with the node10 issue i referenced (see the title), and yet no one in any of these venues seems to know what/where the problem is or how to resolve it.  

You're right that its not stemming from a problem within node10.  The question remains, what is causing this issue and how do we fix it?  In your opinion, is _this_ repo the correct place to address this problem?  If not, any ideas?

@ahayzen, can you post the output of `flatpak list`

**Comment by ahayzen** [comment] 2019-09-27 08:39
@arderyp this issue is tracking a different one to yours. This issue is tracking that flatpak gets confused when you have both the flathub and freedesktop test repo configured (openh264 from the freedesktop correctly installs but then it attempts to use the one from flathub).

Your issue initial is that openh264 needs at least flatpak version 1.0.9, 1.2.5, or 1.4.2 to install. You either need to update to 1.4.2 or later for it to work, or update to 1.0.9 or 1.2.5 and wait for the openh264 extension in flathub to be updated to state that it supports such versions (this is in the beta release right now and should make it into flathub over the next few days/weeks).

It appears you have then updated to 1.4.3 for the later comment, there was a different bug/irc discussion somewhere tracking that openh264 sometimes can't be installed even when the version is correct.

**Comment by ahayzen** [comment] 2019-09-27 08:41
(I think it is this issue that you are affected by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886 )

**Comment by arderyp** [comment] 2019-09-27 14:04
Thanks @ahayzen!

**Comment by Nokia808** [comment] 2019-09-28 04:44
Hi. I'm not sure that what I suffer from is related to this bug or not ! I received flatpak updates. I'm installing flatpak packages from FlatHub on my Fedora 30 X64 bit Cinnamon edition.

In this updates (& next updates including the last one that I performed just few minutes), I received the following on terminal:

```
$ flatpak update
Looking for updates…


        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
        ID                                   Arch   Branch Op Remote  Download
 1. [✓] org.gnome.Platform                   x86_64 3.34   u  flathub   2.3 MB / 318.4 MB
 2. [✓] org.gnome.Platform.Locale            x86_64 3.34   u  flathub  16.7 kB / 322.7 MB
 3. [✓] org.freedesktop.Platform.GL.default  x86_64 19.08  u  flathub  12.8 MB / 43.8 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel x86_64 19.08  u  flathub   1.9 kB / 8.7 MB
 5. [✗] org.freedesktop.Platform.openh264    x86_64 19.08  i  flathub 595.7 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Changes complete.
```

The line: "Warning: org.freedesktop.Platform.openh264 not installed"

**Comment by nanonyme** [comment] 2019-09-28 06:13
On flatpak side it would make sense to have better error if possible. Like was not installed due to missing runtime dependency.

**Comment by arderyp** [comment] 2019-09-28 06:21
@Nokia808, sounds like the issue I'm experiencing. Great user handle, btw.

**Comment by mielouk** [comment] 2019-09-29 09:25
This error is also present on my system – Arch, Flatpak 1.4.2

```
Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.
```

It got pulled by something, but I didn't install it explicitly.

**Comment by nanonyme** [comment] 2019-09-29 09:27
Please stop reportin metoo's. The root cause is known, you can ignore the warning for now.

**Comment by Erick555** [comment] 2019-09-29 11:48
If you want to workaround this error until it's fixed properly just run `flatpak install org.freedesktop.Platform//19.08`

**Comment by ahayzen** [comment] 2019-09-29 15:55
This issue is tracking an issue around having the same ref in two different repositories, which is not directly related to openh264 - I have renamed the issue to avoid confusion.

Please follow https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886 or other issues if you are having problems around installing openh264.

**Comment by discodis** [comment] 2019-11-14 11:20
> Note that this happened when the freedesktop repo has openh264 with the multiple minimum versions (1.0.9, 1.2.5, 1.4.2) and flathub doesn't. cc @alexlarsson this is the bug we discussed on IRC while i was testing flatpak 1.0.9.
> # What Happened
> 
>     1. Configure https://cache.sdk.freedesktop.org/releases/  and flathub as repositories
> 
>     2. Install an app from flathub that uses the freedesktop 19.08 runtime (eg Steam or Riot) and ensure the runtime comes from the freedesktop repo
> 
>     3. Notice that the openh264 extension is correctly installed
> 
>     4. Install an app from flathub that uses the GNOME 3.34 runtime (eg gedit)
> 
>     5. Notice that the openh264 extension has an update and fails to install (it thinks there is an update, but the update is actually the commit from the flathub repo, even though it says fdsdk - so even though it knows the repo name, the wrong commit from the wrong repo is being selected somehow).
> 
> 
> # What I expected to happen
> 
> At step 5 for the openh264 extension not to have an update, as the latest is already installed.
> # Log
> 
> This is the console output example of what happened https://pastebin.ubuntu.com/p/wN8VB2YkCb/

I had this same problem, and I solved it by gragando the official PPA sudo add-apt-repository ppa:alexlarsson/flatpak in this way I have everything fixed.

**Closed** 2021-11-15 10:18 UTC
