### ISSUE TITLE
End of life runtime warning without dependent application

### ISSUE THREAD

**Issue by Torbuntu** [flatpak/flatpak#4441] opened 2021-09-30 14:22 UTC
## Linux distribution and version
Fedora Silverblue 34 

## Flatpak version
1.10.2

## Description of the problem
An end of life runtime wants to be installed, but won't display why:
```
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
```
After installing the runtime anyway, upgrades now display a warning:
```
Looking for updates…
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Nothing to do.
```
It does not mention what is using it or requires it.

I have found that it is the `org.kde.Platform//5.14` runtime that needs it. 

## Steps to reproduce
Install an application that still uses the kde 5.14 runtime such as org.openmw.OpenMW.
See org.freedesktop.Platform.GL.default//19.08 required but not mentioning why on upgrades.

**Comment by vchernin** [comment] 2021-09-30 17:17
This sounds like https://github.com/flatpak/flatpak/issues/4369 and I've run into this as well...

It would definitely be helpful for Flatpak to tell you what runtime is bringing the EOL runtimes. And for that matter, KDE 5.14 should really be EOL as well: https://github.com/flathub/flathub/issues/2499

**Comment by mwleeds** [comment] 2021-10-08 21:53
duplicate of #3687

**Closed by mwleeds** 2021-10-08 21:53 UTC
