### ISSUE TITLE
Installation of Apps fails because of GPG Issues 

### ISSUE THREAD

**Issue by lpmmo4231** [flatpak/flatpak#1379] opened 2018-02-03 12:01 UTC
Hi, 

if I try to install an App from `flathub` or from somewhere else I get the following error message:

```
➜  ~ sudo flatpak install --user --from https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
Installieren: com.spotify.Client/x86_64/stable
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warnung: Problem bei der Suche nach zugehörigen Referenzen: GPG signatures found, but none are in trusted keyring
Error updating remote metadata for 'flathub': GPG signatures found, but none are in trusted keyring
Installing for user: com.spotify.Client/x86_64/stable from flathub
Fehler: GPG signatures found, but none are in trusted keyring
```
or 

```
➜  ~ flatpak install --from https://nuvola.tiliado.eu/eu.tiliado.Nuvola.flatpakref          
Installieren: eu.tiliado.Nuvola/x86_64/stable
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warnung: Problem bei der Suche nach zugehörigen Referenzen: GPG signatures found, but none are in trusted keyring
Error updating remote metadata for 'eu.tiliado.Nuvola-origin': GPG signatures found, but none are in trusted keyring
Installieren: eu.tiliado.Nuvola/x86_64/stable von eu.tiliado.Nuvola-origin
Fehler: GPG signatures found, but none are in trusted keyring
```
My flatpak version `0.10.2.1` and the system is Ubuntu Xenail 16.04.

How can I get rid of the GPG error without turning of the verification? I think I have to add the keys to the keyring but I don't know how. 

Thanks

**Comment by mwleeds** [comment] 2018-02-03 19:54
It should happen automatically I think but you could try to force it by adding the flathub repo (for the first one): `flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`

**Comment by mwleeds** [comment] 2018-02-05 01:28
Also you shouldn't use `sudo` with `flatpak --user`. It implies you want to work on the root user's flatpak installation.

**Comment by mwleeds** [comment] 2018-09-12 17:04
Duplicate of https://github.com/flatpak/flatpak/issues/1450

**Closed by mwleeds** 2018-09-12 17:04 UTC
