### ISSUE TITLE
Flatpak version of qBittorent installed ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1448] opened 2018-02-23 06:29 UTC
Hi,

I have moved to a flatpak version of qBittorent ... ever since, the magnet links and torrent files aren't working ... ideally clicking a magnet link or double clicking a torrent file should add the downloads to qBittorent.

when one clicks on a magnet link or double click on a torrent file, the add download window needs to be triggered ... but it isn't happening ... i am not sure if its an issue with flatpak system or the qBittorrent flatpak version problem !

thanks.

**Comment by TingPing** [comment] 2018-02-23 09:04
Could you pastebin the contents of `org.qBittorrent.qbittorrent` in flatpak's export dir?

**Comment by aiamuzz** [comment] 2018-02-23 09:22
FYI ... my flatpak apps are installed on a separate partition name 'Flatpak' the following is the path of the file you seek ... `/media/user/Flatpak/flatpak/exports/bin/org.qBittorrent.qbittorrent`

contents of the file `org.qBittorent.qbittorrent`
```
#!/bin/sh
exec /usr/bin/flatpak run --branch=stable --arch=x86_64 org.qBittorrent.qbittorrent "$@"
```

**Comment by TingPing** [comment] 2018-02-23 09:49
Sorry I meant `org.qBittorrent.qbittorrent.desktop`

**Comment by aiamuzz** [comment] 2018-02-23 10:02
no problem ... here you go ... i have deleted the various language name entries ...

```
[Desktop Entry]
Categories=Network;FileTransfer;P2P;Qt;
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=qbittorrent --file-forwarding org.qBittorrent.qbittorrent @@u %U @@
GenericName=BitTorrent client
Comment=Download and share files over BitTorrent
Icon=qbittorrent
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
Name=qBittorrent (Flatpak)
Terminal=false
Type=Application
StartupNotify=false
StartupWMClass=qbittorrent
Keywords=bittorrent;torrent;magnet;download;p2p;
Comment[oc]=Telecargar e partejar de fichièrs amb BitTorrent
GenericName[oc]=Client BitTorrent
;
;
;
Comment[oc]=Telecargar e partejar de fichièrs amb BitTorrent
GenericName[oc]=Client BitTorrent
Name[oc]=qBittorrent
Comment[af]=Aflaai en deel lêers oor BitTorrent
GenericName[af]=BitTorrent kliënt
Name[af]=qBittorrent
;
;
deleted other language entries
;
;
X-Flatpak=org.qBittorrent.qbittorrent
```

**Comment by TingPing** [comment] 2018-02-23 10:16
Well the `Exec` line looks correct. Since you opened #1449 that will be the source of your problem.

**Comment by alexlarsson** [comment] 2018-03-15 11:37
Yeah, this has the same root cause as #1449, closing this in favour of that.

**Closed by alexlarsson** 2018-03-15 11:37 UTC
