### ISSUE TITLE
Spotify flatpak facebook login issue

### ISSUE THREAD

**Issue by Izaic** [flatpak/flatpak#1668] opened 2018-05-11 20:13 UTC
## Linux distribution and version
Lubuntu 18.04

## Flatpak version
Flatpak 0.11.3

## Description of the problem
Cannot login to facebook in spotify flathub client.

(Debian and Snap version work fine)

## Steps to reproduce
Click facebook login or enter credentials.

[consoleoutput.txt](https://github.com/flatpak/flatpak/files/1996723/consoleoutput.txt)

**Comment by TingPing** [comment] 2018-05-11 22:06
Duplicate of https://github.com/flathub/com.spotify.Client/issues/36

**Closed by TingPing** 2018-05-11 22:06 UTC

**Comment by pycebs** [comment] 2018-05-25 13:59
I have the exact same problem. Just did a fresh Arch install and I'm using the flatpak version of Spotify. I cannot login via Facebook. If I try to signup via Facebook (just as a test), I get this error message:

A firewall may be blocking Spotify.

I'm not running a firewall, so there must be some sort of connection issue with the Facebook login. Console output doesn't show anything but fontconfig errors. Same as above.
