### ISSUE TITLE
"flatpak update" return errors about GPG verification

### ISSUE THREAD

**Issue by marcosps** [flatpak/flatpak#871] opened 2017-06-27 02:01 UTC
Version: 0.9.5 (Fedora 25)
Command: flatpak update
Output:
[marcos@xfiles ~]$ flatpak update -y
Looking for updates...
Updating: org.gnome.Sdk.Locale/x86_64/master from gnome-nightly
[####################] 1 metadata, 0 content objects fetched; 313 B transferred in 1 seconds
Warning: Failed to update org.gnome.Sdk.Locale/x86_64/master: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: GPG verification enabled, but no summary signatures found
Updating: org.gnome.Sdk/x86_64/master from gnome-nightly
[####################] 4 delta parts, 1 loose fetched; 609 KiB transferred in 14 seconds
Error: Failed to update org.gnome.Sdk/x86_64/master: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: GPG verification enabled, but no summary signatures found
error: One or more operations failed

**Comment by aditiapratama** [comment] 2017-06-27 04:47
I tried with `sudo` and everything is good

**Comment by jakunar** [comment] 2017-06-27 09:08
I can second both of you.
However, just because `sudo` works doesn't mean it's good.

When everything updates smoothly I tend to no longer pay attention to neither the updating progress nor what is being updated. So I can't tell right now what messed up the DBus authentication, but it probably was an update of Fedora 25.

**Comment by alexlarsson** [comment] 2017-06-28 08:25
Duplicate of #860

**Closed by alexlarsson** 2017-06-28 08:25 UTC
