### ISSUE TITLE
Cursor Scaling on HiDPI Display

### ISSUE THREAD

**Issue by ryanleesipes** [flatpak/flatpak#740] opened 2017-04-27 00:07 UTC
I'm not sure why, but Flatpak apps do not respect cursor scaling on HiDPI displays. I'm not sure why this problem happens, but the rest of the application seems to be scaling properly. This is using X, and is observable across Builder and Spotify (for Spotify it persists even after scaling is set at the application level). So, I've only observed this behavior with Flatpak applications:

Not sure how to take a screenshot of the cursor, the default GNOME screenshot tool removes the cursor from a shot as far as I can tell. The cursor appears to be half-size on these applications.

**Comment by matthiasclasen** [comment] 2017-04-27 00:29
which apps are these ? what runtimes are they using ?

a random guess: maybe the runtime does not have a suitable cursor theme with bigger cursors

**Comment by ryanleesipes** [comment] 2017-04-27 00:51
GNOME Builder 3.24 and Spotify (whatever is on the apps page on the Flatpak.org website). 

I went ahead and installed FeedReader via the Flakpakref on the website. Same problem there. I assume since I am using builder 3.24, it is the 3.24 runtime. How do I check @matthiasclasen ?

**Comment by matthiasclasen** [comment] 2017-04-27 01:26
If you have a recent flatpak, you can run

flatpak info --show-metadata org.gnome.Builder

and that will show you the runtime that is used (among many other things).

If your flatpak doesn't know --show-metadata yet, you can do this instead:

flatpak run --command=sh org.gnome.Builder

and, at the prompt,

cat /.flatpak-info

**Comment by ryanleesipes** [comment] 2017-04-27 21:07
The second set of commands worked.

`runtime=runtime/org.gnome.Sdk/x86_64/3.24`

**Comment by matthiasclasen** [comment] 2017-04-27 23:53
ok. in that case, you should have a suitable cursor theme available inside the runtime.

**Comment by ryanleesipes** [comment] 2017-05-01 23:55
@matthiasclasen does this mean I need to add one there? Or is this something that doesn't exist in the runtime as is and we can add as part of Flatpak's runtimes.

**Comment by matthiasclasen** [comment] 2017-05-02 00:35
So far it just means that my first theory about this is wrong. Needs some debugging, if I can get my hands on a hi-dpi display

**Comment by alexlarsson** [comment] 2017-05-02 14:04
It seems to work fine for me with gnome-builder, but I can reproduce with spotify, if i start with `flatpak run com.spotify.Spotify --force-device-scale-factor=2` then everything is scaled but the cursor.

**Comment by alexlarsson** [comment] 2017-05-02 14:09
I believe that is because spotify is using the freedesktop.org runtime without an icon theme.
That will hopefully be solved when we start packaging up icon themes.

But, for the record, what icon theme are you using, and when you get tiny cursors, are they the ancient non-rgba X11 cursors?

**Comment by alexlarsson** [comment] 2017-05-02 14:37
I updated spotify to be based on the gnome runtime (needed for some other dependencies like zenity anyway). Now hidpi cursors work for me with adwaita at least. Can you try it?

**Comment by ryanleesipes** [comment] 2017-05-03 21:11
Yeah, I'll try it, thanks @alexlarsson

**Comment by ryanleesipes** [comment] 2017-05-03 21:13
@alexlarsson I updated via Flatpak, but it didn't pull down a new Spotify release. Anything special I need to do?

**Comment by alexlarsson** [comment] 2017-05-04 06:52
Oh, its not a new spotify release per se, but a new version of the spotify package. Did it not get that?

**Comment by alexlarsson** [comment] 2017-05-04 06:52
the spotify flatpak that is.

**Comment by matthiasclasen** [comment] 2017-05-04 09:55
This is what I get after updating:

flatpak ./flatpak info com.spotify.Client
Ref: app/com.spotify.Client/x86_64/master
ID: com.spotify.Client
Arch: x86_64
Branch: master
Origin: com.spotify.Client-origin
Commit: 4f93a78fe573e398333868446c554474fd9a78c71063d8fd363792b26e900443
Location: /var/lib/flatpak/app/com.spotify.Client/x86_64/master/4f93a78fe573e398333868446c554474fd9a78c71063d8fd363792b26e900443
Installed size: 10.9 MB
Runtime: org.gnome.Platform/x86_64/3.24

**Comment by matthiasclasen** [comment] 2017-05-04 10:03
Yet, no large cursors here, with --force-device-scale-factor=2

I do notice that if I run the flatpak from a jhbuild shell, XCURSOR_PATH leaks into the environment. But unsetting that does not change things

**Comment by matthiasclasen** [comment] 2017-05-04 10:05
I do see the following now:

/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)

but that doesn't keep spotify from running

**Comment by alexlarsson** [comment] 2017-05-04 12:04
Yeah, the warning is because its some debian package and we don't have symbol versions in our libcurl that debian has.

**Comment by ryanleesipes** [comment] 2017-05-04 19:43
This is what I get from flatpak info com.spotify.Client:

app/com.spotify.Client/x86_64/master com.spotify.Client-origin 121ec01acc2b061d27fda92fbc1eb93618baac48efbd1fe16d56b76d0f8bce48

**Comment by alexlarsson** [comment] 2017-05-05 10:28
@ryanleesipes Thats not the latest. Try flatpak update com.spotify.Client

**Comment by alexlarsson** [comment] 2017-05-05 10:31
Also, i talked a bit with @matthiasclasen and we figured out why we're getting different results. I'm running on an actual HiDPI screen (w/ X11) while he is on a LoDPI screen but just forcing the scaling. Maybe the scale factor for cursors is picked based on something else than the --force-device-scale-factor argument.

**Comment by alexlarsson** [comment] 2017-05-05 10:36
Another thing: When i ran under jhbuild the spotify inherited
```
declare -x XCURSOR_PATH="/gnome/share/icons"
```
in the environment, which is not accessible from the sandbox, and caused a return to core X11 cursors.

**Comment by ryanleesipes** [comment] 2017-05-09 16:56
@alexlarsson is there anyway to make that a part of core Flatpak? ^

Would there be a drawback to doing so?

**Comment by alexlarsson** [comment] 2017-05-19 11:06
@ryanleesipes Make what a core part of it? clearing the XCURSOR_PATH?

**Comment by SeerUK** [comment] 2017-07-16 10:00
Hey there, is there any update to this? I'm using Spotify on a 4K display, making my cursor pretty tiny when it's over the Spotify window. I believe I'm running the latest everything (since I've only just got it up and running). I've tried to run it with a few environment variables to no avail.

**Comment by daenney** [comment] 2017-12-18 09:56
I just wanted to chime in and let you know that for me, this works as expected with the Spotify build from Flathub. I had to edit the `com.spotify.Client.desktop` entry to add the `--force-device-scale-factor=2` at the end of the `Exec` line, but other than that it works.

It would be great if this could be autodetected though, otherwise I find mysefl staring a rather tiny font and pointer.

**Comment by Barafu** [comment] 2019-03-21 19:13
I am pinging this bug because it is biting me right now. 
I have a real 4k monitor. Linux Mint, default theme and everything. For example, if I use FileZilla flatpak, then, when mouse pointer is hovering above grey areas of the window (toolbars), it is white and big, exactly like the system pointer. But when it hovers above white portions of the window, the cursor is tiny and black.

**Comment by Barafu** [comment] 2019-03-21 19:26
I am pinging this bug because it is biting me right now. 
I have a real 4k monitor. Linux Mint, default theme and everything. Flatpak 1.3.0. For example, if I use FileZilla flatpak, then, when mouse pointer is hovering above grey areas of the window (toolbars), it is white and big, exactly like the system pointer. But when it hovers above white portions of the window, the cursor is tiny and black.

**Comment by bacher09** [comment] 2019-06-22 18:25
Here's workaround that solved issue for me:

    mkdir ~/.local/cursors/
    cp -r /usr/share/cursors/* ~/.local/cursors/
    flatpak override --user --env=XCURSOR_PATH=~/.local/cursors/xorg-x11/ --filesystem=~/.local/cursors:ro

After this `flatpak override --user --show` should return something like this:

```
[Context]
filesystems=~/.local/cursors:ro;

[Environment]
XCURSOR_PATH=~/.local/cursors/xorg-x11/
```

**Comment by bacher09** [comment] 2019-09-26 13:43
Recently my workaround stopped working for QT applications. I debugged it little bit and found out that it's caused by qgnomeplatform plugin, more precisely by this [change](https://github.com/FedoraQt/QGnomePlatform/commit/8270d9b96e053c0dd1e82ca4152cc0242ab158bf#diff-86bd2408aefbd1736d488207045cfd2bR213).

**Comment by grulja** [comment] 2019-09-27 11:39
> Recently my workaround stopped working for QT applications. I debugged it little bit and found out that it's caused by qgnomeplatform plugin, more precisely by this [change](https://github.com/FedoraQt/QGnomePlatform/commit/8270d9b96e053c0dd1e82ca4152cc0242ab158bf#diff-86bd2408aefbd1736d488207045cfd2bR213).

Is this on wayland or X session?

**Comment by bacher09** [comment] 2019-09-27 12:20
On X session.

**Comment by bacher09** [comment] 2019-09-27 12:34
Basically it reads `cursor-size` property which is for my case is 24, and completely ignores `scaling-factor`, which is 2 on my system (so correct `XCURSOR_SIZE` should be 48). Moreover, since it isn't checking `XCURSOR_SIZE` environment variable, there is no way I can override this behavior.

When I edit that commit and  recompiled `org.kde.PlatformTheme.QGnomePlatform` using my modification everything started to works as expected (same cursor size in flatpak apps as with regular ones).

**Comment by grulja** [comment] 2019-09-27 14:26
I pushed fix to upstream and Flathub. Can you try once it builds and you get an update?

**Comment by bacher09** [comment] 2019-09-27 15:21
Build seems to be already [done](https://flathub.org/builds/#/builders/32/builds/8984), but `flatpak update` does not report any updates. Also build of 5.12 strangely reports 5.13 in it's logs: 

```
Committing ref runtime/org.kde.PlatformTheme.QGnomePlatform.Sources/x86_64/5.13 (db4b4ede1911f98ade9654fe2ae8851ef27c7d2326f1ee9801286025b99a9b13)
| Committing ref runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/5.13 (413fc3096efe3d9924746716e53c59161a3b1f11c0d02ef1de8eb5502529bc68)
| Committing ref runtime/org.kde.PlatformTheme.QGnomePlatform/arm/5.13 (a044429bba8c4716a6663eb0b804e77bdeff70280becbafa883788e5ee84e57b)
| Committing ref screenshots/x86_64 (2e790901edeb030b1b0677be155881218a8caf84ded23061c9a34584bc4cc8c7)
| Committing ref screenshots/arm (a4ef511ee8432a23333dcabfc1f1cb9d83d4b1349a5c8128136f967824acfa2d)
| Committing ref screenshots/aarch64 (c1e2d57b7feed72ecda18ee33bade39c7899c65b28de9619d3eb097e9ed75e02)
| Committing ref runtime/org.kde.PlatformTheme.QGnomePlatform/aarch64/5.13 (10b6dd3d2ebf83b3f1ba5638d564495f234588022658129da86761dba26baff9)
```

And in source report branch tagged as 5.12 has [this](https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/blob/branch/5.12/org.kde.PlatformTheme.QGnomePlatform.json#L3).
Is it supposed to be like this ?

**Comment by grulja** [comment] 2019-09-27 16:11
Ooops, sorry, I merged 5.13 into 5.12 without realizing it would change version of runtime. I pushed a new build.

**Comment by bacher09** [comment] 2019-09-27 17:10
Just updated, and yes indeed now cursor have a regular size just like in other apps.

**Comment by grulja** [comment] 2019-09-27 17:31
> Just updated, and yes indeed now cursor have a regular size just like in other apps.

Perfect, thank you for your help.

**Closed** 2019-12-02 05:03 UTC

**Comment by vincentbernat** [comment] 2020-04-11 18:45
Could this issue be reopened? It seems that without using some workaround with `XCURSOR_PATH`, cursor size does not work out of the box. I am seeing the issue with Firefox, Spotify and Zoom. All of them are using the freedesktop platform. I have a 4K screen and the cursor when over these application is tiny.

From XSettings:

```
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 0
```

Inside the container, I see `/run/host/share/icons/Adwaita/cursors` exists. If I use `XCURSOR_PATH=/run/host/share/icons firefox` inside the flatpak container, this doesn't work either. However, if I use `XCURSOR_THEME=Adwaita firefox`, it works fine. So, I am puzzled. How does flatpak exposes GTK settings? Is there a proxy for XSettings?

**Comment by memeplex** [comment] 2020-04-24 21:23
I'm having this issue in Spotify in Ubuntu 20.04.

Is this supposed to work out of the box or to be fixed by each Snap packager on a case by case basis?

**Comment by qiyoulu** [comment] 2020-05-06 18:18
I have the same issue with all my Flatpaks and Snaps on both Fedora 32 GNOME and Ubuntu 20.04 GNOME.

**Comment by memeplex** [comment] 2020-05-06 18:27
@matthiasclasen should this be reopened?

**Comment by typkrft** [comment] 2020-05-25 06:10
I'm also having this issue.

**Comment by shaicoleman** [comment] 2020-11-04 10:18
On Linux Mint 20, the following solved it for me:
```sudo flatpak override --env XCURSOR_THEME=DMZ-White```

**Comment by hholst80** [comment] 2022-09-25 10:15
2022 calling in. still an issue with HiDPI and mouse cursor size.

**Comment by LorbusChris** [comment] 2022-10-13 16:33
ref https://github.com/flatpak/flatpak/issues/5114

**Comment by fastrizwaan** [comment] 2022-11-08 10:33
freedesktop sdk 22.08
https://github.com/flathub/io.mpv.Mpv/issues/112

**Comment by r14c** [comment] 2024-04-06 17:49
I"m seeing the same issue on DeltaChat 1.44.1 running in Flatpak 1.15.6 on Fedora 39 (KDE Spin)

![Screenshot_20240406_104802](https://github.com/flatpak/flatpak/assets/95627/7d635e62-3fbe-406b-953c-d10e5a689b8f)

For reference, my system cursor is about as tall as the UI icons shown at the top right.

**Comment by iGadget** [comment] 2024-10-14 11:58
Running into this with Thunderbird 128.3.1esr (flatpak) on Ubuntu 24.04 (using Wayland), 125% scaling.
Since the proposed workarounds are several years old (and mostly for X11), which route should I be taking to debug / fix this?

**Comment by moving-bits** [comment] 2025-02-26 08:07
Similar issue here with AndroidStudio running as Flatpak on Linux Mint 22.1, using X11, and screen scaling set to 125% - cursor is nearly invisible within AndroidStudio, but fine outside.

**Comment by salim-b** [comment] 2025-03-07 23:41
Is [this](https://github.com/flathub/im.riot.Riot/blob/a1c201775f7dd1d447488dd9d1fbbbf5d0b0fdfc/im.riot.Riot.yaml#L33-L34) the current best practice to make the mouse cursor scale correctly on a HiDPI display under Wayland?

```yaml
  # For correct cursor scaling under Wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
```
