### ISSUE TITLE
[Feature request] Support user mode networking

### ISSUE THREAD

**Issue by hexchain** [flatpak/flatpak#3404] opened 2020-02-03 15:42 UTC
Currently, apps inside Flatpak can either use the whole host networking stack or have completely no connectivity. It could be useful if Flatpak can set up a user-mode networking interface and pass it into the isolated network namespace, with tools like [slirp4netns](https://github.com/rootless-containers/slirp4netns). This lets applications access the Internet as usual but they are not able to bind to any port or see any other interfaces on the host.

I came up with this idea while trying to package a proprietary online storage client, which picks an interface upon start and tries to connect to the Internet from that specific interface. The problem is that it usually picks the wrong one when I have some VPNs connected, and when this happens it is unable to connect to the Internet.

**Comment by mwleeds** [comment] 2020-02-03 17:56
Seems like a duplicate of #1202

Can you comment there instead?

**Closed by mwleeds** 2020-02-03 17:56 UTC

**Comment by hexchain** [comment] 2020-02-03 18:07
Thanks for the hint. While I don't think it's completely duplicate, I agree these two issues may be merged.
