### ISSUE TITLE
Annoying output related to locale when starting Octave via flatpak (GtK-Message: Locale not supported by C library)

### ISSUE THREAD

**Issue by DrChr** [flatpak/flatpak#3563] opened 2020-04-18 06:23 UTC
## Linux distribution and version
Ubuntu 18.04 LTS

## Flatpak version
Flatpak 1.0.9

## Description of the problem
I'm calling a program (Octave) via flatpak that results in this annoying message

```
(process:2): Gtk-WARNING **: 15:30:30.182: Locale not supported by C library.
	Using the fallback 'C' locale.
```

when executing ```flatpak run org.octave.Octave --eval "fprintf('Hello\n');"```.

The full output is as follows:

```
flatpak run org.octave.Octave --eval "fprintf('Hello\n');"

(process:2): Gtk-WARNING **: 08:32:58.721: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 08:32:58.755: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:32:58.755: Failed to load module "canberra-gtk-module"
Hello
```

I do not get this output if I directly call the locally installed program.

Note: See issue #3521 for an issue tracking the other annoying output related to the missing "canberra-gtk-module".

_Background_: I'm using flatpak to call the program as part of a build process, and the extraneous messages are cluttering my logs so I'd like to get rid of them.

## Steps to reproduce

See example above.

## Related issues

See issue #3521 for an issue tracking the other annoying part of the output.

There's also issue #147.

## Workaround

Launch Octave using flatpak as follows instead:

```
$ LC_ALL=C flatpak run org.octave.Octave --version
```

### Locale inside flatpak

```
$ flatpak run --command=/bin/sh org.octave.Octave 
sh-5.0$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

### Local locale

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

### Other info

```
$ flatpak info org.kde.Platform.Locale
Ref: runtime/org.kde.Platform.Locale/x86_64/5.14
ID: org.kde.Platform.Locale
Arch: x86_64
Branch: 5.14
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2020-04-14 20:53:11 +0000
Subject: build of org.kde.Sdk, Tue Apr 14 13:36:22 UTC 2020 (36e0886be07fb546ad432b54ff108364737f3dee)
Commit: ee3faaf711dcb3419d89af80b97c9a20b67206fdbc5d43e162ac95de2925f45f
Parent: ca0f29c1b41ce1cc67489bf3b0ec3fac1919d729f7685e225feda3b7f0ba0016
Location: /home/chr/.local/share/flatpak/runtime/org.kde.Platform.Locale/x86_64/5.14/ee3faaf711dcb3419d89af80b97c9a20b67206fdbc5d43e162ac95de2925f45f-en
Installed size: 512 bytes
Installed subdirectories: /en
```

## Speculation

The problem is due to my local system using a combination of English and Swedish, making flatpak confused. As seen in the section above, it only has ```/en``` installed.

However, as per initial discussion in #3521, I tried without success the following steps 
- Run ```flatpak config --set languages "sv;en"```
and then
- Run ```flatpak update```
- Run ```flatpak info org.kde.Platform.Locale//5.14```

**Comment by DrChr** [comment] 2020-04-18 06:52
Additional info:
If I do ```ssh -X``` to my own computer and call Octave via flatpak I do not get the annoying messages:

```
$ flatpak run org.octave.Octave --eval "fprintf('Hello\n');"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
Hello
```

There is however instead the message about X11 display variable not being set.
That's due to some other issue with flatpak and/or the Octave package as far as I know though.

**Comment by abderrahim** [comment] 2020-04-18 09:31
If setting the language doesn't work, you would need to remove the locale extension and before running `flatpak update` so that it is reinstalled correctly (with both languages).

The "annoying messages" depend on your environment. So if you don't have mixed locale settings when logging in via ssh, then it's natural you don't see the error.

**Comment by mcatanzaro** [comment] 2021-04-06 12:29
Proposal: mark this as a duplicate of #3712, which is the same issue but with more discussion.

**Closed** 2021-09-13 00:20 UTC
Labels: duplicate
