### ISSUE TITLE
MX Package Installer fails to install flatpaks

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#2751] opened 2019-03-10 19:49 UTC
## Linux distribution and version
- [x] MX 18.1
## Flatpak version
- [x] 1.0.1-1
## Description of the problem
- [x] via logs: `2019/03/10 15:05:20 socat[30910] E parseopts(): unknown option " in-app code editing & issue tracking."`
- [x] The above output is from (attempting) to install Gitkraken via MX's baked-in Flatpak repository (Flathub), which I've done so in the past without a hitch.
- Bitwarden is also not installing.
The following have installed smoothly sometime within 3-6 months ago (I apologize I cannot be more precise.
1. Signal
2. Nextcloud Desktop Sync
3. Atom
... I'm sure I've installed a few more packages, though combing through the list of everything on my system is not something I feel like doing at the moment. I doubt it matters for this report.
- What was happening a few days ago was the installations would auto-answer `n` after reaching the end of their downloads and installations. That, I do not have logs for. Even with the space I've partitioned for logs (in general, including those from Flatpak), I clean (now not so) unnecessary logs, keeping mostly those from iptables and other security/intrusion-related tools. 
## Steps to reproduce
1. Install MX 18.1 (max 20 minutes time)
2. Open `MX Package Installer` which contains the Flatpak repo.
3. Search for Gitkraken; click on `install`.
4. Repeat for Bitwarden.
5. View either the console logs built in to `MX Package Installer` or the verbose output in the system logs.
- In the meantime, I'll try installing a minimum of 20 packs and return to edit this to let you know of any success I may have.
Thank-you for your time,
- intr0

**EDIT**
I returned to where I'm most comfortable, the command line. To help anyone who may see this closed issue: https://github.com/flatpak/flatpak/issues/2670#issue-405485497 instead of using `flatpak remove --unused ` use the `flatpak repair` command.

Now, onto the simpliest fix there is to non-functioning GUIs. Using `flatpak install` to download and install Gitkraken worked flawlessly, and so much faster than any GUI blocking the way to what is *actually* happening during Flatpak's processes.

- term output:
```
intr0@mx:~
$ flatpak install gitkraken
Looking for matches…
Remotes found with refs similar to ‘gitkraken’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 2
Found ref ‘app/com.axosoft.GitKraken/x86_64/stable’ in remote ‘flathub’ (user).
Use this ref? [Y/n]: y

com.axosoft.GitKraken permissions:
    ipc       network              ssh-auth             wayland       x11
    dri       file access [1]      dbus access [2]      tags [3]

    [1] host
    [2] org.freedesktop.secrets
    [3] proprietary


        ID                             Arch            Branch          Remote           Download
 1. [✓] com.axosoft.GitKraken          x86_64          stable          flathub          287.0 MB / 293.2 MB

Installation complete.
```
Beyond the GUI issue MX is having, everything is running smoothly.
- Peace

**Comment by mwleeds** [comment] 2019-03-11 22:08
If this issue only occurs in "MX Package Installer" maybe a bug report should be opened against that, unless or until it's clear that this is Flatpak's fault?

**Comment by DNSCrypt-Lists** [comment] 2019-03-11 23:51
@mwleeds If it for some reason does not resolve, and only the command line functions, then it will most likely be an issue to report here. Regardless, I did return to edit my post with additional information explaining exactly the fact the command line, obviously, works. So while I was in no way faulting anyone as responsible for this ongoing occurrence, I do agree that it’s as of yet unclear as to the cause of the problem. Now, while you **may** reason that my use of a distro popular with many Linux novices, and your reasoning leads you to assume the same of me, both that possible assumption and your reasoning are false. You’ll understand in about 30 years why I’d prefer a simpler distro to maintain relative to the 1990’s. If I see that the person who left the rude comment in response to my other post, I’ll predict at that point that Flatpak as a Corporate entity won’t last very long. Treat those doing what they can to help Flatpak **for free** with kindness. Peace.

**Comment by mwleeds** [comment] 2019-03-12 20:06
@ghost this is either a bug in the way MX Package Installer is using the libflatpak API, or it's a bug in libflatpak. That's the question we need to answer, so that's why I suggested opening a bug report against that software.

But since you deleted your GitHub account I guess I'll assume there won't be further progress and close this.

**Closed by mwleeds** 2019-03-12 20:06 UTC
