### ISSUE TITLE
I can not input Chinese(zh-cn) within shotcut

### ISSUE THREAD

**Issue by yichuang-zh** [flatpak/flatpak#3201] opened 2019-10-29 02:52 UTC
Debian Stretch 9.11 /Gnome
Flatpak 1.2.4
I can not input Chinese(zh-cn) within shotcut

Open shotcut installed from flathub, put a clip on the timeline, then open the filter tab, click the button of "Add a filter", select "Video > Text: Simple", click the "Text" edit area, press Ctrl+Space to switch to Chinese input method fcitx, but the fcitx did not appear. I can't input Chinese, I can only input English.

**Comment by mwleeds** [comment] 2019-11-08 18:36
Duplicate of https://github.com/flatpak/flatpak/issues/2031 ?

**Comment by yichuang-zh** [comment] 2019-11-10 09:12
I have read the contents of your prompt #2031 .
It seems that the problem described by #2031 is the same as the problem I am having.

Thanks you.

**Closed** 2019-11-10 16:50 UTC
