### ISSUE TITLE
[Bug]: failed to install runtime/org.freedesktop.Platform.openh264/x86_64/2.0: Wrong size for extra data

### ISSUE THREAD

**Issue by zengmor** [flatpak/flatpak#4544] opened 2021-11-07 09:37 UTC
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.1

### What Linux distribution are you using?

Manjaro Linux

### Linux distribution version

5.13.19-2-MANJARO

### What architecture are you using?

x86_64

### How to reproduce

1. install a manjaro gnome edition and keep it up to date.
2. use pacman to install flatpak and then use flatpak to install openh264.

### Expected Behavior

the installation of org.freedesktop.Platform.openh264 should succeed and took a only a few seconds.
```bash
flatpak install org.freedesktop.Platform.openh264
```

### Actual Behavior

I got the following message:

```
Looking for matches…
Remotes found with refs similar to ‘org.freedesktop.Platform.openh264’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)
   3) ‘gnome-nightly’ (user)

Which do you want to use (0 to abort)? [0-3]: 1
Similar refs found for ‘org.freedesktop.Platform.openh264’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Platform.openh264/x86_64/2.0
   2) runtime/org.freedesktop.Platform.openh264/x86_64/19.08

Which do you want to use (0 to abort)? [0-2]: 1


        ID                                Branch Op Remote  Download
 1. [✗] org.freedesktop.Platform.openh264 2.0    i  flathub 1.0 kB / 1.5 MB

Error: Wrong size for extra data http://ciscobinary.openh264.org/libopenh264-2.1.1-linux64.6.so.bz2
error: Failed to install org.freedesktop.Platform.openh264: Wrong size for extra data http://ciscobinary.openh264.org/libopenh264-2.1.1-linux64.6.so.bz2
```

### Additional Information

I am not sure if this is a problem of flatpak or openh264, I have found a "wrong size for extra data" issue  #3954 that says this could have something to do with openh264.

**Comment by mwleeds** [comment] 2021-11-08 17:00
This is probably a duplicate of #4415 and if so will be fixed by #4430

**Closed** 2022-02-10 10:51 UTC
Labels: bug
