### ISSUE TITLE
After/Before custom filemanager opens up, it "crashes"

### ISSUE THREAD

**Issue by JeremyStarTM** [flatpak/flatpak#3990] opened 2020-11-25 19:57 UTC
## Linux distribution and version
/proc/version:
Linux version 5.4.0-54-generic (buildd@lcy01-amd64-024) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))
neofetch:
OS: Ubuntu 20.04.1 LTS x86_64
Kernel: 5.4.0-54-generic
DE: Plasma
WM: KWin
WM Theme: Big Sur Dark
Theme: Breeze Dark [Plasma], Breeze [GTK3]
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3]
CPU: Intel Core 2 Quad Q9400 (4) @ 2.664GHz
GPU: AMD ATI Radeon HD 7850 / R7 265 / R9 270 1024SP
Memory: 7961MiB
## Flatpak version
Flatpak 1.6.5
## Description of the problem
If i open Shotcut or some program that has an own file manager (like Shotcut has) or an already existing one (like nautilus) sometimes i can select something and after i selected it it "crashes" or the file manager pops up (or not) and it "crashes". And with "crashes" i mean that i can't do anything and the only solution is to get it away is kill it.
## Steps to reproduce
Download shotcut and create a project. Save it and then export the project. It produces no files, it just "crashes". See what happens and if nothing happens after it opened the file manager, close it again.

Tested on my computer and in a virtual machine with Kubuntu 20.04 fresh installed.

**Comment by JeremyStarTM** [comment] 2020-11-25 20:00
Edited because i checked it _after_ i posted this issue

**Comment by JeremyStarTM** [comment] 2020-11-25 20:03
I was stupid, first i checked the issue, but i made an mistake and edited it again. 🤦🏼

**Comment by mwleeds** [comment] 2021-11-18 03:24
Closing this since it's from an old OS version and no one said they could reproduce

**Closed by mwleeds** 2021-11-18 03:24 UTC

**Comment by JeremyStarTM** [comment] 2022-01-19 22:16
@mwleeds No problem. Since did some distro hopping and it works now.
