### ISSUE TITLE
GPG signatures found, but none are in trusted keyring winepak

### ISSUE THREAD

**Issue by bibiyanki** [flatpak/flatpak#2138] opened 2018-09-26 07:19 UTC
## Flatpak version= i don't know maybe last
hello
i follow step for add reposetory of winepak, i think it's work because it don't tell nothing and return to the line
and when i try install app or just see list, it tell me
flatpak remote-ls winepak
error: GPG signatures found, but none are in trusted keyring

what's wrong
thank u

**Comment by mwleeds** [comment] 2018-09-26 18:44
Duplicate of https://github.com/flatpak/flatpak/issues/1450

**Closed by mwleeds** 2018-09-26 18:44 UTC
