### ISSUE TITLE
When renaming a desktop file, flatpak-builder should also add StartupWMClass

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#321] opened 2016-09-22 19:31 UTC
flatpak-builder has this handy feature of renaming the desktop file to the reverse DNS scheme.

However, once it does that the WM class doesn't match the desktop file name any more.

This causes weird bugs like org.gnome.Calculator (for which the desktop file currently gets renamed from gnome-calculator) being grouped together with unrelated apps in the GNOME Shell alt-tab menu.

**Comment by bochecha** [comment] 2016-09-22 19:36
Blender grouped under Polari:

![blender-and-polari](https://cloud.githubusercontent.com/assets/272170/18763090/1478b598-810c-11e6-990c-be0f48f4292d.png)

That's because the Blender window has `WM_CLASS(STRING) = "Blender", "Blender"` (taken from `xprop`).

Setting `StartupWMClass=Blender` in `~/.local/share/flatpak/exports/share/applications/org.blender.app.desktop` gets Blender under its own app icon in the Shell alt-tab menu.

**Comment by alexlarsson** [comment] 2016-09-27 13:09
> That's because the Blender window has WM_CLASS(STRING) = "Blender", "Blender" (taken from xprop).

Why is that a problem, and what is the polari WM_CLASS?

**Comment by bochecha** [comment] 2016-09-27 13:12
Polari has `WM_CLASS(STRING) = "org.gnome.Polari", "Org.gnome.Polari"`

I was told by halfline and fmuellner on IRC that GNOME Shell has some heuristics to track applications, and part of that is that the `WM_CLASS` should match the desktop file id, unless the desktop file contains a `StartupWMClass`.

**Comment by alexlarsson** [comment] 2016-09-27 13:14
That may be true, but it doesn't mean you can always set StartupWMClass to whatever without breaking things.

**Comment by bochecha** [comment] 2016-09-27 13:17
Fair enough. I discovered this stuff for the first time last week, and opened this bug report following the advice of halfline and fmuellner.

I'm happy to admit that I can be wrong here. :smile: 

What would be the right way to fix the issue, then?

**Comment by alexlarsson** [comment] 2016-09-27 13:17
I don't get why gnome-shell combines blender and polari though? We renamed the blender desktop file, so it may not be able to match the WM_CLASS to a desktop file, but it should not combine it with something else. And polari *does* set its app id as the WM_CLASS (due to being gjs), so in particular, it should not combine with that.

**Comment by bochecha** [comment] 2016-09-27 13:20
Like I said in the pull request, GNOME Shell combines it only with the flatpak app that last had the focus. It does not combine it with a non-flatpak app (e.g from a fedora RPM).

Part of the app tracking heuristics is the pid, which is the same for all flatpak apps (pid = 2 inside the container). Could that cause the grouping?

**Comment by alexlarsson** [comment] 2016-09-27 13:20
There is a general movement in the linux desktop to rename the desktop files to the dbus name. For instance, my nautilus desktop file is called "org.gnome.Nautilus.desktop", and it sets a WM_CLASS of "nautilus". This doesn't seem to cause any problems to the shell. So i wonder how the two are different?

**Comment by alexlarsson** [comment] 2016-09-27 13:29
Could be the pid=2 for all of them. Or maybe the fact that all .desktop files has Exec=flatpak ... in them?
 @fmuellner: Got any ideas?

@bochecha Can you try adding --class=org.gnome.Calculator arguments when running the app?

**Comment by alexlarsson** [comment] 2016-09-27 13:41
Ok. I reproduced this here. So, if i run a flatpak that has a "correct" WM_CLASS (i.e. matching its desktop name) such as org.gnome.Polari , and then i run org.gnome.Calculator (WM_CLASS gnome-calculator) *and* I removed any system-wide gnome-calculator.desktop file, then the calculator window gets matched to polari.

This isn't great in the long run, because pid-reuse can accidentally happen in other cases too, and we're moving away from naming the desktop files after argv[0] and moving towards using the dbus names, even in the non-flatpak case.

**Comment by bochecha** [comment] 2016-09-27 14:21
> Can you try adding --class=org.gnome.Calculator arguments when running the app?

flatpak doesn't recognize this option.

**Comment by alexlarsson** [comment] 2016-09-27 15:04
So. I think the most generic solution is: if the old desktop file name matches the executable, then add a symlink to the binary with the app is as name and launch that one instead.

**Comment by bochecha** [comment] 2016-09-27 15:29
> with the app is as name

Did you mean the app i**d**?

(I think that's what you mean, but I'd rather make sure, if I'm going to send a patch :stuck_out_tongue: )

**Comment by halfline** [comment] 2016-09-27 15:29
I think what we need is a d-bus api in the flatpak session helper that says "What app started this pid?" then gnome-shell can use XResQueryClientIds to find the pid of any given window, and then know how to match it reliably.

**Comment by alexlarsson** [comment] 2016-09-27 16:06
Yeah. App id.

**Comment by alexlarsson** [comment] 2016-09-27 16:08
@halfline you can already get the app id from the pid via /proc/pid/root/.flatpak-info

**Comment by halfline** [comment] 2016-09-27 16:50
okay great, that should work fine.

**Comment by fmuellner** [comment] 2016-10-08 16:26
Sorry for letting this slip - I've picked this up now, see https://bugzilla.gnome.org/show_bug.cgi?id=772615.

**Closed** 2016-10-24 15:00 UTC
