### ISSUE TITLE
Flatpak website does not show command line instructions for some applications

### ISSUE THREAD

**Issue by kcarcia** [flatpak/flatpak#1677] opened 2018-05-15 22:05 UTC
## Linux distribution and version
OS: RHEL 7.3
Browser: Chrome 65.0.3325.146

## Flatpak version
Current version of https://flathub.org/home

## Description of the problem
I cannot see the command line instructions on the flatpak website for some apps including Flatpak demo and Fedora Media Writer.

## Steps to reproduce
1. Go to https://flathub.org/home
2. Click "Browse the Apps"
3. Search for "Flatpak demo"
4. Scroll down to the "Command line instructions" section
5. Notice that commands do not appear

As a first time Flatpak user, I didn't know the standard install/run process. I also able to figure it out by looking at other app pages, e.g., gimp.

![screenshot from 2018-05-15 18-04-10](https://user-images.githubusercontent.com/1798956/40085985-70dfe8ec-586a-11e8-80d3-21fba4d7935f.png)

**Comment by mwleeds** [comment] 2018-05-18 01:02
This is sort of a duplicate of https://github.com/flathub/linux-store-frontend/issues/108, and I was able to reproduce it the other day but not any more. If you see it again open an issue on that repo.

**Closed by mwleeds** 2018-05-18 01:02 UTC
