### ISSUE TITLE
How to add the .so library to the Flatpak sandbox when building a program?

### ISSUE THREAD

**Issue by KirMozor** [flatpak/flatpak#4941] opened 2022-06-10 11:44 UTC
I am new to Flatpak and am trying to transfer my program to Flatpak, but I ran into a problem.

My program uses a third-party library, and to run the program I need to place the library file under `/usr/lib/libbass.so`
I tried to do this (org.kirmozor.Yamux.yml in zip file [AppDir.zip](https://github.com/flatpak/flatpak/files/8878495/AppDir.zip) ), but I get an error:
`install: cannot create regular file '/usr/lib/libbass.so': Read-only file system`

What do I do in this case?

**Comment by KirMozor** [comment] 2022-06-10 11:49
Before that, instead of install -D libbass.so /usr/lib, I tried this: cp libbass.so /usr/lib
But the error remained the same :(

**Comment by rusty-snake** [comment] 2022-06-10 12:04
Related: #4929

**Comment by swick** [comment] 2022-06-10 12:56
/usr is read-only by design. Try to convince the library to search at the right directory (LD_LIBRARY_PATH and friends). If all else fails you can overwrite dlopen in your app and redirect that to the correct path. This isn't the right place for questions like this though.

**Comment by smcv** [comment] 2022-06-10 14:14
This is not a bug, closing.

**Closed by smcv** 2022-06-10 14:14 UTC
