### ISSUE TITLE
Update is older then current version

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#1266] opened 2017-12-20 00:40 UTC
What happened:
1) Had a few flatpak's installed (eg org.audacityteam.Audacity)
2) Wait for a period of time, so there are updates
3) Perform `$ flatpak update` when there is an update
4) Notice, sometimes, that "Update is older then current version" is returned

What should happen:
At step 4 for the update to work.

Note: This is the second time I've had this happen to a flatpak when simply performing `$ flatpak update`.
Also side note, this error should probably read "Update is old *than* current version" ?

Output when performing an update.
```
$ flatpak update
Looking for updates...
Updating: org.audacityteam.Audacity/x86_64/stable from flathub
Error: Failed to update org.audacityteam.Audacity/x86_64/stable: Update is older then current version
error: One or more operations failed
```

The information about the local and remote, also note that the local date "2017-12-18 22:27:19 +0000" when this command was performed around "2017-12-18 22:03:09 +0000" (see pastebin post time here for proof https://pastebin.ubuntu.com/26211367/ ). So I have a local commit which thinks it is from the future ?! I wonder if this is part of the problem ? Otherwise you can see from the commits that my local is one commit behind the remote.
```
$ flatpak info org.audacityteam.Audacity
Ref: app/org.audacityteam.Audacity/x86_64/stable
ID: org.audacityteam.Audacity
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2017-12-18 22:27:19 +0000
Subject: Update to 2.2.1 and fix m4a import (b8dde8d6)
Commit: f857d3c30495af7013a2543f6867e68916b61b1e46fb7d17b06ae161c4ff25c5
Parent: a8857483aee8537f4e5b52cf33b02c3ac5852cff3c6b5517ff9c52d2a77e514f
Location: /var/lib/flatpak/app/org.audacityteam.Audacity/x86_64/stable/f857d3c30495af7013a2543f6867e68916b61b1e46fb7d17b06ae161c4ff25c5
Installed size: 43.4 MB
Runtime: org.gnome.Platform/x86_64/3.26

$ flatpak remote-info flathub org.audacityteam.Audacity
Ref: app/org.audacityteam.Audacity/x86_64/stable
ID: org.audacityteam.Audacity
Arch: x86_64
Branch: stable
Date: 2017-12-18 16:13:56 +0000
Subject: Enable Opus and WMA (4391711e)
Commit: 8c10ec263790a7832ce1586a8dca99fb752abc2f04e9a9b5cc38288b85e8e64c
Parent: f857d3c30495af7013a2543f6867e68916b61b1e46fb7d17b06ae161c4ff25c5
Download size: 15.2 MB
Installed size: 43.5 MB
Runtime: org.gnome.Platform/x86_64/3.26
```

The workaround I used last time to resolve the issue was simply to remove and install the app again.

**Comment by alexlarsson** [comment] 2017-12-20 10:57
I think this might actually have been caused by the timestamps being wrong on the flathub build machines. @chergert @ramcq I guess we need to ensure that all the workers are in the same timezone, etc?

**Comment by alexlarsson** [comment] 2017-12-20 11:07
For the record, here are the two builds:
 First one (that you had locally): https://flathub.org/builds/#/builders/1/builds/1331
 Second one: https://flathub.org/builds/#/builders/1/builds/1335
The x86-64 build was on worker flathub-builder-pdx1 for the first, and x86-1 for the second.

**Comment by alexlarsson** [comment] 2017-12-20 11:17
Unfortunately I can't find any timestamps in the logs, but the timestamps of the two commits that lead to the builds are 13:56 and 15:43 it seems likely that the second commit has the right timestamp, but the first one is off by 8 hours.

**Comment by alexlarsson** [comment] 2017-12-20 11:18
@chergert Basically, it looks like the timezone info is off on flathub-builder-pdx1

**Comment by alexlarsson** [comment] 2017-12-20 15:39
@airlied any idea what could cause the radeon driver to be slow like this or how to debug it?

**Comment by chergert** [comment] 2017-12-20 22:44
Indeed, the pdx1 builder had an incorrect time set. It was PST but with something near a UTC time. It looks like CentOS doesn't automatically setup ntp for us, so we should add that to the setup instructions. (`systemctl enable ntpd` is probably enough).

**Comment by alexlarsson** [comment] 2017-12-21 08:55
Ok. i'll close this supposing this is fixed.

**Closed** 2017-12-21 08:57 UTC

**Comment by orschiro** [comment] 2018-02-09 10:21
Hey guys,

Having the same issue on Fedora 27:

```
[orschiro@localhost ~]$ flatpak update
Looking for updates...
Updating: org.kde.Platform/x86_64/5.9 from flathub
Warning: Failed to update org.kde.Platform/x86_64/5.9: Update is older then current version
```

How can I address this in my case? It's not a timezone issue, is it?

BTW: it should be `older than current version` not `then current version` :-)

**Comment by orschiro** [comment] 2018-02-09 11:31
Alright, solved as follows:

1. `flatpak uninstall org.kde.Platform/x86_64/5.9`
2. `flatpak install flathub org.kde.Platform//5.9`

Now all is good again. :-)
