### ISSUE TITLE
flatpak-coredumpctl should auto install debug extensions & SDKs

### ISSUE THREAD

**Issue by vchernin** [flatpak/flatpak#4427] opened 2021-09-20 22:53 UTC
## Linux distribution and version
Fedora 34 Silverblue
## Flatpak version
1.10.2
## Description of the problem

`flatpak-coredumpctl` should auto install required/useful debug runtimes/sdks.

I saw reading [this great article](https://blogs.gnome.org/mcatanzaro/2021/09/18/creating-quality-backtraces-for-crash-reports/) `coredumpctl` is able to auto install all required components when getting a backtrace on Fedora 35. However the Flatpak section of the article for `flatpak-coredumpctl` describes how one has to manually install needed debug extensions and SDKs. I don't see why `flatpak-coredumpctl` can't proactively prevent headaches and prompt users to install the things they probably want to install when getting a Flatpak app's backtrace.

I don't see why something like `debuginfod` would be necessary for Flatpak here, just auto installing the SDK for the app's runtime, and the 2 debug extensions (as explained in the article) should be sufficient.

**Comment by mwleeds** [comment] 2021-10-08 22:24
duplicate of #2003

**Closed by mwleeds** 2021-10-08 22:24 UTC
