### ISSUE TITLE
flatpak remote-ls complains about a remote

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#1489] opened 2018-03-16 10:38 UTC
I get this

$ flatpak remote-ls --updates 
error: Invalid refspec org.mozilla.FirefoxNightly-origin:.

when trying to list available updates.
Yet, flatpak update seems to have no problem with it.

**Comment by TingPing** [comment] 2018-03-16 10:41
Duplicate of #1444

**Closed** 2018-03-17 04:28 UTC
