### ISSUE TITLE
Flatpak doesn’t work: Unable to load summary from remote flathub: Peer failed to perform TLS handshake.

### ISSUE THREAD

**Issue by SimplestStudio** [flatpak/flatpak#3452] opened 2020-03-08 12:55 UTC
Manjaro Linux 19.0.2
Flatpak version 1.6.2

Description of the problem:
Flatpak doesn’t work: Unable to load summary from remote flathub: Peer failed to perform TLS handshake.
On some forums it is written that the problem with the clock, but I tried all sorts of ways to configure the clock, including in the BIOS , nothing helped.

Steps to reproduce:
There is no search and installation via Flatpak (using the Bauh and Discover programs, through the terminal, the same thing).
An error appears: Unable to load summary from remote flathub: Peer failed to perform TLS handshake.

**Comment by mwleeds** [comment] 2020-03-09 18:31
>  On some forums it is written that the problem with the clock, but I tried all sorts of ways to configure the clock, including in the BIOS , nothing helped.

Is your clock set incorrectly?

**Comment by Helg1980** [comment] 2020-03-09 19:21
Correctly

**Comment by Helg1980** [comment] 2020-03-11 17:40
???

**Comment by Helg1980** [comment] 2020-03-11 17:45
In short, I need to go back to Windows , no one knows anything.

**Comment by refi64** [comment] 2020-03-11 17:49
It's only been ~3 days.

**Comment by refi64** [comment] 2020-03-11 17:52
Also check #2921 and #3388, if you haven't run a full upgrade in a while
it's likely the same p11-kit bug.

**Comment by Helg1980** [comment] 2020-03-11 19:29
Thanks! Tell me how to downgrade that package.

**Comment by rmader** [comment] 2020-03-11 22:13
> Thanks! Tell me how to downgrade that package.

Dude, this is not your personal support hotline. Do you pay anyone here? If not, please either change your attitude - friendly asking for help instead of commanding people around - or yes, get back to windows or wherever you came from. This is an issue tracker where people collaboratively work on free software - nobody here asked you to use it, you are just friendly invited to join (if you behave).

**Comment by Helg1980** [comment] 2020-03-12 05:35
I'm also trying to develop free software, actually.

**Comment by Helg1980** [comment] 2020-03-15 09:07
Manjaro updates have arrived, but nevertheless Flatpack does not work , the same error appears.

**Comment by Helg1980** [comment] 2020-03-17 16:03
[helg@Houston ~]$ wget https://dl.flathub.org/repo/logo.svg
--2020-03-17 17:59:53--  https://dl.flathub.org/repo/logo.svg
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving dl.flathub.org (dl.flathub.org)... 151.101.2.217, 151.101.66.217, 151.101.130.217, ...
Connecting to dl.flathub.org (dl.flathub.org)|151.101.2.217|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.

**Comment by Helg1980** [comment] 2020-04-08 11:14
Good afternoon! The other day I found out that in the KDE Neon distribution, Flatpack works for me, but for some reason in Manjaro KDE, Manjaro Gnome, as well as in Elementary OS, Flatpak does not work.

**Comment by Helg1980** [comment] 2020-04-08 22:39
I connected to the Internet via my mobile phone, and then started installing apps via Flatpack.
The most incomprehensible thing about all this is that now the error does not appear when connecting to the wired Internet.
Accordingly, the problem is that the TLS requirements are too strict when installing components:

org.freedesktop.Platform
org.freedesktop.Platform.GL.default
org.freedesktop.Platform.GL.nvidia-440-82
org.freedesktop.Platform.openh264

after installing them, the “Peer failed to perform TLS handshake” error no longer appears. Is it possible to soften the requirements for "TLS handshake"in some way?

**Comment by Helg1980** [comment] 2020-04-20 09:01
Hi,
I tried to type this line, and this is what happened:

[helg@Houston ~]$ curl -I https://dl.flathub.org/repo/summary.sig
HTTP/2 200
server: nginx/1.14.0 (Ubuntu)
content-type: application/octet-stream
last-modified: Sun, 19 Apr 2020 21:35:43 GMT
etag: “5e9cc42f-250”
expires: Sun, 19 Apr 2020 22:36:23 GMT
cache-control: max-age=3600
strict-transport-security: max-age=15768000
backend-name: 3DxooTFj8SlVTdJ0UTX8Jd–F_front_hex2_https
accept-ranges: bytes
date: Sun, 19 Apr 2020 22:35:58 GMT
via: 1.1 varnish
age: 3574
x-served-by: cache-fra19131-FRA
x-cache: HIT
x-cache-hits: 125
x-timer: S1587335758.295722,VS0,VE0
content-length: 592

**Comment by liferooter** [comment] 2020-12-10 09:24
Have same issue on latest Arch Linux.
**Flatpak vesion:** Flatpak 1.9.2

**Comment by hfiguiere** [comment] 2024-02-10 19:19
no update.

**Closed by hfiguiere** 2024-02-10 19:19 UTC
