### ISSUE TITLE
create-usb only works on ext4

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2019] opened 2018-08-26 21:12 UTC
I tried create-usb with one of my existing usb sticks, and was greeted with:

"fsetxattr: Operation not supported”

I think it would be very useful to make this work with FAT, as most usb sticks are formatted that way.

**Comment by mwleeds** [comment] 2018-08-28 06:14
@matthiasclasen could you post what OS and version you used for this? Because I'm not able to reproduce it:
```
0 ✓ mwleeds@endless ~ (2 keys)
↳ mount | grep fat
/dev/sdb1 on /run/media/mwleeds/260A-D3BF type vfat (rw,nosuid,nodev,relatime,uid=1001,gid=1001,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
0 ✓ mwleeds@endless ~ (2 keys)
↳ flatpak create-usb /run/media/mwleeds/260A-D3BF org.gnome.Aisleriot
Warning: Couldn't find appstream data for remote ‘flathub’ arch ‘x86_64’: Collection–ref (org.flathub.Stable, appstream/x86_64) not found
3 metadata, 1 content objects imported                                                                                                                                                        

0 metadata, 0 content objects imported; 569 B transferred in 0 seconds                                                                                                                        
256 metadata, 3105 content objects imported                                                                                                                                                   
0 metadata, 0 content objects imported; 569 B transferred in 1 seconds                                                                                                                        
8 metadata, 12 content objects imported                                                                                                                                                       
3 metadata, 1 content objects imported                                                                                                                                                        
5 metadata, 707 content objects imported                                                                                                                                                      
211 metadata, 2646 content objects imported                                                                                                                                                   
0 metadata, 0 content objects imported; 569 B transferred in 1 seconds                                                                                                                        
Copied 10/10 refs successfully from ‘/var/lib/flatpak/repo’ to ‘.ostree/repo’ repository in ‘/run/media/mwleeds/260A-D3BF’.
```

**Comment by matthiasclasen** [comment] 2018-08-28 14:52
Hmm, i'll try to reproduce here.

This was on a Silverblue system, copying from a user installation, and the gnome-disks said 'vfat' for the file system on the stick.

**Comment by matthiasclasen** [comment] 2018-08-29 02:01
still happens here, with a freshly fat-formatted usb stick

**Comment by matthiasclasen** [comment] 2018-08-29 02:02
here is the output with --ostree-verbose

[log.log](https://github.com/flatpak/flatpak/files/2330425/log.log)

**Comment by matthiasclasen** [comment] 2018-09-07 23:05
we played a bit with this at las. We verified that the getxattr check does fail as expected, and causes flatpak to use OSTREE_REPO_MODE_ARCHIVE. Yet, on my system we end up with a fsetxattr failure, while it works on Matthews.

**Comment by mwleeds** [comment] 2018-09-18 21:04
I guess the conclusion is that `OSTREE_REPO_MODE_ARCHIVE` isn't the right mode to use when xattrs aren't available. According to the libostree docs, `OSTREE_REPO_MODE_BARE_USER_ONLY` doesn't require xattrs, so I tried that and got this error:
```
$ flatpak create-usb /run/media/mwleeds/4478-6DC3 org.gnome.dfeet
6 metadata, 1 content objects imported                                                                                                                                                        
28 metadata, 141 content objects imported                                                                                                                                                     
1 metadata, 0 content objects imported                                                                                                                                                        

Caught error, waiting for outstanding tasks                                                                                                                                                   
error: Writing content object: Operation not permitted
```
whereas on this machine things work fine when `create-usb` uses the archive mode with the same FAT-formatted flash drive.

At the moment I don't understand enough about the ostree repo modes or why flatpak needs xattrs to debug this further.

**Comment by mwleeds** [comment] 2018-09-28 20:07
I can't prove it but I'm pretty confident this was fixed by https://github.com/ostreedev/ostree/commit/c141fe610b652f383a9c445169d3cc6f28f99bd1

**Closed by mwleeds** 2018-09-28 20:07 UTC
Labels: enhancement, p2p
