### ISSUE TITLE
Persistent errors when running any Flatpak

### ISSUE THREAD

**Issue by lionirdeadman** [flatpak/flatpak#2167] opened 2018-10-02 05:08 UTC
## Linux distribution and version
Fedora 29 (upgraded from Fedora 28)
## Flatpak version
1.0.2
## Description of the problem
GNOME Flatpaks don't start, KDE flatpaks have similar error messages but start anyways. This happens consistently.
## Steps to reproduce
I don't know.
I tried reinstalling Flatpak, clearing `/var/lib/flatpak`, `~/.var/app/` , `~/.local/share/flatpak` and then reinstalling the flatpaks. 

Here's some errors : 

Gitg :
```Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"

(gitg:2): GLib-GIO-CRITICAL **: g_converter_convert: assertion 'outbuf_size > 0' failed

** (gitg:2): WARNING **: gitg-resource.vala:33: Error while loading resource: style-unix.css:1:0Failed to import: The resource at “/org/gnome/gitg/ui/style-unix.css” failed to decompress

(gitg:2): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Paper/16x16/status/image-missing.png: Error opening file /run/host/share/icons/Paper/16x16/status/image-missing.png: No such file or directory (g-io-error-quark, 1)
```

Krita : 
```Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Delegate created
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'sip'
/app/lib/krita-python-libs/krita added to PYTHONPATH
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Regular")
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Bold")
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Regular")
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Regular")
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Regular")
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Light")
krita.general: Could not find font QVariant(QString, "Source Sans Pro") with style QVariant(QString, "Regular")
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/opacity-increase
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/opacity-decrease
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/lightness-increase
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/lightness-decrease
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/zoom-in
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/rotate-canvas-left
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/rotation-reset
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/rotate-canvas-right
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/zoom-out
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/brushsize-decrease
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/brushsize-increase
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/preset-switcher
file:///app/lib/qml/org/krita/sketch/components/Button.qml:84:9: QML Image: Failed to get image from provider: image://icon/edit-clear
```

How can I help to fix this bug / How can I fix this issue on my system if it's a local system?

**Comment by alexlarsson** [comment] 2018-10-04 06:55
Hmm, i get some of those gitg warnings too:
```
$ flatpak run org.gnome.gitg
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"

(gitg:2): GLib-GIO-CRITICAL **: g_converter_convert: assertion 'outbuf_size > 0' failed

** (gitg:2): WARNING **: gitg-resource.vala:33: Error while loading resource: style-unix.css:1:0Failed to import: The resource at “/org/gnome/gitg/ui/style-unix.css” failed to decompress
```
but it seems to work.

**Comment by alexlarsson** [comment] 2018-10-04 07:15
Ah, that is an old error which doesn't matter: https://gitlab.gnome.org/GNOME/glib/issues/1560

**Comment by alexlarsson** [comment] 2018-10-04 07:16
Your actual issue is a duplicate of: https://github.com/flatpak/flatpak/issues/2149

**Closed by alexlarsson** 2018-10-04 07:16 UTC

**Comment by lionirdeadman** [comment] 2018-10-04 20:34
Ah, damn. Who would've thought icon themes would break flatpaks. Guess I'll stick to Adwaita for now. 

Thank you.
