### ISSUE TITLE
Works without systemd ?

### ISSUE THREAD

**Issue by yledoare** [flatpak/flatpak#1164] opened 2017-11-11 19:30 UTC
Thanks for Flatpak, it is a great idea !

I try to make it run inside my distro (linuxconsole).

The init process is run from busybox (not systemd), I try to run it from the next (alpha) LinuxConsole  release, but when I want to run package, I have this error :  "pivot_root: Invalid argument".

I looked inside the code, and i saw call to /run/users/ inside bubblewrap/bubblewrap.c, but I believe that is is provided by pam_systemd.

Is it possible to run flatpak without Systemd ? 

Thanks

**Comment by alexlarsson** [comment] 2017-11-13 14:16
This is unrelated to systemd and is a duplicate of:  https://github.com/flatpak/flatpak/issues/1007

**Closed by alexlarsson** 2017-11-13 14:16 UTC

**Comment by yledoare** [comment] 2026-04-24 22:39
(very late) Fixed by enabled switch_root in early starting initramfs
https://github.com/linuxconsole-org/ydfs/commit/be43d38550a84758b26b5cccba3e9d40cef12049

Thanks !
