### ISSUE TITLE
Downloading times out; doesn't resume

### ISSUE THREAD

**Issue by jadahl** [flatpak/flatpak#1196] opened 2017-11-24 06:40 UTC
For the last couple of days I've tried to download org.kde.Platform/x86_64/5.9 from flathub. Every time it has failed with the message

`error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote flathub-1: [28] Timeout was reached`

When retrying, it'll fail again. The closest I ever got to finishing so far was 273.7 MB out of 276.0, but yet it failed and restarted from scratch the next attempt. The outcome is always the same; only that it will fail after different degree of progress.

**Comment by jadahl** [comment] 2017-11-24 06:42
I'm not sure whether this is the same as issue 945, which is also about a timeout except about updating remote metadata.

**Comment by alexlarsson** [comment] 2017-11-24 10:37
So, i can't reproduce this right now, but a lot of people have seen it in various places, and its also reported at https://github.com/ostreedev/ostree/issues/878, and seems to be related to the curl ostree backend.

If anyone can reproduce this, can you try this:
```
ostree --repo=testrepo init --mode=bare-user
ostree --repo=testrepo remote add --no-gpg-verify flathub https://flathub.org/repo
ostree --repo=testrepo pull -v flathub runtime/org.gnome.Sdk/x86_64/3.26
```

**Comment by alexlarsson** [comment] 2017-11-24 10:38
Also, please report output of `ostree --version`

**Comment by jadahl** [comment] 2017-11-24 10:41
I could not reproduce the issue, but it might be because the internet connectivity is better where I am at now. I'll try to reproduce again later.

The ostree version is what is provided in F27; anyway more specifically it is
```
libostree:
 Version: 2017.12
 Git: 6a701651ebd91e34e9bf70d7225433f442aac48d
 Features:
  - libcurl
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - openssl
  - libmount
  - release
```

**Comment by alexlarsson** [comment] 2017-11-28 15:48
I believe this is fixed by https://github.com/ostreedev/ostree/pull/1349

**Closed by alexlarsson** 2017-11-28 15:48 UTC

**Comment by brihadeesh** [comment] 2018-03-24 13:49
Been facing this issue for a while now. I don't have `ostree` installed. Could that be the issue here? Running Ubuntu 16.04

`$ flatpak install '~/Downloads/binaries/Flatpak/org.fedoraproject.MediaWriter.flatpak' 
Required runtime for org.fedoraproject.MediaWriter/x86_64/master (org.kde.Platform/x86_64/5.9) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.kde.Platform/x86_64/5.9 from flathub
[###############     ] Downloading: 140.3 MB/192.6 MB (454.1 kB/s)             
error: While pulling runtime/org.kde.Platform/x86_64/5.9 from remote flathub: Socket I/O timed out
`

**Comment by mwleeds** [comment] 2018-03-24 16:35
Flatpak has a hard requirement on ostree, so you must have at least the library installed if not also the command line tools.

**Comment by brihadeesh** [comment] 2018-03-24 16:40
That's odd considering apt usually installs the dependencies (I installed flatpak from the PPA). Based on some of the older comments here I figured it would be essential. So I can just install the packaged version of ostree?

**Comment by mwleeds** [comment] 2018-03-24 18:02
You probably have it installed and don't realize it but sure, apt installing it won't hurt. Run
```
$ ldd `which flatpak` | grep ostree
```
and you'll see it

**Comment by brihadeesh** [comment] 2018-03-24 21:32
Thats odd. I did see the library:
`$ ldd `which flatpak` | grep ostree`
`	libostree-1.so.1 => /usr/lib/x86_64-linux-gnu/libostree-1.so.1 (0x00007f916cdc9000)`
What can I do to fix this?

**Comment by mwleeds** [comment] 2018-03-24 21:37
Does it happen every time you do an install or just sometimes?

**Comment by brihadeesh** [comment] 2018-03-24 21:40
Well, pretty much all the time. It was occasional in my Fedora 27, but quite frequent in Ubuntu (that is to say each time I have tried to install anything through flatpak).

**Comment by mwleeds** [comment] 2018-03-24 21:49
Maybe you're on too old a version of flatpak/ostree to have the fix mentioned above.
