### ISSUE TITLE
Automatically clean-up/remove unsupported runtimes (Feature Request)

### ISSUE THREAD

**Issue by barnscott** [flatpak/flatpak#3747] opened 2020-07-15 03:11 UTC
This is a feature request, not a bug.

## Linux distribution and version
Fedora Silverblue 32

## Flatpak version
Flatpak 1.6.4

## Description of the problem
I typically let Flatpak manage itself and don't touch it, and it normally works great. However, today Gnome Software provided errors when checking for udpates. Jumping on the command line, I saw the following:

[barn@b ~]$ flatpak update -y
```
Looking for updates…
Info: org.gnome.Sdk is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Sdk.Locale is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform is end-of-life, with reason: GNOME 3.30 runtime is no longer supported as of 27th January 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: GNOME 3.30 runtime is no longer supported as of 27th January 2020. Please ask your application developer to migrate to a supported platform.
Info: org.fedoraproject.Platform is end-of-life, with reason: Fedora 30 runtime is no longer supported.
F: Warning: Treating remote fetch error as non-fatal since runtime/org.fedoraproject.Platform/x86_64/f29 is already installed: No such ref 'runtime/org.fedoraproject.Platform/x86_64/f29' in remote fedora
F: Warning: Can't find runtime/org.fedoraproject.Platform/x86_64/f29 metadata for dependencies: No entry for runtime/org.fedoraproject.Platform/x86_64/f29 in remote 'fedora' summary flatpak cache 
Info: io.github.GnomeMpv.Locale is end-of-life, with reason: This project has been renamed to io.github.celluloid_player.Celluloid
Info: io.github.GnomeMpv is end-of-life, with reason: This project has been renamed to io.github.celluloid_player.Celluloid
error: Failed to get tokens for ref: Not a oci remote, missing summary.xa.oci-repository
```

Wow, that's a lot of messages and warnings! After removing the unsupported runtimes, issue was fixed. But it would be nice if flatpak verified if (a) runtime is no longer supported and (b) if no apps are using the runtime. Based on these two conditions, it would be nice to automatically remove any old runtimes. Considering that flatpak automatically installs runtimes, I think it is sensible to let flatpak remove the runtimes too.

## Steps to reproduce
If using Fedora, you can reproduce this error if you let your runtimes pile up for at least 3 releases.

**Comment by mwleeds** [comment] 2020-07-15 16:17
Duplicate of #2639

I do agree it would make sense to remove unused eol runtimes.

The error `error: Failed to get tokens for ref: Not a oci remote, missing summary.xa.oci-repository` seems like an independent issue that deserves its own ticket.

**Closed by mwleeds** 2020-07-15 16:17 UTC
