### ISSUE TITLE
Too many strings offered for translation?

### ISSUE THREAD

**Issue by haaninjo** [flatpak/flatpak#310] opened 2016-09-14 20:25 UTC
Hi,
reviewing the Swedish translation I noticed some strings in system-helper/org.freedesktop.Flatpak.policy.in that looks like they might be better left untranslated.

This includes strings like "package-x-generic", "auth_admin_keep", "https://cgit.freedesktop.org/xdg-app/xdg-app/" etc.

So, should the tags outside `<vendor>`, `<message>` and `<description>` in helper/org.freedesktop.Flatpak.policy.in really be translatable?

(I reported the same for gvfs, and in that case got the response that it might be a gettext bug as there was an .its file in place to only have the `<message>` and `<description>`  tags translatable: https://mail.gnome.org/archives/gnome-i18n/2016-September/msg00044.html )

**Comment by alexlarsson** [comment] 2016-09-15 09:07
Actually, I think the problem is that there is *not* an its file for policykit xml files, because policykit is not installing it or something. @matthiasclasen do you know the status of this?

**Comment by matthiasclasen** [comment] 2016-09-18 20:11
Its merged in master, but not in a release yet: https://cgit.freedesktop.org/polkit/

**Comment by matthiasclasen** [comment] 2016-09-18 20:27
The idea with the rule for policy files was that we'll fall back to copying the untranslated file if we don't have an its file. Is that not working ?

**Comment by matthiasclasen** [comment] 2016-09-24 14:54
Oh, I see. The rule is only about merging the translations back. This is about extracting the strings, for which gettext seems to fall back to just treat this as xml.

**Comment by matthiasclasen** [comment] 2018-09-25 23:46
this seems fixed now

**Closed by matthiasclasen** 2018-09-25 23:46 UTC
