### ISSUE TITLE
a crash in progress reporting

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#819] opened 2017-05-28 02:39 UTC
Seen while updating today:

Updating: com.spotify.Client/x86_64/master from com.spotify.Client-origin

Downloading extra data 91.1 MB/91.1 MB                                                                   **
OSTree:ERROR:src/libostree/ostree-async-progress.c:214:ostree_async_progress_get: assertion failed: (variant != NULL)
Aborted (core dumped)

**Comment by pwithnall** [comment] 2017-05-29 12:31
> mclasen_	pwithnall___, I've encountered https://github.com/flatpak/flatpak/issues/819
> and git blame seems to point in your direction
> pwithnall___	mclasen_: does the backtrace for the assertion failure use the new async_progress_get() API, or the old get_uint{,64}()?
> mclasen_: The fix is going to be something like this: https://github.com/flatpak/flatpak/commit/67a9d9dfec934e4900c83efab563786d71d4097f
> mclasen_	pwithnall___, I'll check the next time it happens
> pwithnall___	so either that commit fixes your problem, or a similar one needs to be made on another code path to ensure all the progress fields are initialised at first use
> *initialised before they’re first queried
> mclasen_	sounds like a job for ostree_async_progress_new ? or _init ? or some other central place ?
> pwithnall___	ish
> The caller provides the OstreeAsyncProgress object, though, and the function they’re calling is the one which needs to initialise all thefields

**Comment by alexlarsson** [comment] 2017-05-31 06:45
This is fixed in flatpak 0.9.4, but yeah, its caused by the new ostree and is a bit unfortunate.

**Closed by alexlarsson** 2017-05-31 06:45 UTC
