### ISSUE TITLE
Flatpak update fails with "No such metadata object"

### ISSUE THREAD

**Issue by alexb3d** [flatpak/flatpak#2048] opened 2018-08-30 17:53 UTC
In Ubuntu, Flatpak does not update 
![screenshot from 2018-08-30 13-48-07](https://user-images.githubusercontent.com/7833263/44871216-0cab2b80-ac47-11e8-8b3b-c6979f55d648.png)

**Comment by mwleeds** [comment] 2018-09-09 16:49
Duplicate of #725

**Closed by mwleeds** 2018-09-09 16:49 UTC
