### ISSUE TITLE
flatpak uninstall app doesn't work if --user not specified

### ISSUE THREAD

**Issue by csoriano1618** [flatpak/flatpak#1333] opened 2018-01-23 12:40 UTC
Seems I have installed an application as a --user, however when typing uninstall it forces to specify --user instead of assuming the only one installed is what I probably want to remove.

I believe this should just uninstall if it's under user. Afaik that goes in line with other commands that assume that user installation is always first, like when running a flatpak installed both system and user wise with the same id.

**Comment by mwleeds** [comment] 2018-01-24 07:09
Duplicate of #1321?

**Closed** 2018-01-24 07:09 UTC
