### ISSUE TITLE
Download status moves both up and down every time , correcting errors?

### ISSUE THREAD

**Issue by Azza-NZ** [flatpak/flatpak#3196] opened 2019-10-25 20:26 UTC
## Linux distribution and version
Ubuntu 18.04 and Fedora 30
## Flatpak version
Multiple versions including 1.4.3
## Description of the problem
When installing anything via terminal the download percentage will count both up and down (before eventually getting to 100%) . It  looks like it's quickly correcting corrupted files. Normally downloads will only increase in percentage unless something has gone wrong.
## Steps to reproduce
Install anything from terminal "flatpak install ..."

**Comment by matthiasclasen** [comment] 2019-10-26 16:47
this is due to us having incomplete information about the size of the download, and is hard to fix.

**Comment by Azza-NZ** [comment] 2019-10-27 19:39
Thanks for the reply, it's good to know it's not correcting errors.

Perhaps you could make it tick up in 10% increments and not tick back if the estimated size gets bigger, simply stay at current percentage. I think that would be less confusing and more in line with what people would expect. 

Thanks for your time I'm a big fan of FlatPak in general and appreciate your work.

**Comment by Azza-NZ** [comment] 2019-10-27 22:07
I just used it again and  it has a new way to show progress, I like it.  I'm using Solus OS now, is that unique to Solus OS or is there a new system now?

**Comment by matthiasclasen** [comment] 2019-10-28 15:33
I don't know what you are talking about, so I can't answer that question

**Comment by Azza-NZ** [comment] 2019-10-30 03:27
> I don't know what you are talking about, so I can't answer that question

In Solus OS when installing a flatpak from terminal it doesn't tick up and down like I explained , instead it shows how many files of a total number of files have been downloaded. It's a better option in my opinion.

**Comment by mwleeds** [comment] 2019-11-12 21:33
duplicate of #3175 and #2768

**Closed by mwleeds** 2019-11-12 21:33 UTC

**Comment by Azza-NZ** [comment] 2019-11-12 23:24
> 
> 
> duplicate of #3175 and #2768

Can you leave one of these open? I thought the work around I described was good, you could list packages needed and packages received instead of "percentage complete". That what it does by default in Solus OS (a Linux distribution). It makes sense and looks nice.

**Comment by mwleeds** [comment] 2019-11-13 18:16
@Azza-NZ you can open an issue here: https://github.com/ostreedev/ostree/
