### ISSUE TITLE
Flatpak over-reports download size

### ISSUE THREAD

**Issue by aidanharris** [flatpak/flatpak#3362] opened 2020-01-12 14:21 UTC
## Linux distribution and version
Gentoo (rolling)

## Flatpak version

Flatpak 1.6.0

## Description of the problem

![Screenshot from 2020-01-12 14:14:37](https://user-images.githubusercontent.com/3309784/72220219-6e232000-3546-11ea-80a1-290cf2c9891e.png)

## Steps to reproduce
`flatpak update` (note the download size which estimates that 94TB will be downloaded.)

This may be a duplicate of #3127

**Comment by mwleeds** [comment] 2020-01-13 23:13
Don't think this is a duplicate of #3127. That one is about under-reporting; this is about over-reporting.

But this is a duplicate of #2627 I'd argue.

**Comment by refi64** [comment] 2020-01-14 05:06
Isn't 94tb a bit excessive though? I'd think there's something more
intricate going on here...

**Comment by barthalion** [comment] 2020-01-21 09:06
We just started hitting it on Flathub after migrating to ZFS so re-opening.

**Comment by barthalion** [comment] 2020-01-21 09:10
```
~ $ flatpak --system remote-info flathub org.gnome.Boxes                                          1

GNOME Boxes - Simple remote and virtual machines

        ID: org.gnome.Boxes
       Ref: app/org.gnome.Boxes/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 3.34.3
   License: LGPL-2.1+
Collection: org.flathub.Stable
  Download: 94,3 TB
 Installed: 672,2 MB
   Runtime: org.gnome.Platform/x86_64/3.34

       Sdk: org.gnome.Sdk/x86_64/3.34
    Commit: 8a8370f5fa3627ebb873dde4878a5d5137e38febb2defeeb0d93c6b65e07167a
    Parent: fcf719456eeefb8553cd8b3b95265af2485a7138c01bef23be44b86fa1cae7a5
   Subject: use shared-modules for intltool (24de53cb)
      Date: 2020-01-20 15:36:40 +0000

~ $ flatpak --system remote-info flathub-beta org.nextcloud.Nextcloud.Locale
        ID: org.nextcloud.Nextcloud.Locale
       Ref: runtime/org.nextcloud.Nextcloud.Locale/x86_64/beta
      Arch: x86_64
    Branch: beta
Collection: org.flathub.Beta
  Download: 93,8 TB
 Installed: 96,8 kB

    Commit: 03f93786663595384e177c8fd470ba137bbdae050c7b2049e2234fc5aae32c5e
    Parent: 3ecfb909847016b5549c1708666da372af748e2e5037406160e9342d75bbb02e
   Subject: Bump version to 2.7.0-beta1 (925bd851)
      Date: 2020-01-20 14:11:37 +0000 
```

**Comment by fenris** [comment] 2020-01-21 09:11
![Screenshot from 2020-01-21 16-48-56](https://user-images.githubusercontent.com/405473/72790622-e7222600-3c70-11ea-8284-c82788a79d30.png)

Another 93TB for Gnome Box as @barthalion details

**Comment by alexlarsson** [comment] 2020-01-21 09:24
I can see the wrong size of boxes too, and it seems to not be a endianness issue.

The download-size stored in the summary is 0x5f325affce550000, which when converted from big endian is 0x55ceff5a325f.

This size is calculated when creating the commit object during the build-commit-from operation on the flathub master repo with this code:  
https://github.com/flatpak/flatpak/blob/a98d655f4ff95082eb5386dd2d825389dcdb03f4/common/flatpak-utils.c#L3220

And it is later copied from the commit to the summary which is downloaded and read by the client.

**Comment by alexlarsson** [comment] 2020-01-21 09:30
The value seems wrong in the commit object too, so its the calculation that goes wrong.

**Comment by alexlarsson** [comment] 2020-01-21 09:33
I don't understand how that can go wrong though. Its just fstat:ing all the object files and summing stbuf.st_size.

**Comment by alexlarsson** [comment] 2020-01-21 09:34
Oh, its not initilalizing it before summing!

**Closed** 2020-01-23 08:04 UTC
Labels: bug
