### ISSUE TITLE
[RFE] Caching software - On a LAN

### ISSUE THREAD

**Issue by dmedri** [flatpak/flatpak#2112] opened 2018-09-17 16:47 UTC
## Linux distribution and version

misc, flatpak on 27/28 with last updates

## Flatpak version
see above. (on fed27, ver. 1.0.0)

Browsing online on project website, I didn't find any useful reference or future plan. So, this is a RFE, a request for enhancement, or an open discussion about the implementation of a general idea. This one is based on local caching mechanism, already cited here: [(https://github.com/flatpak/flatpak/issues/2111)]

Caching software packages, on a LAN (Local Area Network)
----------------------------------------------------------------------------

Every host on a LAN could have similar software requests. A host with a local cache shared on a local network could decrease the network traffic. As an example, on Debian, a distro-specific tool is apt-cacher-ng that act like a network proxy.

**Comment by mwleeds** [comment] 2018-09-17 17:27
Closing as a duplicate of https://github.com/flatpak/flatpak/issues/1693

**Closed by mwleeds** 2018-09-17 17:27 UTC
