### ISSUE TITLE
Cleanup 'flatpak update' command error's ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#3422] opened 2020-02-18 13:48 UTC
## Linux distribution and version
Deepin Linux 15.11

## Flatpak version
Flatpak 1.2.5

## Description of the problem
getting update errors when the command `flatpak update` is executed ...

```
$ flatpak update
Looking for updates…
F: Error updating remote metadata for 'org.qBittorrent.qbittorrent-origin': GPG signatures found, but none are in trusted keyring
F: Error updating remote metadata for 'gnome': Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk/x86_64/1.4 is already installed: Unable to load summary from remote gnome: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Sdk/x86_64/1.4 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Sdk.Locale/x86_64/1.4 is already installed: Unable to load summary from remote gnome: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Sdk.Locale/x86_64/1.4 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Platform.GL.default/x86_64/1.6 is already installed: Unable to load summary from remote gnome: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Platform.GL.default/x86_64/1.6 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Treating remote fetch error as non-fatal since runtime/org.freedesktop.Platform.GL.default/i386/1.6 is already installed: Unable to load summary from remote gnome: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Can't find runtime/org.freedesktop.Platform.GL.default/i386/1.6 metadata for dependencies: Unable to load metadata from remote gnome: summary fetch error: Error resolving 'sdk.gnome.org': Name or service not known
F: Warning: Treating remote fetch error as non-fatal since app/org.qBittorrent.qbittorrent/x86_64/stable is already installed: Unable to load summary from remote org.qBittorrent.qbittorrent-origin: GPG signatures found, but none are in trusted keyring
F: Warning: Can't find app/org.qBittorrent.qbittorrent/x86_64/stable metadata for dependencies: Unable to load metadata from remote org.qBittorrent.qbittorrent-origin: summary fetch error: GPG signatures found, but none are in trusted keyring

        ID                                   Arch             Branch           Remote           Download
^[[33;1R 1. [✗] io.designer.GravitDesigner           x86_64           stable           flathub          194.7 MB / 206.0 MB

Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Updates complete.
error: There were one or more errors

```

## Steps to reproduce
execute command `flatpak update`

**Comment by mwleeds** [comment] 2020-02-18 21:42
> F: Error updating remote metadata for 'gnome': Error resolving 'sdk.gnome.org': Name or service not known

The suggestion in #3356 was for you to remove the `gnome` remote.

>F: Error updating remote metadata for 'org.qBittorrent.qbittorrent-origin': GPG signatures found, but none are in trusted keyring

Would need more information to debug this, like the output of `flatpak remotes -d` and `ls /var/lib/flatpak/repo/`

>Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Updates complete.`

For what it's worth, that was the symptom of a problem fixed in Endless by [this commit](https://github.com/endlessm/eos-updater/pull/262/commits/a076e31acb41802123f06a83984a018db39bb8b1), but the cause is likely different in your case unless you have some sandboxing (e.g. by AppArmor) happening on flatpak. If that issue is only reproducible on Deepin, maybe report a bug to them?

**Closed** 2020-03-03 03:03 UTC
Labels: need more info
