### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Pshemas** [flatpak/flatpak#1875] opened 2018-07-09 18:00 UTC
## Description of the problem:
I've been using flathub's Steam flatpak and I've noticed that in a fair share of games I don't have audio. While looking into command line output I see the following:
```
ALSA lib conf.c:3942:(snd_config_update_r) Cannot access file /etc/alsa-pulse.conf
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM default
```
The list of games that I found affected by this problem is here:
https://github.com/flathub/com.valvesoftware.Steam/issues/102

Do you have any ideas what can I try to workaround / solve this problem?
It's pretty annoying as other than that Flatpak would be a perfect solution for less important, casual things like games :) .

**Comment by fenryxo** [comment] 2018-07-10 06:55
I guess that the issue is that OpenSUSE sets to `ALSA_CONFIG_PATH` environment variable to `/etc/alsa-pulse.conf`, which does not exist in the Flatpak sandbox. If it is so, `unset ALSA_CONFIG_PATH; flatpak run ...` should work.

**Comment by Pshemas** [comment] 2018-07-10 17:07
ok, so while the workaround works I wonder - how do I make those changes work each time (with desktop shortcut) so I won't have to launch Steam flatpak through command line?
It seems it's not so easy as modifying a .dekstop file ...

**Comment by nanonyme** [comment] 2018-07-15 15:12
We're trying a generalization of the workaround on Steam Flatpak level. It was just pushed out as an update

**Comment by alexlarsson** [comment] 2018-08-14 13:02
Closing this as it seems to be handled by the steam flatpak.

**Closed by alexlarsson** 2018-08-14 13:02 UTC

**Comment by bertogg** [comment] 2019-08-12 12:17
Hi, it seems that this problem affects other apps, see e.g. https://github.com/tiliado/nuvolaruntime/issues/376 and https://github.com/flathub/net.sf.fuse_emulator/issues/3

I suppose this can theoretically affect any app using Alsa, so are app developers expected to unset ALSA_CONFIG_PATH manually in all apps or should this be handled generically at the Flatpak level?

**Comment by nanonyme** [comment] 2019-08-12 12:35
Another option is runtime level

**Comment by bertogg** [comment] 2019-08-24 07:38
There's another slightly related problem: the `/usr/share/alsa/alsa.conf` file inside the Freedesktop runtime includes the `~/.asoundrc` file.

My impression is that in practice this file either doesn't exist (if the home directory is not shared) or it exists but it doesn't necessarily work with the Alsa setup inside the sandbox (a user just found this problem with net.sf.fuse_emulator).

I guess the most correct alternative would be not to share the home directory at all, and use portals for file access, but would removing `~/.asoundrc` from `/usr/share/alsa/alsa.conf` be a good idea anyway?
