### ISSUE TITLE
fcitx stop working at flatpak 1.0.0

### ISSUE THREAD

**Issue by nakamuray** [flatpak/flatpak#2031] opened 2018-08-28 06:48 UTC
## Linux distribution and version
ubuntu 18.04

## Flatpak version
1.0.0 (from `ppa:alexlarsson/flatpak`)

## Description of the problem
After upgrading flatpak from 0.99.3 to 1.0.0, I can't input japanese characters on slack app.
While fcitx (mozc) is activated (input method indicator is apeard around cursor), typing keyboard has no effect.
Downgrading to 0.99.3 bring back to expected behavior.

## Steps to reproduce
1. setup fcitx on host side
2. install slack app from flathub and run it
3. activate fcitx (mozc) and type something

**Comment by alexlarsson** [comment] 2018-08-28 08:04
Hmm, this is probably due to a small change in how the dbus proxy works that was made to future proof the portals. In particular, this commit: https://github.com/flatpak/flatpak/commit/ef9297a0f104365f3d94211c95ae594f67ad55d2

We used to allow sandboxed apps to receive all broadcasts from portals, but we now limit them to those under the /org/freedesktop/portal object path. I wonder if the fcitx portal was using this? If so, it would need to change the broadcast object paths.

**Comment by nakamuray** [comment] 2018-08-29 04:01
I confirmed that at least on flatpak 1.0.0 without ef9297a (rebuild deb package with patch which revert the commit), fcitx works as expected.

**Comment by alexlarsson** [comment] 2018-08-29 07:01
I realize this is a breaking change, but its unfortunately required for security reasons. However, it should be fixable, and If you have patches to fcitx I can apply them in the runtimes.

**Comment by trulyliu** [comment] 2018-10-09 08:43
I am also affected by this issue.
Should we patch fcitx?  How?

**Comment by nanonyme** [comment] 2019-04-06 13:27
@alexlarsson if we need changes in freedesktop-sdk, we should probably have a copy of this on that side, right?

**Comment by nanonyme** [comment] 2019-04-06 13:31
Opened https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/728 so this gets tracked on runtime-side as well.

**Comment by alexlarsson** [comment] 2019-04-12 13:08
So, I'm not sure exactly what needs to change, because I don't know exactly how fcitx clients talk to the fcitx portal daemon. However, what changed was a detail in which dbus messages was allowed by default.

It used to be the case that all direct messages to any dbus names called `org.freedesktop.portal.*` were allowed to be sent, and all broadcasts message from the same names are allowed to be received by the sandboxed. However, in later versions of flatpak the later has changed. Any broadcast from `org.freedesktop.portal.*` must now have an object path starting with `/org/freedesktop/portal` for it to be received by the sandboxed app.

**Comment by alexlarsson** [comment] 2019-04-12 13:10
If you want to see what fcitx does, run `dbus-monitor  --session` while running whatever is not working.
Alternatively you can `flatpak run --log-session-bus ...`, although the output from that isn't super-easy to understand.

**Comment by nanonyme** [comment] 2019-04-12 18:47
Maybe whoever can reproduce this should just collect the output and attach here for further analysis?

**Comment by daotrunghieu** [comment] 2019-04-15 21:28
Hello,

I'm using _fcitx_ as my input method and I found an approach helps me type freely in flatpak applications  has **runtime: org.kde.Platform/x86_64/5.12**

`$ flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app-id>`
or
`$ flatpak --user override --socket=session-bus <app-id>` (too much?)

In my system (flatpak-1.2.4-1.fc29), three applications were tested: com.slack.Slack; net.ankiweb.Anki; org.telegram.desktop.

**Comment by nanonyme** [comment] 2019-04-16 06:04
The latter is definitely too much, it's a blanket permission for granting access to everything in session bus.

**Comment by magiruuvelvet** [comment] 2019-04-16 18:54
I just tested `flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app-id>` on some apps and it works great. Thanks for figuring this out :heart: 

I'm on Arch Linux running the latest flatpak.

**Comment by nanonyme** [comment] 2019-04-16 19:12
@alexlarsson what's your opinion? Should apps that are most affected by this issue just be changed to request this permission? Do all apps need it?

**Comment by daotrunghieu** [comment] 2019-04-17 21:56
I double-check experiments on another apps, I have the outcome that adding
`--talk-name=org.freedesktop.portal.Fcitx`
is enough to let those apps work with fcitx:
- chat.rocket.RocketChat
- com.visualstudio.code
- com.mattermost.Desktop
- im.gitter.Gitter

and none succeeded:
- com.spotify.Client
- io.ark.Desktop

This is the output when run `flatpak run --log-session-bus`
[logs.tar.gz](https://github.com/flatpak/flatpak/files/3091712/logs.tar.gz)

**Comment by Mikaela** [comment] 2019-04-18 08:26
I confirmed that Riot, Telegram, Discord and Gajim also work when that is added and I sent pull requests as this issue has bothered me a lot with them especially with `backticks and code blocks`. Thank you everyone involved in finding what was wrong :purple_heart:

**Comment by alexlarsson** [comment] 2019-04-23 08:33
A --talk-name=org.freedesktop.portal.Fcitx will fix this because that is a wider permission than what the default portal one is. 

However, this is a security regression and should not be merged, as it just papers over the real problem which will then not be fixed, and will need every app to be modified with a hack that will be copied around forever.

**Comment by alexlarsson** [comment] 2019-04-23 08:36
Basically, the fix is that all the broadcast messages that the fcitx daemon sends have to use a object path that starts with `/org/freedesktop/portal`.

**Comment by nanonyme** [comment] 2019-04-23 08:43
Looks like there actually *is* a relevant upstream ticket at https://gitlab.com/fcitx/fcitx/issues/429

**Comment by trulyliu** [comment] 2019-10-21 03:36
flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx com.skype.Client
make skype works.

**Comment by BjoernDaase** [comment] 2019-11-01 23:36
I have the exact same problem in all my Jetbrains IDEs. Unfortunately, ```flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx com.jetbrains.Webstorm``` (or any other application of those) does not make the dead keys work again. Any ideas?

OS: Fedora 31

**Comment by nanonyme** [comment] 2019-11-02 08:38
This is a bug in fcitx. They seem to have removed means to contribute fixes to the project though so I'm not sure this will ever be fixed. They also removed issue tracker on fcitx. I'm not sure the project is alive anymore.

**Comment by wengxt** [comment] 2019-11-03 05:30
Just pushed relevant fix, need to check if that's the only change need to make https://github.com/fcitx/fcitx/commit/1f4c3a96cb2d1308581864676dd86ea6aa393ccb

**Comment by nanonyme** [comment] 2019-11-03 09:16
@wengxt note, regarding compatibility: the server part is shipped by distro while the library is shipped through Flatpak runtime. It's most likely not possible to be compatible but current situation is broken anyway pretty much everywhere.

**Comment by nanonyme** [comment] 2019-11-03 09:57
Thank you and sorry for above. I jumped to conclusions from repo configuration

**Comment by nanonyme** [comment] 2019-11-10 14:19
The fix by @wengxt is now integrated into all active freedesktop-sdk branches. It will be released Soon (tm) for 18.08 and 19.08.

**Comment by nanonyme** [comment] 2019-11-10 14:21
Note we realized that Gnome runtime is shipping a separate fcitx version so assuming all goes well with the freedesktop-sdk release, attention needs to next be focused into https://gitlab.gnome.org/GNOME/gnome-build-meta/issues. KDE should end up getting fixed by itself after a rebuild.

**Comment by refi64** [comment] 2020-01-30 00:00
To be clear, what else here needs to be done? Is it just pending a new fcitx server release with the linked commit?

**Comment by Quintasan** [comment] 2020-02-06 13:44
I am not sure if this is related but I can't even activate fcitx in Slack using the default Ctrl+Space combo.

I have run `flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx com.slack.Slack`

which then I verified by running

```
~ ➜ flatpak --user override --show com.slack.Slack
[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk
org.fcitx.Fcitx=talk
```

so my flatpak should have the appropriate permissions to talk to Fcitx. Fcitx itself works just fine on the host itself. Is there anything I misseD?

**Comment by Mikaela** [comment] 2020-02-07 21:38
Have you restarted Slack after adding the override? That is the only step you don't mention that I can see you as missing.

**Comment by Quintasan** [comment] 2020-02-08 03:42
I did not mention that but of course I did restart Slack :)

pt., 7 lut 2020, 22:38 użytkownik Mikaela Suomalainen <
notifications@github.com> napisał:

**Comment by yutouyes** [comment] 2020-04-15 12:32
The trick 'flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app id>' doesn't work in Crostini(Chrome OS). Tested in Firefox and vscode.

**Comment by luni3359** [comment] 2020-04-15 16:01
> The trick `flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app id>` doesn't work in Crostini(Chrome OS). Tested in Firefox and vscode.

Your fcitx needs to be on version 4.2.9.7 to work with flatpak.

**Comment by yutouyes** [comment] 2020-04-16 09:35
> > The trick `flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app id>` doesn't work in Crostini(Chrome OS). Tested in Firefox and vscode.
> 
> Your fcitx needs to be on version 4.2.9.7 to work with flatpak.

I've upgraded to 4.2.9.7-3 but still broke. Is everything ok in your crostini?

**Comment by wengxt** [comment] 2020-04-16 16:08
> > > The trick `flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app id>` doesn't work in Crostini(Chrome OS). Tested in Firefox and vscode.
> > 
> > 
> > Your fcitx needs to be on version 4.2.9.7 to work with flatpak.
> 
> I've upgraded fcitx to 4.2.9.7-3 but still broke. Is everything ok in your crostini?

I just tried firefox from flathub on archlinux and everything works fine. So probably you just had a regular fcitx configuration problem? BTW, no "talk-name" argument is required anymore.

Try set GTK_IM_MODULE before run flatpak, also see https://fcitx-im.org/wiki/Configure_(Other)

**Comment by yutouyes** [comment] 2020-04-17 01:25
> > > > The trick `flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app id>` doesn't work in Crostini(Chrome OS). Tested in Firefox and vscode.
> > > 
> > > 
> > > Your fcitx needs to be on version 4.2.9.7 to work with flatpak.
> > 
> > 
> > I've upgraded fcitx to 4.2.9.7-3 but still broke. Is everything ok in your crostini?
> 
> I just tried firefox from flathub on archlinux and everything works fine. So probably you just had a regular fcitx configuration problem? BTW, no "talk-name" argument is required anymore.
> 
> Try set GTK_IM_MODULE before run flatpak, also see https://fcitx-im.org/wiki/Configure_(Other)

I've set that and fIrefox from apt-get can catch fcitx correctly. I'm not sure if it's the problem of crostini or just my mistake because before flatpak, snap also came to an error ``` cannot update snap namespace: cannot create writable mimic over "/usr/share/"``` which is not reported in the community. Your archlinux is running in crostini right?

**Comment by teohhanhui** [comment] 2020-06-21 15:01
Looks like kimpanel also has the same problem:

    $ dbus-monitor --session
```
signal time=1592751473.282050 sender=:1.93 -> destination=(null destination) serial=1221311 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=ShowAux
   boolean false
signal time=1592751473.282057 sender=:1.93 -> destination=(null destination) serial=1221312 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=ShowPreedit
   boolean false
signal time=1592751473.282072 sender=:1.93 -> destination=(null destination) serial=1221313 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=ShowLookupTable
   boolean false
```

This seems to be something that needs to be fixed on Flatpak side, instead of expecting everybody else to change their paths?

**Comment by ccshao** [comment] 2020-07-06 08:53
Hello, any updates on this topic? Here in xfce4, opensuse. Fcitx not working in flatpak apps like firefox, Mark Text ...
I have tried the following command suggested by above threads,

```
 flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx org.mozilla.firefox
```

However, fcitx still doesn't work in flatpak apps, only work in stock firefox.

**Comment by nanonyme** [comment] 2020-07-06 10:35
The talk-name workaround is no longer relevant. Which version of fcitx do you have on host?

**Comment by ccshao** [comment] 2020-07-07 09:41
Fcitx 4.2.9.6-lp152.3.12, with flatpak 1.6.3 in opensuse.
________________________________

**Comment by Iey4iej3** [comment] 2020-07-07 12:13
For me: flatpak 1.6.2-1 in Debian Buster Backports, fcitx 4.2.9.6-5.

**Comment by wengxt** [comment] 2020-07-07 21:06
to put it simple, you'll need 4.2.9.7 to make it work. Because fcitx im module in flatpak is from 4.2.97 and using a different dbus object path. It need to be the same version of fcitx on your host.

**Comment by Iey4iej3** [comment] 2020-07-08 06:54
Is that configurable? I mean, a config file in which contains different dbus object paths for different apps needed.

**Comment by ntninja** [comment] 2020-08-31 14:32
@ley4iej3: It is not configurable, but you could ask the Debian maintainers to add https://github.com/fcitx/fcitx/commit/1f4c3a96cb2d1308581864676dd86ea6aa393ccb as a patch in Buster. See the issue tracker at: 
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=fcitx;dist=buster

(You can report Debian bugs using `reportbug fcitx` on the commandline.)

**Comment by Aspire1Inspire2** [comment] 2021-03-16 12:06
> to put it simple, you'll need 4.2.9.7 to make it work. Because fcitx im module in flatpak is from 4.2.97 and using a different dbus object path. It need to be the same version of fcitx on your host.

Could you share how to diagnose the supported fcitx module version in my flatpak? Many thanks!

**Comment by nanonyme** [comment] 2021-03-16 22:16
@Aspire1Inspire2 it should just work out of the box assuming your *host* has flatpak 4.2.9.7 or newer.

**Comment by wengxt** [comment] 2021-03-21 00:46
shall we just close this?

Originally it was caused by an upstream change in flatpak that requires fcitx to make some necessary changes. Now things are all implemented and released, so I don’t think there’s anything more need to be done in fcitx/flatpak.

If you still have problem: 
1. upgrade your system, or ask distro to upgrade or back port relevant code.
2. if the flatpak app you’re using is using an extremely old runtime that doesn’t have the update, then ask the app distributor to make the upgrade.
(Some other possible workaround may includes using fcitx5 from flatpak because it’s really new.. etc)

There’s nothing else can be done or need to be done in fcitx/flatpak.

**Comment by JayXT** [comment] 2022-01-07 13:41
> Hello,
> 
> I'm using _fcitx_ as my input method and I found an approach helps me type freely in flatpak applications has **runtime: org.kde.Platform/x86_64/5.12**
> 
> `$ flatpak --user override --talk-name=org.fcitx.Fcitx --talk-name=org.freedesktop.portal.Fcitx <app-id>` or `$ flatpak --user override --socket=session-bus <app-id>` (too much?)
> 
> In my system (flatpak-1.2.4-1.fc29), three applications were tested: com.slack.Slack; net.ankiweb.Anki; org.telegram.desktop.

What talk-name would you use for fcitx5?

**Comment by nanonyme** [comment] 2022-01-07 13:51
@wengxt yes, this should be closed. The original problem is fixed.

**Comment by nanonyme** [comment] 2022-01-07 13:52
@JayXT fcitx uses a portal, you must not use talk name. If it doesn't work, create new bug report after ensuring your host software is up to date.

**Comment by JayXT** [comment] 2022-01-07 13:58
@nanonyme, thanks for the response. I'm currently facing an issue with fcitx5 mozc input in Anki flatpak, which seemed somehow related to this thread. The OS (Debian 11) is up-to-date, some [recommendations](https://github.com/flathub/net.ankiweb.Anki/issues/42) like running the following command haven't resulted in any improvements.
`flatpak override --user --env=IBUS_USE_PORTAL=1 net.ankiweb.Anki`
I wonder whether there is any special portal that enables interaction with fcitx5.

**Comment by nanonyme** [comment] 2022-01-07 14:08
In case it matters, net.ankiweb.Anki is using fcitx4.

**Comment by JayXT** [comment] 2022-01-07 14:11
@nanonyme , is it something specific just to Flatpak version of Anki? Because its older version in Debian repos (2.1.15) despite other issues seems to work fine with fcitx5.

**Comment by nanonyme** [comment] 2022-01-07 14:12
net.ankiweb.Anki is built against a runtime that provides fcitx4, not fcitx5. It should potentially be runtime bumped.

**Comment by JayXT** [comment] 2022-01-07 14:16
Under runtime you mean the version of KDE platform in its build yaml file?
![image](https://user-images.githubusercontent.com/8045344/148556554-4fd05053-0d84-44af-9e00-3c1cf578d586.png)

**Comment by nanonyme** [comment] 2022-01-07 14:25
Yes, there's a newer runtime 5.15-21.08 which has fcitx5.

**Closed** 2022-01-07 18:42 UTC
Labels: bug

**Comment by rokejulianlockhart** [comment] 2023-02-06 20:58
Since this is closed, has it been remediated?

I ask because [upstream](https://gitlab.com/fcitx/fcitx/-/issues/429) it remains open, and on flatkill.org, it remains mentioned as open.

**Comment by wengxt** [comment] 2023-02-06 21:07
The fcitx upstream is using github again for some time. gitlab is only left for archive purpose.

I problably should disable the issue on gitlab.

**Comment by nanonyme** [comment] 2023-02-06 22:53
@rokejulianlockhart flatkill.org is maintained by people who are against flatpak. I doubt it will ever be fixed to be correct.
