### ISSUE TITLE
Sandbox exemption of --devices=all is too permissive when only USB access is desired

### ISSUE THREAD

**Issue by resotek** [flatpak/flatpak#3016] opened 2019-07-18 20:15 UTC
## Linux distribution and version
Probably all versions, but in my case:
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
Linux version 4.15.0-54-generic
## Flatpak version
Flatpak 1.0.8
## Description of the problem
Currently flatpak applications cannot access the serial ports without granting the application `--device=all`. This is particularly a problem with Visual Studio Code with the PlatformIO plugin. The flatpak sandbox prevents accessing any USB device unless the user entrusts Microsoft's Visual Studio Code access to **all** devices via `run --device=all`. That is too much trust to place on a Microsoft product with so many notorious telemetry features. Consequently, PlatformIO in a Visual Studio Code flatpak is unusable for programming USB devices. VS Code with PlatformIO is becoming a very popular way to develop code with the Arduino libraries. The current work-around of --device=all doesn't seem that different than installing the VS Code .deb distribution outside of flatpak. 
## Steps to reproduce
Run Visual Studio as a flatpak with PlatformIO plugin without --device=all and try to access a USB port, and observe that you are unable to do so. I presume the same applies to any flatpak application.
## Proposed solution
Support a sandbox exemption of a specific device, or group of devices. For example:
`--device=/dev/devicename` e.g. `/dev/ttyUSB0` or `/dev/ttyUSB*` 
or `--device=file=/path/to/file/with/whitelisteddevices`
or `device=group=dialout` for serial port access.

**Comment by mwleeds** [comment] 2019-07-19 17:36
Thanks for the bug report, but this is a duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/227

**Closed by mwleeds** 2019-07-19 17:36 UTC
