### ISSUE TITLE
Segmentation fault installing flatpaks fedora 30

### ISSUE THREAD

**Issue by Wrexthor** [flatpak/flatpak#2984] opened 2019-06-26 06:52 UTC
## Linux distribution and version
Fresh install of fedora 30
Linux 5.1.12-300.fc30.x86_64 x86_64
Using btrfs encrypted with luks

## Flatpak version
Flatpak 1.4.1

## Description of the problem
Using flatpak install causes segmentation fault (from flathub), using gnome software crashes the software app.

From logs
```bash
08:34:49 systemd-coredum: Process 14620 (flatpak) of user 1000 dumped core.

Stack trace of thread 14620:
#0  0x00007f5ca707f764 n/a (libcurl.so.4)
#1  0x00007f5ca707fa3b curl_multi_socket_action (libcurl.so.4)
#2  0x00007f5ca7f9a37a n/a (libostree-1.so.1)
#3  0x00007f5ca79deedd g_main_context_dispatch (libglib-2.0.so.0)
#4  0x00007f5ca79df270 n/a (libglib-2.0.so.0)
#5  0x00007f5ca79df313 g_main_context_iteration (libglib-2.0.so.0)
#6  0x00007f5ca7f617da ostree_repo_pull_with_options (libostree-1.so.1)
#7  0x0000559640104bfc n/a (flatpak)
#8  0x000055964011d31c n/a (flatpak)
#9  0x000055964012a0e3 n/a (flatpak)
#10 0x0000559640154072 n/a (flatpak)
#11 0x00005596400ea68e n/a (flatpak)
#12 0x00005596400c00a8 n/a (flatpak)
#13 0x00005596400b70b5 n/a (flatpak)
#14 0x00007f5ca77aff33 __libc_start_main (libc.so.6)
#15 0x00005596400b7bde n/a (flatpak)

Stack trace of thread 14658:
#0  0x00007f5ca787c5c7 __poll (libc.so.6)
#1  0x00007f5ca79df1de n/a (libglib-2.0.so.0)
#2  0x00007f5ca79df313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f5c98385a9d n/a (libdconfsettings.so)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14621:
#0  0x00007f5ca787c5c7 __poll (libc.so.6)
#1  0x00007f5ca79df1de n/a (libglib-2.0.so.0)
#2  0x00007f5ca79df313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f5ca79df361 n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14743:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14622:
#0  0x00007f5ca787c5c7 __poll (libc.so.6)
#1  0x00007f5ca79df1de n/a (libglib-2.0.so.0)
#2  0x00007f5ca79df5a3 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f5ca7c25d5a n/a (libgio-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14741:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14742:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14733:
#0  0x00007f5ca7965b4f __write (libpthread.so.0)
#1  0x00007f5ca7fa558e n/a (libostree-1.so.1)
#2  0x00007f5ca7f4c6cf n/a (libostree-1.so.1)
#3  0x00007f5ca7f4e9bb n/a (libostree-1.so.1)
#4  0x00007f5ca7f5142d ostree_repo_write_content (libostree-1.so.1)
#5  0x00007f5ca7f514f2 n/a (libostree-1.so.1)
#6  0x00007f5ca7ba879d n/a (libgio-2.0.so.0)
#7  0x00007f5ca7b8eaee n/a (libgio-2.0.so.0)
#8  0x00007f5ca7bbd8f7 n/a (libgio-2.0.so.0)
#9  0x00007f5ca7a08f14 n/a (libglib-2.0.so.0)
#10 0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#11 0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#12 0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14740:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14623:
#0  0x00007f5ca787c5c7 __poll (libc.so.6)
#1  0x00007f5ca79df1de n/a (libglib-2.0.so.0)
#2  0x00007f5ca79df5a3 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f5ca822e9e7 n/a (libpolkit-agent-1.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14744:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14739:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)

Stack trace of thread 14745:
#0  0x00007f5ca7881fad syscall (libc.so.6)
#1  0x00007f5ca7a2af4e g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f5ca79b0031 n/a (libglib-2.0.so.0)
#3  0x00007f5ca7a0906a n/a (libglib-2.0.so.0)
#4  0x00007f5ca7a084e2 n/a (libglib-2.0.so.0)
#5  0x00007f5ca795c5a2 start_thread (libpthread.so.0)
#6  0x00007f5ca7887303 __clone (libc.so.6)
```

## Steps to reproduce
```bash
flatpak install flathub com.visualstudio.code.oss
Looking for matches…
Required runtime for com.visualstudio.code.oss/x86_64/stable (runtime/org.freedesktop.Sdk/x86_64/18.08) found in remote flathub
Do you want to install it? [Y/n]: y

com.visualstudio.code.oss permissions:
    ipc                   network              pulseaudio      ssh-auth      x11      dri
    file access [1]       dbus access [2]

    [1] host
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications


        ID                                            Arch          Branch        Remote         Download
 1. [—] org.freedesktop.Sdk                           x86_64        18.08         flathub           22,6 MB / 595,5 MB
 2. [ ] org.freedesktop.Sdk.Locale                    x86_64        18.08         flathub        < 319,3 MB (partial)
 3. [ ] org.gtk.Gtk3theme.Adwaita-dark                x86_64        3.22          flathub          < 1,5 kB
 4. [ ] org.freedesktop.Platform.html5-codecs         x86_64        18.08         flathub          < 2,9 MB
 5. [ ] org.freedesktop.Platform.VAAPI.Intel          x86_64        18.08         flathub          < 1,8 MB
 6. [ ] com.visualstudio.code.oss                     x86_64        stable        flathub         < 68,5 MB

Installing 1/6… ██▊                   14%  940,5 kB/s  02:27Segmentation fault (core dumped)
```

**Comment by mwleeds** [comment] 2019-06-27 22:26
Maybe a bug report should be filed against libcurl? That seems to be where the seg fault happens. It would also be useful to have more debugging symbols (which I think would be `dnf debuginfo-install libcurl`).

**Comment by mwleeds** [comment] 2019-06-27 22:28
Oh, looks like this is a duplicate of https://github.com/flatpak/flatpak/issues/2977

**Closed by mwleeds** 2019-06-27 22:28 UTC
