### ISSUE TITLE
Error: Error deploying: While trying to checkout.... Couldn't find file object....

### ISSUE THREAD

**Issue by devJ0n** [flatpak/flatpak#4116] opened 2021-02-11 21:02 UTC
## Linux distribution and version
Manjaro Linux 20.2.1
## Flatpak version
Flatpak 1.10.1
## Description of the problem
I started Pamac GUI application to install com.visualstudio.code from "flathub" remote, during the installation I by accident pushed the cancel button which reverted the transaction, then I pressed on the install button once again. Then I get a message saying "Transaction successfully" within the Pamac GUI application, but the log message from Pamac GUI in Manjaro Linux:

> Installing runtime/org.freedesktop.Sdk/x86_64/20.08
> 2 metadata, 0 content objects fetched; 592 B transferred in 0 seconds
> While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-Y2RNY0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'
> Skipping com.visualstudio.code/x86_64/stable due to previous error
> Transaction successfully finished.

I get the same error when trying to install using the Flatpak CLI:

> [admin@laptop ~]$ flatpak install com.visualstudio.code
> Looking for matches…
> Found similar ref(s) for ‘com.visualstudio.code’ in remote ‘flathub’ (system).
> Use this remote? [Y/n]: y
> Required runtime for com.visualstudio.code/x86_64/stable (runtime/org.freedesktop.Sdk/x86_64/20.08) found in remote flathub
> Do you want to install it? [Y/n]: y
> 
> com.visualstudio.code permissions:
>    ipc                      network                         pulseaudio         ssh-auth
>    x11                      devices                         devel              file access [1]
>    dbus access [2]          system dbus access [3]          tags [4]
> 
>    [1] host, xdg-config/kdeglobals:ro
>    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*, org.freedesktop.Flatpak,
>        org.freedesktop.Notifications, org.freedesktop.secrets
>    [3] org.freedesktop.login1
>    [4] proprietary
> 
> 
>  ID                             Branch          Op          Remote          Download
>  1. [✗] org.freedesktop.Sdk            20.08           i           flathub            1,0 kB / 563,3 MB
>  2. [  ] com.visualstudio.code          stable          i           flathub         < 70,2 MB
> 
> Error: Error deploying: While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-ID00Y0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'
> error: Failed to install org.freedesktop.Sdk: Error deploying: While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-ID00Y0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'

> [admin@laptop ~]$ flatpak install org.freedesktop.Sdk//20.08
> Looking for matches…
> Found similar ref(s) for ‘org.freedesktop.Sdk//20.08’ in remote ‘flathub’ (system).
> Use this remote? [Y/n]: y
> 
>  ID                           Branch          Op         Remote          Download
>  1. [✗] org.freedesktop.Sdk          20.08           i          flathub         1,0 kB / 563,3 MB
> 
> Error: Error deploying: While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-VL6GY0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'
> error: Failed to install org.freedesktop.Sdk: Error deploying: While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-VL6GY0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'

## Steps to reproduce
1.) Install com.visualstudio.code using the Pamac GUI application, press cancel during installation.
2.) Press install button again.
3.) com.visualstudio.code can't be installed due to corrupt state with the runtime org.freedesktop.Sdk//20.08

**Comment by devJ0n** [comment] 2021-02-11 21:04
Have tried to run

> flatpak repair
> flatpak repair --user
> flatpak uninstall --unused
> flatpak update --appstream

**Comment by devJ0n** [comment] 2021-02-18 20:50
Also tried a verbose install of the runtime.

> [admin@laptop ~]$ flatpak --verbose install org.freedesktop.Sdk//20.08
> F: No installations directory in /etc/flatpak/installations.d. Skipping
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /home/admin/.local/share/flatpak
> Looking for matches…
> F: Fetching summary index file for remote ‘flathub’
> F: Loading https://dl.flathub.org/repo/summary.idx using libsoup
> F: Received 2737 bytes
> F: Loaded indexed summary file 7c8c930658a6c0619072c39c8c8120797695338ca1d602a9c434ab92de23ca2a from cache for remote ‘flathub’
> Found similar ref(s) for ‘org.freedesktop.Sdk//20.08’ in remote ‘flathub’ (system).
> Use this remote? [Y/n]: y
> F: Fetching summary index file for remote ‘flathub’
> F: Loading https://dl.flathub.org/repo/summary.idx using libsoup
> F: Received 2737 bytes
> F: Loaded indexed summary file 7c8c930658a6c0619072c39c8c8120797695338ca1d602a9c434ab92de23ca2a from cache for remote ‘flathub’
> F: Transaction: install flathub:runtime/org.freedesktop.Sdk/x86_64/20.08[*]
> F: Calling system helper: Configure
> F: Looking for remote metadata updates for flathub
> F: marking op install:runtime/org.freedesktop.Sdk/x86_64/20.08 resolved to 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64
> F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/20.08[*]
> F: Transaction: install/update flathub:runtime/org.freedesktop.Sdk.Locale/x86_64/20.08[/en, /sv]
> F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.openh264/x86_64/2.0[*]
> F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/20.08[*]
> F: marking op install/update:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/20.08 resolved to 8951f6afb4bb638fd65b85519bfbec7bc932f2928719a743eb339436a928b4e0
> F: marking op install/update:runtime/org.freedesktop.Platform.openh264/x86_64/2.0 resolved to 73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b
> F: marking op install/update:runtime/org.freedesktop.Sdk.Locale/x86_64/20.08 resolved to a9459062b34eba0511b8298e9a0382618891e05d132e2be5da482e2221a541f2
> F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 resolved to ca66fdbf87dd110c2e2063ab090db5cc426b055c2252775c8e2d28a4ec15556b
> 
> 
>  1.	   	org.freedesktop.Sdk	20.08	i	flathub	< 563,3 MB
> 
> Proceed with these changes to the system installation? [Y/n]: y
> Installing…                                                                                         F: Calling system helper: GetRevokefsFd
> F: Calling system helper: GetRevokefsFd
> F: flatpak_dir_pull: Using commit 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 for pull of ref runtime/org.freedesktop.Sdk/x86_64/20.08 from remote flathub
> 
> Installing…                        0%  0 bytes/s
> Installing… ████████████████████ 100%F: Calling system helper: Deploy
> Error: Error deploying: While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-DRHSY0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'
> error: Failed to install org.freedesktop.Sdk: Error deploying: While trying to checkout 305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64 into /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/20.08/.305a04169e9092e7c31a0fde61c185d01e18dc1e8a710aac1e02e8479330ed64-DRHSY0: Opening content object 39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04: Couldn't find file object '39e10c8d60a3debb1a2a497499b0404c9d40bb049a385a9515c5e1da162d8e04'

**Comment by leanndroguedes** [comment] 2021-02-21 23:28
> Have tried to run the following commands without resolving my issue.
> 
> > flatpak repair
> > flatpak repair --user
> > flatpak uninstall --unused
> > flatpak update --appstream

worked perfectly

**Comment by willyywt** [comment] 2021-02-25 08:38
According to ``man flatpak-repair``, it should be run with root privileges to operate on the system installation. It seems to run without root privileges, but actually it doesn't repair them.

**Comment by willyywt** [comment] 2021-02-25 09:13
I think this is just a common case for many flatpak users without prefect internet connection. As far as I see, flatpak cannot automatically recover from bad installations (or pick up where the download was interrupted).
I see a similar issue #3952 Implement more robust download of dependencies

**Comment by leocadiomichael** [comment] 2021-04-17 05:08
> According to `man flatpak-repair`, it should be run with root privileges to operate on the system installation. It seems to run without root privileges, but actually it doesn't repair them.

Worked for me!

**Comment by vchernin** [comment] 2021-07-22 22:40
For reference:

For Flatpaks installed as user (this operates on your current user):
`flatpak repair --user`

For Flatpaks install system-wide (this one needs root):
`sudo flatpak repair`

Try both if you're not sure.
Generally in Flatpak you don't want to run with root, this is one case where root might be needed.

**Comment by elmarco** [comment] 2021-07-26 14:07
It didn't work for me:

```
$ flatpak repair --user                                  
[10/33] Verifying flathub:app/net.mediaarea.MediaInfo/x86_64/stable…
[15/33] Verifying gnome-nightly:runtime/org.gnome.Polari.Locale/x86_64/master…
Checking remotes...
Pruning objects

$ flatpak install  gnome-nightly org.gnome.Sdk
Looking for matches…


        ID                     Branch          Op         Remote                Download
 1. [✗] org.gnome.Sdk          master          i          gnome-nightly         1,0 kB / 608,9 MB

Error: While trying to checkout b06b9e3b7f00b25648fd68e8857bf7eb81ca4d26fdbc404b011333ded524a761 into /home/elmarco/.local/share/flatpak/runtime/org.gnome.Sdk/x86_64/master/.b06b9e3b7f00b25648fd68e8857bf7eb81ca4d26fdbc404b011333ded524a761-P31V60: Opening content object 07ad6c2c958b6c9cb819243eb7321f9fd595dd71794d2725a1fdccaabc391c91: Couldn't find file object '07ad6c2c958b6c9cb819243eb7321f9fd595dd71794d2725a1fdccaabc391c91'
error: Failed to install org.gnome.Sdk: While trying to checkout b06b9e3b7f00b25648fd68e8857bf7eb81ca4d26fdbc404b011333ded524a761 into /home/elmarco/.local/share/flatpak/runtime/org.gnome.Sdk/x86_64/master/.b06b9e3b7f00b25648fd68e8857bf7eb81ca4d26fdbc404b011333ded524a761-P31V60: Opening content object 07ad6c2c958b6c9cb819243eb7321f9fd595dd71794d2725a1fdccaabc391c91: Couldn't find file object '07ad6c2c958b6c9cb819243eb7321f9fd595dd71794d2725a1fdccaabc391c91'

```

**Comment by vchernin** [comment] 2021-07-26 17:28
Could you also try `sudo flatpak repair`

**Comment by cod3g3nki** [comment] 2021-09-24 02:31
It seems like `flatpak` can't handle installation/update failures gracefully. The only way out of this situation, to my knowledge, is to remove the app directory and reinstall the app. First to remove the app directory, in case of system space:
```
rm -r /var/lib/flatpak/app/org.Publisher.AppName
# or for runtime
rm -r /var/lib/flatpak/runtime/org.Publisher.AppName
```
and for userspace:
```
rm -r $HOME/.local/share/flatpak/{app,runtime}/org.Publisher.AppName
# or for runtime
rm -r $HOME/.local/share/flatpak/runtime/org.Publisher.AppName
```
Then just install the app/runtime as usual:
```
flatpak install flathub AppName
```
Apparently, these steps don't disturb the app data & state.

**Comment by codewiz** [comment] 2021-11-21 19:49
I corrupted my Signal install when the Internet connection died in the middle of an update, and now it won't complete:

```
% flatpak update --user
Looking for updates…


        ID                         Branch         Op         Remote          Download
 1. [✗] org.signal.Signal          stable         u          flathub         1.0 kB / 152.4 MB

Error: While trying to checkout 55a13b24fde201735814eb335f1485ac73a0fd4f4cad5b9ca96b45a5dcab17da into /home/bernie/.local/share/flatpak/app/org.signal.Signal/x86_64/stable/.55a13b24fde201735814eb335f1485ac73a0fd4f4cad5b9ca96b45a5dcab17da-2SH7C1: Opening content object f1e4a7474801403e60698f2567a6b7a9d5e274ef1eb14d6eaeb6569cedbf418e: Couldn't find file object 'f1e4a7474801403e60698f2567a6b7a9d5e274ef1eb14d6eaeb6569cedbf418e'
Updates complete.
error: There were one or more errors
```

It seems repair would fix it by deleting Signal:
```
% flatpak repair --dry-run --user
[7/82] Verifying flathub:app/org.signal.Signal/x86_64/stable…
Object missing: f1e4a7474801403e60698f2567a6b7a9d5e274ef1eb14d6eaeb6569cedbf418e.file
Dry run: Deleting ref flathub:app/org.signal.Signal/x86_64/stable due to missing objects
[32/82] Verifying flathub:runtime/org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources/x86_64/5.15…
[82/82] Verifying flathub:runtime/org.kde.Platform.Locale/x86_64/5.15-21.08…
Checking remotes...
```

This is flatpak-1.12.2-1.fc36.x86_64 with ostree-libs-2021.5-2.fc36.x86_64.

**Comment by mwleeds** [comment] 2021-11-22 16:57
> It seems repair would fix it by deleting Signal:

This would leave your user data untouched, so if you run repair without `--dry-run`, it should reinstall Signal and you will not lose your chat history.

**Comment by kokizzu** [comment] 2021-12-26 05:41
```
flatpak update
Looking for updates…

ID                                           Branch          Op          Remote          Download
1. [✗] org.freedesktop.Platform.GL.default          21.08           i           flathub         1.0 kB / 131.2 MB

Warning: While trying to checkout 031dc8a64a8fc1ed5819295270af05241a8982b0e0a48cd6f53fd69704cbb437 into /home/kyz/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/21.08/.031dc8a64a8fc1ed5819295270af05241a8982b0e0a48cd6f53fd69704cbb437-NRGVE1: Opening content object 7bac0642b4f52436c1a2c25ec43c7680d8da356d08c9c38bb945aa1072237f5e: Couldn't find file object '7bac0642b4f52436c1a2c25ec43c7680d8da356d08c9c38bb945aa1072237f5e'
Installation complete.
```

removing that file also doesn't work, but @devJ0n  comment works
```
flatpak repair
flatpak repair --user
flatpak uninstall --unused
flatpak update --appstream
flatpak update
```

**Comment by luanmarques1789** [comment] 2022-04-05 23:18
> According to `man flatpak-repair`, it should be run with root privileges to operate on the system installation. It seems to run without root privileges, but actually it doesn't repair them.

**It works** for me and resolved my prob! Thanks!

**Comment by mwleeds** [comment] 2022-04-06 01:32
Closing this as I believe it's a duplicate of #3479: a different error message but same root cause.

**Closed by mwleeds** 2022-04-06 01:32 UTC

**Comment by SolarianZ** [comment] 2023-02-16 01:45
> Have tried to run the following commands without resolving my issue.
> 
> > flatpak repair
> > flatpak repair --user
> > flatpak uninstall --unused
> > flatpak update --appstream

Works on my Steam Deck!
