### ISSUE TITLE
bwrap: Can't make symlink at /var/run: File exists

### ISSUE THREAD

**Issue by KD0BPV** [flatpak/flatpak#2200] opened 2018-10-06 13:40 UTC
## Linux distribution and version
Gentoo testing
## Flatpak version
1.0.2, 1.0.3, 1.0.6
## Description of the problem
Some apps fail to start with error `bwrap: Can't make symlink at /var/run: File exists`
So far, I've had this issue with org.nextcloud.Nextcloud , com.github.wwmm.pulseeffects, com.discordapp.Discord
## Steps to reproduce
1. flatpak install org.nextcloud.Nextcloud
2. flatpak run org.nextcloud.Nextcloud

**Comment by alexlarsson** [comment] 2018-10-08 10:29
I believe this might be fixed by #2160, which is in the 1.0.3 release. Can you test that?

**Comment by KD0BPV** [comment] 2018-10-10 21:02
1.0.3 isn't available on the `flatpak-overlay` yet, but I'll try a manual build and see what happens.

**Comment by KD0BPV** [comment] 2018-10-10 22:46
Issue still exists with 1.0.3. On a whim, I tried running Nextcloud again via `sudo flatpak run org.nextcloud.Nextcloud` and that worked. As such, I then rolled back to 1.0.2-r1 from `flatpak-overlay` and tried it there. Nextcloud worked with that too. Looking at the ebuild, it looks like the fix you were talking about was [backported to 1.0.2](https://data.gpo.zugaina.org/flatpak-overlay/sys-apps/flatpak/files/). I think this rules out #2160 as the cause?

**Comment by YogSottot** [comment] 2018-10-28 16:39
> flatpak run org.telegram.desktop
> bwrap: Can't make symlink at /var/run: File exists
> Flatpak 1.0.4

gentoo

**Comment by KD0BPV** [comment] 2018-12-21 18:12
Now I'm getting this with com.discordapp.Discord too, which was working perfectly just yesterday.

**Comment by sumdog** [comment] 2019-01-28 20:50
I'm experiencing this problem currently on Gentoo:

```
layman -o https://raw.githubusercontent.com/fosero/flatpak-overlay/master/repositories.xml -f -a flatpak-overlay
emerge -av flatpak
flatpak install --user flathub com.github.bleakgrey.tootle
flatpak run com.github.bleakgrey.tootle
bwrap: Can't make symlink at /var/run: File exists
```

I'm running flatpak-1.0.6

What's the current workaround for this issue?

**Comment by sumdog** [comment] 2019-01-28 21:34
I realized that my Gentoo overlay hadn't synced correctly for some reason and I didn't have the option of flatpak 1.2.0. I have since added it to accept keyword, ran `flatpak uninstall tootle` and then reinstalled it. I still run into the same issue:

![selection_245](https://user-images.githubusercontent.com/156601/51867826-19c16900-2312-11e9-96dd-63d4f8c3f794.png)

flatpak: 1.2.0
ostree: 2019.1

**Comment by duckinator** [comment] 2019-02-01 16:31
Running into the same problem with com.slack.Slack from flathub on Fedora 29.

I do _not_ have the problem with org.signal.Signal from flathub, on the same system.

**Comment by ph1lt0r** [comment] 2019-02-01 19:01
I have the same exact issue on Gentoo Linux as well on flatpak 1.0.6 (what's in the gentoo overlay). I am running the moonlight game streaming application. However, if I xhost and run as root, it will work.

**Comment by duckinator** [comment] 2019-02-26 00:19
After seeing PR #2710, and that it was supposed to fix it by basically resolving the symlink, I figured out a workaround: When running things via flatpak, change `$XDG_RUNTIME_DIR` to use the real path.

E.g.,

```
~$ echo $XDG_RUNTIME_DIR 
/var/run/user/1000
~$ file /var/run
/var/run: symbolic link to ../run
~$ org.gnome.Fractal 
bwrap: Can't make symlink at /var/run: File exists
~$ env XDG_RUNTIME_DIR=/run/user/1000 org.gnome.Fractal
~$
```

**Comment by omichalek** [comment] 2019-02-26 13:14
> 
> 
> After seeing PR #2710, and that it was supposed to fix it by basically resolving the symlink, I figured out a workaround: When running things via flatpak, change `$XDG_RUNTIME_DIR` to use the real path.
> 
> E.g.,
> 
> ```
> ~$ echo $XDG_RUNTIME_DIR 
> /var/run/user/1000
> ~$ file /var/run
> /var/run: symbolic link to ../run
> ~$ org.gnome.Fractal 
> bwrap: Can't make symlink at /var/run: File exists
> ~$ env XDG_RUNTIME_DIR=/run/user/1000 org.gnome.Fractal
> ~$
> ```

Thank you for the tip!

A suggestion for the developers: put a mention of the XDG_RUNTIME_DIR variable into the error message!

**Comment by TingPing** [comment] 2019-02-26 13:40
Anyway this can be closed, it will be fixed in the next release. Workaround above in the meantime.

**Closed by TingPing** 2019-02-26 13:40 UTC
Labels: sandbox

**Comment by probonopd** [comment] 2019-09-15 09:54
I am runnnig into this as well:

```
cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

sudo apt-get -y install flatpak

flatpak install flathub org.gnome.gedit
flatpak run org.gnome.gedit

bwrap: Can't make symlink at /var/run: File exists
```

**Comment by probonopd** [comment] 2019-09-15 10:02
Now for something more drastic:

```
sudo rm -rf /var/run

flatpak run org.gnome.gedit

(...)

(flatpak run:12992): GLib-GIO-CRITICAL **: 12:01:55.475: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

** (flatpak run:12992): CRITICAL **: 12:01:55.475: polkit_authority_register_authentication_agent_with_options_sync: assertion 'POLKIT_IS_AUTHORITY (authority)' failed
Segmentation fault
```

**Comment by probonopd** [comment] 2019-09-15 10:40
Same result on Ubuntu 19.04 (Disco Dingo) Live ISO:

https://asciinema.org/a/XSmQ2WY4ha9T5ebKm5PBy3AwE

**Comment by refi64** [comment] 2019-09-15 13:35
`sudo rm -rf /var/run` basically just deleted almost every daemon communication socket, it's kinda a miracle your system didn't crash.

**Comment by probonopd** [comment] 2019-09-15 13:37
I have just done this on a Live ISO (like I do all of my computing), so after the next reboot the system is in factory-new state.

**Comment by tallero** [comment] 2020-01-17 14:31
>sudo rm -rf /var/run basically just deleted almost every daemon communication socket, it's kinda a miracle your system didn't crash.

If you do that by mistake, remember to give
```
ln -s /run/dbus /var/run/dbus
```

**Comment by tallero** [comment] 2020-03-02 09:39
This still happens on Archlinux as of today.

**Comment by probonopd** [comment] 2020-03-22 09:10
I am running into the same issue on the Xubuntu 18.04.2 LTS Live ISO:

```
me@host:~$ flatpak --version
Flatpak 1.6.2 # from PPA

me@host:~$ flatpak run --user --command=bash org.gnome.gedit

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/me/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

bwrap: Can't make symlink at /var/run: File exists
```

**Comment by lxbarbosa** [comment] 2020-06-27 16:44
Just run in the issue.

Debian SID 10
Kernel: 5.7.0-1-amd64
Exwm

**Comment by fallingcats** [comment] 2021-02-03 16:45
> Just run in the issue.
> 
> ```shell
> flatpak run com.valvesoftware.Steam
> 
> bwrap: Can't make symlink at $HOME/Music
> ```
> 
> Debian SID 10
> Kernel: 5.7.0-1-amd64
> Exwm

I just had this happen on fully updated Arch, also with steam.
`Flatpak 1.10.0`

**Comment by aaronw2** [comment] 2023-01-12 13:07
It's still happening in 1.12.5

**Comment by smcv** [comment] 2023-01-12 14:24
Information for anyone who is getting the symptom "Can't make symlink at /var/run: File exists":

This is an error message that can happen for multiple reasons. It's shown by a low-level component (bubblewrap) which does not have enough context to be able to tell you the reason why this is happening.

The original reason for that error message **in this specific issue** is that `XDG_RUNTIME_DIR` was set to a path starting with `/var/run`, on a system where `/var/run` was a symlink to `/run`.

Any other reason for the same error message is outside the scope of this issue. #3477 is another example of the same error message happening for a different reason. If you are seeing the same error message for a different reason, please check for other issue reports that match, and if there is none, open a separate issue with full details (including `flatpak run -vv` output so that we can see what is going on).

Please do not reply to this closed issue.

> A suggestion for the developers: put a mention of the XDG_RUNTIME_DIR variable into the error message!

No, that would be misleading. bubblewrap does not have enough information to know that the root cause for the bug involves XDG_RUNTIME_DIR.

The root cause involving XDG_RUNTIME_DIR was already fixed, the root cause involving `/var/run/media` is #3477 and has not been fixed, and there are probably other reasons why the same error message can appear.
