### ISSUE TITLE
remote-ls error: Invalid refspec org.gnome.Builder-origin:.

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#1446] opened 2018-02-22 16:33 UTC
When I run flatpak remote-ls, I get this error message:

```
$ flatpak remote-ls
error: Invalid refspec org.gnome.Builder-origin:.
```

Not sure what that means.

**Comment by mwleeds** [comment] 2018-02-22 16:42
Duplicate of #1444

**Closed by mwleeds** 2018-02-22 16:42 UTC
