### ISSUE TITLE
During install, progress bar goes beyond 100% and timestamp goes mindblown

### ISSUE THREAD

**Issue by kirisakow** [flatpak/flatpak#3448] opened 2020-03-06 01:40 UTC
## Linux distribution and version
Ubuntu 18.04.4 LTS
## Flatpak version
Flatpak 1.6.2
## Description of the problem
![Screenshot 1](https://user-images.githubusercontent.com/11773604/76165202-55ee0c80-6155-11ea-9092-f9ff887969b0.png)
![Screenshot 2](https://user-images.githubusercontent.com/11773604/76165221-88980500-6155-11ea-8553-67a612be40ca.png)

## Steps to reproduce
Just run `flatpak install flathub io.neovim.nvim` for instance. Good thing my WiFi is being particularly slow today — if it wasn't I probably wouldn't have noticed anything weird.

**Comment by rffontenelle** [comment] 2020-03-08 08:02
Got `Non-Image content-type returned` when clicking in the link. How about attaching to the bug report instead?

**Comment by kirisakow** [comment] 2020-03-08 14:58
Sorry about that. Update posted

**Comment by mwleeds** [comment] 2020-03-27 22:49
This seems to have been fixed by https://github.com/flatpak/flatpak/pull/3482. At least, I can no longer reproduce it.

**Comment by mwleeds** [comment] 2020-03-30 21:23
I can reproduce this again, so reopening. I think it was re-introduced by https://github.com/flatpak/flatpak/commit/6deb23a32231e1d88d45532130f4ffeb7d71cd54 since it goes away if I revert that.

**Comment by mwleeds** [comment] 2020-04-03 17:45
Fixed by #3530

**Closed by mwleeds** 2020-04-03 17:45 UTC
