### ISSUE TITLE
Flatpak always restarts download (?!)

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#3484] opened 2020-03-22 14:29 UTC
flatpak-1.6.2-1.fc32.x86_64
ostree-2020.2-2.fc32.x86_64
libcurl-7.69.1-1.fc32.x86_64

I'd expect the total size to download to lower, or the already download portion to be higher when starting, but here it seems to be restarting from scratch each time.

```sh
OSTREE_DEBUG_HTTP=1 flatpak install --system -y flathub runtime/org.gnome.Sdk.Debug/x86_64/3.36 2> sdk-install-log.txt
Looking for matches…


        ID                           Branch          Op         Remote          Download
 1. [✗] org.gnome.Sdk.Debug          3.36            i          flathub         54.1 MB / 3.6 GB

Error: While pulling runtime/org.gnome.Sdk.Debug/x86_64/3.36 from remote flathub: While fetching https://dl.flathub.org/repo/objects/9a/eae2c9192457b8d29dccd22309db36e2b81ea644df949566d4ac1d48dbc404.filez: [92] Stream error in the HTTP/2 framing layer
-(~)-> OSTREE_DEBUG_HTTP=1 flatpak install --system -y flathub runtime/org.gnome.Sdk.Debug/x86_64/3.36 2> sdk-install-log-2.txt
Looking for matches…


        ID                           Branch          Op         Remote          Download
 1. [✗] org.gnome.Sdk.Debug          3.36            i          flathub         74.1 MB / 3.6 GB

Error: While pulling runtime/org.gnome.Sdk.Debug/x86_64/3.36 from remote flathub: While fetching https://dl.flathub.org/repo/objects/ff/3a706a777187557ca69eae5649e5287432cde19fe3eaeba36e4c002e8a2015.filez: [92] Stream error in the HTTP/2 framing layer
-(~)-> OSTREE_DEBUG_HTTP=1 flatpak install --system -y flathub runtime/org.gnome.Sdk.Debug/x86_64/3.36 2> sdk-install-log-3.txt
Looking for matches…


        ID                           Branch          Op         Remote          Download
 1. [✗] org.gnome.Sdk.Debug          3.36            i          flathub         150.9 MB / 3.6 GB

Error: While pulling runtime/org.gnome.Sdk.Debug/x86_64/3.36 from remote flathub: While fetching https://dl.flathub.org/repo/deltas/u2/RScsHym+Ea7wqBhAEA1X7+2esauwimGgFTpWrmgVk/22: [92] Stream error in the HTTP/2 framing layer
```

**Comment by refi64** [comment] 2020-03-22 15:40
Iirc it doesn't actually restart each time, but the progress shown doesn't
signify that.

**Comment by hadess** [comment] 2020-03-22 16:31
> Iirc it doesn't actually restart each time, but the progress shown doesn't signify that.

Hence the `(?!)` in the title. Either it's redownloading everything or it needs to show that it's not, somehow.

**Comment by mwleeds** [comment] 2020-03-25 18:33
duplicate of #679

**Closed by mwleeds** 2020-03-25 18:33 UTC

**Comment by hadess** [comment] 2020-03-25 22:19
> duplicate of #679

Not quite, https://github.com/flatpak/flatpak/issues/679#issuecomment-386177211 mentions that the "to download" amount goes down, but it doesn't here.
