### ISSUE TITLE
incorrect operation of dolphin/keepassxc

### ISSUE THREAD

**Issue by Rajikoro** [flatpak/flatpak#3209] opened 2019-11-04 06:40 UTC
## Linux distribution and version
Ubuntu 18.04 + i3wm (ppa) latest

## Flatpak version
latest of ppa

##  Description of the problem
In dolphin I can not use "file type assotiations".
In keepassxc I can not open the database.

## Steps to reproduce
Install dolphin and keepassxc.
Override to dolphin: `flatpak override org.kde.dolphin –filesystem=host`
In dolphin, try setting the file extension association.
In keepassxc, create and open a database using the program itself.

**Comment by mwleeds** [comment] 2019-11-07 18:40
Is there any reason to think these issues are related to each other? Otherwise I'd say these should be separate bug reports.

**Comment by Rajikoro** [comment] 2019-11-08 11:05
@mwleeds 
I wrote information about two problems that I encountered, albeit with different software.
In order not to create separate Issues, I did everything in one.
Perhaps there is a configuration problem (no access to something) and a bug report is not required.

Thank you for your interest in my problem!

**Comment by mwleeds** [comment] 2019-11-08 18:34
Your dolphin issue sounds like a duplicate of https://github.com/flathub/org.kde.dolphin/issues/2

Depending on the version you have installed, your keepassxc issue might be a duplicate of https://github.com/flathub/org.keepassxc.KeePassXC/issues/1. If it's not, you can open a new issue on that repo.

**Closed by mwleeds** 2019-11-08 18:34 UTC
