### ISSUE TITLE
Sort refs by name before showing them

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#3483] opened 2020-03-22 14:02 UTC
flatpak-1.6.2-1.fc32.x86_64

```sh
flatpak install flathub org.gnome.Sdk.Debug
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1
Similar refs found for ‘org.gnome.Sdk.Debug’ in remote ‘flathub’ (system):

   1) runtime/org.gnome.Sdk.Debug/x86_64/3.28
   2) runtime/org.gnome.Sdk.Debug/x86_64/3.30
   3) runtime/org.gnome.Sdk.Debug/x86_64/3.34
   4) runtime/org.gnome.Sdk.Debug/x86_64/3.32
   5) runtime/org.gnome.Sdk.Debug/x86_64/3.36
   6) runtime/org.gnome.Sdk.Debug/x86_64/3.26
   7) runtime/org.gnome.Sdk.Debug/x86_64/3.24

Which do you want to use (0 to abort)? [0-7]: 
```

The choices should be sorted by version number.

**Comment by Mikenux** [comment] 2024-09-23 17:04
@hadess: Seems to be a duplicate of https://github.com/flatpak/flatpak/issues/3224

**Closed** 2024-09-27 12:00 UTC
