### ISSUE TITLE
[Bug]: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

### ISSUE THREAD

**Issue by bitseater** [flatpak/flatpak#4642] opened 2022-01-03 21:13 UTC
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Debian

### Linux distribution version

5.15.0-2-amd64

### What architecture are you using?

x86_64

### How to reproduce

Using at terminal `apt update`

### Expected Behavior

It is expected that there is no warning

### Actual Behavior

When type `apt update`, there is a warning message : 

> 
> ** (appstreamcli:11481): WARNING **: 21:53:33.554: Found icon of unknown type 'u
> nknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.
> 
> ** (appstreamcli:11481): WARNING **: 21:53:33.554: Found icon of unknown type 'u
> nknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

I haven't installed `cc.nift.nsm` from flatpak.

### Additional Information

I have tried uninstalling and reinstalling, together and separately gnome-software & appstream, after `apt purge`. It shows the same warnings, with & without flathub repository added.

**Comment by Karmavil** [comment] 2022-01-09 09:22
In my case It happened just once after
* Debian Quick Setup for flatpak ([setup guide](https://flatpak.org/setup/))
* reboot the system
* (sudo) apt update

So technically it is not reproducible (not in my case I least that's why I added a 👍🏽 )

**Comment by doczipeter** [comment] 2022-02-05 11:08
Same here. Warning comes and goes, can't reproduce for now.
Flatpak 1.12.4, Linux debian 5.15.0-3-amd64
![Screenshot from 2022-02-05 12-07-21](https://user-images.githubusercontent.com/46346136/152639574-0de3f1b2-bdc4-4edb-9db7-9feb7b0ef332.png)

**Comment by TeoColuccio** [comment] 2022-02-22 02:17
I've the same problem on debian testing 5.16.0-1.

**Comment by smcv** [comment] 2022-02-22 10:02
This is https://github.com/flathub/cc.nift.nsm/issues/3 and is unlikely to be fixed by a change in Flatpak. The correct change to resolve this would be for either: `cc.nift.nsm` to fix its metadata, or Flathub to filter it or stop publishing it.

> I haven't installed cc.nift.nsm from flatpak.

This is a problem with the Appstream metadata published by Flathub, which user interfaces like GNOME Software use to show you the applications that you *could* install, so it is normal that it is affecting everyone (not just people who have installed it). The warnings are coming from `appstreamcli` when it processes the metadata that has been downloaded by Flatpak and apt.

**Comment by smcv** [comment] 2022-02-22 10:43
If this happens again (I don't know why it's intermittent...), it might be useful for someone to find the `cc.nift.nsm` component in `/var/lib/flatpak/appstream/flathub/` and check exactly what XML it is that is triggering this warning.

I think the apt hook should not really be showing this warning: https://bugs.debian.org/1006269

**Comment by jkoking** [comment] 2022-02-22 19:03
I got the same error's when i used yay to update Arch

**Comment by smcv** [comment] 2022-02-22 20:01
> I got the same error's when i used yay to update Arch

This will likely happen to anyone whose OS has at least the same level of Appstream and Flatpak integration that Debian does: it is not particularly Debian-specific.

**Comment by ximion** [comment] 2022-02-25 05:36
Back in the day when AppStream was "new" (or being adopted by distributions, rather) we had a lot of cases where components were not visible on the clients and people had no idea why - in all the cases, the issue was in the debug logs, and in half of all cases there was some issue with the metadata generation. So I changed the code to report all issues that lead to metadata loss, which was too much output, so now AppStream will only throw a noisy warning if something gets ignored and the reason for that wasn't a naming collision.

Annoyingly there is nothing *users* can do about it, but if we show nothing, the issue is noticed at a very late time - so IMHO it's better to be a bit noisy and have the server issue fixed quickly, rather than hiding the issue and run into troubles and an annoying debug session later (also, keep in mind this issue is not shown in any GUI, ever).
So here, `appstreamcli` is rebuilding a cache of system components/apps for the operating system as well as Flatpak nowadays, which is why this message shows up in "unexpected" places. I am not sure if we should simply not build the Flatpak cache (libappstream will create one per-user in that case, so everything will still work but data is duplicated and software center startup may be slower) and limit this to OS data only, or keep the current behavior of ensuring all system-wide caches are updated.
In any case, I think Flathub shouldn't emit bad metadata but filter it out or complain at the app developer to fix their input data.

The reason why you don't see this issue all the time is simply because AppStream will only rebuild caches when needed, and keeps track of the different origins of data too (so it will not rebuild Flatpak stuff if only OS data changes, for example). If you want to reproduce this all the time, try `sudo appstreamcli refresh --force --verbose`.

So, that's for the possibly way too verbose explanation on what is going on here ;-)
This issue though (and also KDE developers) made me aware of another issue in how Flatpak uses AppStream (related to its "branches" feature), but that's a matter for a different bug report and also something that has a bunch of solutions (likely best solved by an AppStream specification extension, but let's see).

**Comment by lfom** [comment] 2022-03-05 18:07
```
$ grep cc.nift.nsm /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml
    <id>cc.nift.nsm</id>
        <image type="thumbnail" height="351" width="624">https://dl.flathub.org/repo/screenshots/cc.nift.nsm-stable/624x351/cc.nift.nsm-e21418c1536a53306b3afe593d254186.png</image>
        <image type="thumbnail" height="63" width="112">https://dl.flathub.org/repo/screenshots/cc.nift.nsm-stable/112x63/cc.nift.nsm-e21418c1536a53306b3afe593d254186.png</image>
        <image type="thumbnail" height="126" width="224">https://dl.flathub.org/repo/screenshots/cc.nift.nsm-stable/224x126/cc.nift.nsm-e21418c1536a53306b3afe593d254186.png</image>
        <image type="thumbnail" height="423" width="752">https://dl.flathub.org/repo/screenshots/cc.nift.nsm-stable/752x423/cc.nift.nsm-e21418c1536a53306b3afe593d254186.png</image>
    <launchable type="desktop-id">cc.nift.nsm.desktop</launchable>
    <bundle type="flatpak" runtime="org.freedesktop.Platform/x86_64/21.08" sdk="org.freedesktop.Sdk/x86_64/21.08">app/cc.nift.nsm/x86_64/stable</bundle>
```
No icons tho...
```
$ fd nsm /var/lib/flatpak/                   
/var/lib/flatpak/appstream/flathub/x86_64/a2580e3a7fba716438190c3623f1ce53c400a39fd50dce536141d850c1dc7b97/icons/128x128/com.transmissionbt.Transmission.png
/var/lib/flatpak/appstream/flathub/x86_64/a2580e3a7fba716438190c3623f1ce53c400a39fd50dce536141d850c1dc7b97/icons/128x128/io.github.TransmissionRemoteGtk.png
/var/lib/flatpak/appstream/flathub/x86_64/a2580e3a7fba716438190c3623f1ce53c400a39fd50dce536141d850c1dc7b97/icons/64x64/com.transmissionbt.Transmission.png
/var/lib/flatpak/appstream/flathub/x86_64/a2580e3a7fba716438190c3623f1ce53c400a39fd50dce536141d850c1dc7b97/icons/64x64/io.github.TransmissionRemoteGtk.png
```

**Comment by Dungeonseeker** [comment] 2022-03-28 08:39
Got the same issue on Arch
![con1](https://user-images.githubusercontent.com/15569173/160359324-500dbf11-934f-4543-80a1-5ff058fd0443.png)
`uname -srv 
Linux 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000`

I grabbed the entire offending XML

[appstream.zip](https://github.com/flatpak/flatpak/files/8361073/appstream.zip)

**Comment by matilde-t** [comment] 2022-04-07 16:47
Same, Pop!OS 22.04 beta (but at this point it isn't a beta issue?)

![image](https://user-images.githubusercontent.com/61622827/162255064-739bea76-b25f-4448-9fa4-915e77f69f3f.png)

**Comment by smcv** [comment] 2022-04-07 18:08
We do not need additional reports of this. It will affect basically everyone, and commenting to say "me too" does not help it to be resolved.

The way to resolve this is at least one of:

* someone with control over the app fixes the app so it doesn't contain a broken icon (https://github.com/nifty-site-manager/nsm-flatpak/issues/1, https://github.com/flathub/cc.nift.nsm/issues/3)
* someone with control over Flathub stops publishing that app, or filters it to not contain the broken icon (I hope https://github.com/flathub/website/issues/39 is the right place, but I'm not entirely clear on how Flathub fits together)

**Comment by ximion** [comment] 2022-04-07 18:55
What @smcv said, but in addition to that I will also change AppStream to not rebuild Flatpak's cache too when updating OS metadata - this will move the warning to a different place, but I think that's okay (it will likely show up in the console output of every software center then, instead of on apt updates, which probably is the better place to warn about this as it reaches the right people).

**Comment by ximion** [comment] 2022-04-10 18:18
I also think that as soon as https://github.com/flatpak/flatpak/pull/4426 lands, appstreamcli will just reject this kind of invalid data on the spot, so it doesn't even reach Flathub - so this may solve itself that way (cc.nift.nsm will still need to be fixed though).

**Comment by RedBearAK** [comment] 2022-04-25 07:38
I've been dealing with this for... I can't remember when it started but it's been happening on Ubuntu 21.10 for quite a while, and continued today when I upgraded to Ubuntu 22.04. 

I just ran `sudo appstreamcli refresh --force` and saw the same errors, but then ran `sudo apt update` a couple of times and the error is gone, at least for the moment.

**Comment by ximion** [comment] 2022-05-24 19:31
FWIW, Debian and recent Ubuntu will no longer deal with Flatpak data on apt updates and instead just create caches for its own data. That hides the issue when running APT, but the root problem is still very much there until Flathub has fixed its metadata.

**Comment by Ntemis** [comment] 2022-06-08 14:44
Same on 22.04
** (appstreamcli:4887): WARNING **: 17:40:24.404: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

** (appstreamcli:4887): WARNING **: 17:40:24.404: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.
Reading package lists... Done

**Comment by johanfleury** [comment] 2022-06-10 02:17
I’m sorry but the issue on cc.nift.nsm has been open for months and nothing has been done by the maintainer. It’s time for Flatpak/Flathub maintainers to do something or to drop the app from Flathub.

**Comment by ximion** [comment] 2022-06-10 13:27
I filed https://github.com/nifty-site-manager/nsm-flatpak/pull/2, so this should be a low hanging fruit for the NSM flatpak maintainers to resolve :-)

**Comment by martindholmes** [comment] 2022-06-13 15:08
Also on Ubuntu 22.04, flatpak 1.12.7, got this this morning:

~~~~~
** (appstreamcli:7653): WARNING **: 08:01:25.346: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

** (appstreamcli:7653): WARNING **: 08:01:25.346: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

~~~~~

What's weird is that there's no sign that I've ever installed anything called Nifty Site Manager, nor would I want to. It must be a dependency of something else, but what?

**Comment by Jacksaur** [comment] 2022-07-20 08:56
With longer than a month since a PR was offered, and a full year since the last commit, it seems clear the nsm developer has no intention of fixing this.
Can't the app at least be removed from Flathub until this is resolved?

**Comment by WFSVK** [comment] 2022-07-20 09:13
Highly agree with @Jacksaur 
If developer is not interested to make anything (in that case just to approve PR), why users should suffer?

**Comment by wrestlerdude** [comment] 2022-07-28 17:10
> Highly agree with @Jacksaur If developer is not interested to make anything (in that case just to approve PR), why users should suffer?

It might be my pessimism, but I doubt this will ever be fixed. It's extremely low hanging fruit for everyone involved. Which is frustrating because it is such a nuisance.

**Comment by smcv** [comment] 2022-07-29 09:01
> Can't the app at least be removed from Flathub until this is resolved?

Yes it could, but only by the maintainers of Flathub (a source of Flatpak apps), and not by the maintainers of Flatpak (software to install and run those apps). This issue is on the Flatpak issue tracker, not the Flathub issue tracker. Most (all?) of the maintainers of Flatpak do not have any more access to Flathub than you do, so complaining here is not going to get Flathub changed.

https://github.com/flathub/website/issues/39 is a request to resolve this in Flathub by filtering out apps with invalid metadata.

**Comment by alf-lmint** [comment] 2022-08-12 05:52
> I've been dealing with this for... I can't remember when it started but it's been happening on Ubuntu 21.10 for quite a while, and continued today when I upgraded to Ubuntu 22.04.
> 
> I just ran `sudo appstreamcli refresh --force` and saw the same errors, but then ran `sudo apt update` a couple of times and the error is gone, at least for the moment.
> 
> EDIT: The error comes back, I guess after enough time passes that the update command hits more of the default repos. But running the `appscreamcli` command above makes it temporarily go away again.

Worked beautifully for me!

**Comment by hfiguiere** [comment] 2024-02-10 22:29
solved then.

**Closed by hfiguiere** 2024-02-10 22:29 UTC
Labels: bug
