### ISSUE TITLE
Nvidia Driver Issue

### ISSUE THREAD

**Issue by ksthiele** [flatpak/flatpak#1242] opened 2017-12-11 21:08 UTC
I am on Solus and when I update flatpak I get:

```
Looking for updates...
Installing: org.freedesktop.Platform.GL.nvidia-340-104/x86_64/1.4 from flathub
[####################] Downloading: 38.6 MB/38.6 MB (3.9 MB/s) 
Warning: Failed to install org.freedesktop.Platform.GL.nvidia-340-104/x86_64/1.4: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Updating: org.freedesktop.Platform.GL.nvidia-340-102/i386/1.4 from gnome
[####################] Downloading: 38.8 MB/38.8 MB (3.9 MB/s)                 
Error: Failed to update org.freedesktop.Platform.GL.nvidia-340-102/i386/1.4: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Updating: org.freedesktop.Platform.GL.nvidia-340-104/i386/1.4 from flathub
[####################] Downloading: 38.8 MB/38.8 MB (4.9 MB/s)
Error: Failed to update org.freedesktop.Platform.GL.nvidia-340-104/i386/1.4: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
error: One or more operations failed
```

**Comment by TingPing** [comment] 2017-12-11 21:20
Duplicate of #1237

**Closed by TingPing** 2017-12-11 21:20 UTC
