### ISSUE TITLE
Tab completion + update/upgrade aliases interact badly

### ISSUE THREAD

**Issue by davidstrauss** [flatpak/flatpak#4072] opened 2021-01-14 18:40 UTC
## Linux distribution and version

Not version-specific.

## Flatpak version

Not version-specific.

## Description of the problem

The `upgrade` and `update` subcommands are aliases of each other, but tab completion still stops at `up` because it's basically offering a fork in road where both choices end up in the same destination. But, `up` isn't a valid subcommand, so the CLI then forces the user to make a distinction without a difference by expanding the subcommand to one of the two longer aliases.

## Steps to reproduce

`flatpak up` + TAB

## Suggested resolutions

There are a couple options:

- Only tab-complete to the primary subcommand (preferred option).
- Accept `up` as a third member of this set of equivalent subcommands.

**Comment by mwleeds** [comment] 2021-01-22 23:39
duplicate of #4036

**Closed by mwleeds** 2021-01-22 23:39 UTC
