### ISSUE TITLE
Terminating a process using libflatpak causes undesirable state

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak#4258] opened 2021-05-05 03:20 UTC
If you have a process that is using libflatpak, it is possible it crashes for a number of reasons (or sigkill/sigterm). In this case, running a transaction again often fails because the repository is in a state such as:

```
Aborted due to failure (Failed to read commit fd2f895c5326eb56a1a5290dd65f8c75582bfaab360bd206022c2ad13c603730: No such metadata object 35f97be8e0fc52120f8c4c592e135bfc0c60c1799f9113b3cba458df40a3245d.dirtree)
```

It would be nice if the operations were done in such a way that we don't have to run `flatpak --user repair` to recover from a crash.

This has been affecting us quite a bit in Builder, not because it crashes, but because people cancel the installation transactions (for whatever reasons).

**Comment by mwleeds** [comment] 2022-02-19 21:48
This seems almost certainly a duplicate of #3479 which will be fixed by #4765.

**Closed by mwleeds** 2022-02-19 21:48 UTC
